### ISSUE TITLE
How to find receive address using wallet version 23.1.0

### ISSUE THREAD

**Issue by zydjohnHotmail** [qtumproject/qtum#1005]
Hello:
I have installed Qtumcore wallet for Windows (x64 for testnet), the version is: Qtum Core version v23.1.0.  
I have run it for a few hours, now it has synced, and has all the blocks from Qtum testnet blockchain. However, I created 2 wallets on this wallet software, I can see the wallets' names, but how can I see the wallets' addresses?
I read some documents about the Qtum Core wallet, but the documents are talking about old version of the wallet, none of them is talking about v23.1.0.
Any suggestions on how to find the wallet address, so I can use the wallet address to get some free tokens via faucet.
Refer to the attached screen shot to understand what I am talking about.
![QtumCoreWalletNoAddress](https://user-images.githubusercontent.com/45263518/232329192-2e0e88d8-178d-4567-82dc-eb58a6baea46.png)

Thanks,

**Comment by herryben** [comment]
您好，我已收到您的邮件，我会尽快给您回复。

**Comment by qtum-neil** [comment]
You can see a receive address when you click the Receive button. you can get more addresses by clicking Address Refresh

**Comment by zydjohnHotmail** [comment]
Hi,
I figure this out, the older version (20.03) has the receive address, also has the QR code for the receive address, but the latest version 23.1 doesn't show the receive address. You can try to do some testing and you will know.
