### ISSUE TITLE
No faucet available for testnet.

### ISSUE THREAD

**Issue by zydjohnHotmail** [qtumproject/qtum#1006]
Hello:
I want to get some free QTUM tokens from faucet for testing. I have tried the following URLs:
https://testnet-faucet.qtum.info/
https://testnet.qtum.info/faucet
https://faucet.qtum.org/testnet/
https://testnet.qtum.org/faucet
But they are either 404 (page not found) or can not be reached, I am now living in Spain. Any other faucets where I can get some free QTUM tokens for testing?
Thanks,

**Comment by mikehash** [comment]
Hello, that is the faucet, it might have been down at the time of writing. Please do try again. Cheers !
