### ISSUE TITLE
Status: 0/unconfirmed, not in memory pool  Sent QTUM to external wallet and no transaction showing, WHERE's MY MONEY??

### ISSUE THREAD

**Issue by qtiphead** [qtumproject/qtum#1009]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by mikehash** [comment]
Hello, if you're still having this issue, please do provide us with more information :

- TX ID
- Origin and destination wallet address (in case you don't have a TX ID)
