### ISSUE TITLE
make failed on linux, error: call to deleted constructor of 'util::Result<std::unique_ptr<AddrMan, std::default_delete<AddrMan> > >::T' (aka 'std::unique_ptr<AddrMan, std::default_delete<AddrMan> >')

### ISSUE THREAD

**Issue by wangzuo2023** [qtumproject/qtum#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

root@xxxx:~/qtum-27.1# make
Making all in src
make[1]: Entering directory '/root/qtum-27.1/src'
make[2]: Entering directory '/root/qtum-27.1/src'
  CXX      qtumd-bitcoind.o
  CXX      init/qtumd-bitcoind.o
  CXX      libbitcoin_node_a-addrdb.o
addrdb.cpp:216:12: error: call to deleted constructor of 'util::Result<std::unique_ptr<AddrMan, std::default_delete<AddrMan> > >::T' (aka 'std::unique_ptr<AddrMan, std::default_delete<AddrMan> >')
    return addrman;
           ^~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:468:7: note: 'unique_ptr' has been explicitly marked deleted here
      unique_ptr(const unique_ptr&) = delete;
      ^
./util/result.h:47:14: note: passing argument to parameter 'obj' here
    Result(T obj) : m_variant{std::in_place_index_t<1>{}, std::move(obj)} {}
             ^
1 error generated.
make[2]: *** [Makefile:15050: libbitcoin_node_a-addrdb.o] Error 1
make[2]: Leaving directory '/root/qtum-27.1/src'
make[1]: *** [Makefile:27751: all-recursive] Error 1
make[1]: Leaving directory '/root/qtum-27.1/src'

### Expected behaviour

make success

### Steps to reproduce

make

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v24.0.1

### Operating system and version

Ubuntu 20.04.6 LTS

**Comment by qtum-neil** [comment]
Try cloning in a clean directory.
