### ISSUE TITLE
Qtum Core v27.1 cannot be built

### ISSUE THREAD

**Issue by fatminer** [qtumproject/qtum#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I am building Qtum core on Ubuntu 22.04 based on the README.
when I run make, I get the following error:

```
make[2]: *** [Makefile:14184: eth_client/libdevcrypto/libbitcoin_common_a-CryptoPP.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/workspace/src'
make[1]: *** [Makefile:27753: all-recursive] Error 1
make[1]: Leaving directory '/workspace/src'
make: *** [Makefile:841: all-recursive] Error 1
```
I've run it in several environments, but it ends up with the same error.

### Expected behaviour

The build completes successfully.

### Steps to reproduce

I am following the contents of the README below.
The path is set properly.

https://github.com/qtumproject/qtum?tab=readme-ov-file#build-on-ubuntu

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v27.1

### Operating system and version

Ubuntu 22.04

**Comment by qtum-neil** [comment]
Try cloning on a clean directory, also post the full error logs.

**Comment by qtum-neil** [comment]
Looks like you are not using the proper version of evmone submodule, make sure to properly update submodules.

**Comment by fatminer** [comment]
I am planning to update the submodules as mentioned in the README.
Does this mean that there is an error in the README content?

> git submodule update --init --recursive
