### ISSUE TITLE
Failed on make

### ISSUE THREAD

**Issue by ethought** [qtumproject/qtum#207]
#### If so, please list the steps to reproduce below:
1. ./autogen.sh
2. ./configure
3. make

### Actual behaviour
make[2]: *** No rule to make target 'cpp-ethereum/deps/lib/libsecp256k1.a', needed by 'libbitcoinconsensus.la'.  Stop.

### Machine specs:
- OS: Debian
- RAM: 32 GB

**Comment by mcgtts** [comment]
Mac os 10.12.5
```shell
./autogen.sh
./configure
make
```

Error:

```
Making all in src
  CXX      crypto/libbitcoinconsensus_la-aes.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha256.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CXX      libbitcoinconsensus_la-arith_uint256.lo
  CXX      consensus/libbitcoinconsensus_la-merkle.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      primitives/libbitcoinconsensus_la-block.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      script/libbitcoinconsensus_la-script_error.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[2]: *** No rule to make target `cpp-ethereum/deps/lib/libsecp256k1.a', needed by `libbitcoinconsensus.la'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by Earlz** [comment]
Did you run this command before ./autogen.sh ?

    git submodule update --init --recursive

**Comment by ethought** [comment]
@Earlz - Yes, I ran that first.

**Comment by Earlz** [comment]
And ./autogen.sh didn't show any kind of errors?

**Comment by ethought** [comment]
@Earls - no errors on ./autogen.sh or ./configure.

**Comment by Earlz** [comment]
Strange. I'll try to reproduce it

**Comment by ethought** [comment]
@Earlz tried again from scratch and got this from ./autogen.sh after running the submodule update command:

src/Makefile.am: installing 'build-aux/depcomp'
src/Makefile.am:532: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.14/am/depend2.am: ... overrides Automake target '.mm.o' defined here
parallel-tests: installing 'build-aux/test-driver'
Installing cpp-ethereum dependencies on Debian Linux.
./scripts/install_deps.sh: 151: ./scripts/install_deps.sh: sudo: not found

**Comment by Earlz** [comment]
Oh. Guess we never thought about sudo not already being installed. Install sudo via apt-get and make sure you're in the sudoers file

**Comment by ethought** [comment]
Prefer not to use sudo, especially on production servers. Any way around that?

**Comment by Earlz** [comment]
You might try editing autogen.sh to remove ./scripts/install_deps.sh and call it manually (using su). You might also need to modify install_deps.sh to not use sudo also. After running install_deps, then use ./autogen.sh

Note install_deps does more than just install apt-get packages, in most cases it also compiles some dependencies, so it's not trivial to prevent it's use completely

**Comment by ethought** [comment]
Have installed literally hundreds of different wallets, never had to have sudo installed.

**Comment by tekahuna** [comment]
If youʻre really adamant about not using sudo, along the lines of what Earlz said, I would try something like the following:

1. comment out the ./scripts/install_deps.sh line in autogen.sh
2. `su`
3. `apt-get update`
4. `apt-get install libcurl4-openssl-dev libgmp-dev libleveldb-dev libmicrohttpd-dev libminiupnpc-dev`
5. `exit`
6. `./autogen.sh`

Basically, manually install the deps through apt-get that are not in the Qtum build instuctions, and comment out calling install_deps.sh in autogen.sh.  Does that get you over the hump?  For Debian it appears all that all install_deps.sh does is run those two apt-get commands.  

This appears however to be a personal issue, and not a general issue, as Ethereum in general, for all Linux versions calls sudo to update dependencies, unless built as root.

**Comment by ethought** [comment]
@tekahuna 

No. There are now all sorts of other errors I suspect could also be related to sudo.

I don't have time to keep trying to get it working right now.

As a side not building Geth from source does not require sudo as far as I am aware.

**Comment by tekahuna** [comment]
@ethought 

Correctoid, I should have said cpp-ethereum.  Sorry to hear youʻre still having trouble getting it built according to your criteria.  It can be tough taking a road less traveled.  Blessings on your journey!

**Comment by Earlz** [comment]
Assuming you removed the sudo references and still installed all the required dependencies, I don't think you should be having this many problems. Which exact version of Debian are you using?

**Comment by Earlz** [comment]
Closing for now, please reopen if issue persists
