### ISSUE TITLE
How to get the initial qtum coin to stake on the testnet?

### ISSUE THREAD

**Issue by jibuji** [qtumproject/qtum#215]
It seems in order to mine qtum coin, one should have some coin on staking, but nobody has coin on the testnet initially, how can I get out of this dilemma?

**Comment by Earlz** [comment]
There will be a public faucet setup soon so that people can get some coins for testing. In the meantime, if you post your Qtum address I can send you some coins

**Comment by polefishu** [comment]
I have the same problem.

**Comment by polefishu** [comment]
my qtum address is QfymdrbbQSWjeJEXytXzt59DPVVqdTgQe1

**Comment by mcguang** [comment]
my address:  QTiPqxD1zmPRnM4iT7cnhh7VAVoWYk63Le

**Comment by Earlz** [comment]
Sent to both

**Comment by millileakz** [comment]
0x06a87aa8e5e1a35fcbcb731b2d60e4600407c67f may i have some please sire :)

**Comment by bobomurod** [comment]
my address: QjgWVizHLAj35LACWMVxU8Yg6MZ88QvBzS

**Comment by MSDevYT** [comment]
Would be very helpful if someone could send me the smalest amount possible.. 
My Adress: QiDhW41MKrwv1U5nKEazLxRebHtnmBt4Ex
Thanks.. :)

**Comment by LiboDing** [comment]
qRE5mMKdxUUNNMkRNBuqoypZf5dskWh4pW

**Comment by freshonline** [comment]
Why don't work "gen=1", "-gen", "-regtest generate 101" and etc?
I need coins to qarBfjK8t8y7xLHh4gkNz5yNmx9Hcrz9eh
