### ISSUE TITLE
qtum compile error

### ISSUE THREAD

**Issue by ghost** [qtumproject/qtum#216]
Hi, I followed the Quickstart  instructions , and met an error on my ubuntu 14.04, with newest code, could anyone have a look at it ?

error info is attached.
[compile_error_info.txt](https://github.com/qtumproject/qtum/files/1111709/compile_error_info.txt)

**Comment by qtum-neil** [comment]
Try using gcc 5 or 6.

**Comment by Earlz** [comment]
Please try following the new instructions from #226 and see if that resolves the problem

**Comment by Earlz** [comment]
Closing. Please file another issue if those instructions did not resolve your problem
