### ISSUE TITLE
lost some test token in the wallet?

### ISSUE THREAD

**Issue by mcguang** [qtumproject/qtum#236]
OS : ubuntu 14.04

I run the qtum wallet in my own machine, and got 10000 QTUM from  @Earlz  
(ID: b459f0adeaf6e63d90035f23210d57bdc4434580cb3cbbf92822a0a25175aad8) 。

I also got (131+92+160) QTUM from the Faucet . 
(ID: 8913eeb7579577e1580d6dae63051a5174711bdff5540b2f08837fd12fb04fce;
ID: 26c8b558aba644f282e36fa9a03112c190d9a066f5e4fb25cbf0d5fa1e8b4396;
ID: 0e46ed75288c332753aef6829341a7be250a57de5617a6d133c920050680f8da
)

also mining (4+4+4) QTUM
(
ID: 5fb2384aa1a0e68e64197206d4b12e5328416d78c6d67f40ac455f02ce834c9c
ID: c9adbf36da5e049f1daf3f689a486c77507dae673f0c423aa6e795e1630e5403
ID: 7ea5328e91a22ca70e2df2d6df9ec24dba8b66d7e5baffd200324e787ce8e696
)

**The total amount should be 10000+131+92+160+4+4+4 = 10395.**

But, when I run 

```
./qtum-cli getwalletinfo                                   
{
  "walletversion": 130000,
  "balance": 9507.09198461,
  "stake": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 10,
  "keypoololdest": 1498722091,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "hdmasterkeyid": "f98f6dc526d064e83364f5ed7f72b997eef00512"
}
```
**I just have 9507 QTUM in my wallet,  means lost 10395-9507 = 888QTUM.**

by testing the transaction, I send QTUM to myself 2 times, every transaction cost 0.00004520 QTUM as fee.
(
ID: 8d4d8b8b6c48f5a21802607c79ea41900989581774c520dec4f4968b93cd7ee2
ID: 254c37d49bdd6bdff8a5a47b0b4beed2cc9e8e94a087f46c5d88543e60b20351
)

one of the self transation, I send 888QTUM to this address
(https://qtum.info/address/QchZm2zLLnn979RYh2ZF3JgiGAjiiSP1Mc)

I wonder If I lost the private key of (QchZm2zLLnn979RYh2ZF3JgiGAjiiSP1Mc) ?

` ./qtum-cli dumpprivkey "QchZm2zLLnn979RYh2ZF3JgiGAjiiSP1Mc"
KxSWWXrRcomCfWNpLhPPSpghFBEr9a8AAvZUzkWHUZZnsUGZjUJm
`
 [dumpprivkey]  shows that I have the private key.

so, I want to know, is this  a bug? 
maybe I didn't discribe it very clear,you can ask me any details if needed.

**Comment by Earlz** [comment]
Would you mind uploading your wallet.dat file?

**Comment by Earlz** [comment]
Also try starting qtumd with the command line argument `-zapwallettxes=1` and/or `-rescan`. These should rescan the blockchain for transactions belonging to your wallet and pick up any missing coins. However, this still shouldn't have happened unless you imported or restored a private key backup

**Comment by mcguang** [comment]
I tried the command line argument you recommend, but it didn't work.
This is my wallet file.
[wallet.zip](https://github.com/qtumproject/qtum/files/1157842/wallet.zip)

**Comment by Earlz** [comment]
Still have not been able to determine why this happens or reproduce the issue, closing for now
