### ISSUE TITLE
Question: what's the numeric shortcut for currency in QTUM solidity?

### ISSUE THREAD

**Issue by yuanfeiz** [qtumproject/qtum#248]
I used to write something like:
```
2 ether == 2000 finney
```
Does QTUM provide the same shortcuts? It's kinda weird in that `msg.value` in QTUM is actually qtum rather than ether.

**Comment by Earlz** [comment]
We currently do not have one built into Solidity but you can define your own. This is what I used in my contract @yuanfeiz . We currently have no plans of forking Solidity to add a custom Qtum unit

    uint constant COIN = 100000000;
