### ISSUE TITLE
Failed to compile due to "No rule to make libethereum.a"

### ISSUE THREAD

**Issue by yuanfeiz** [qtumproject/qtum#265]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
Failed to compile due to "No rule to make libethereum.a"

Error logs:
```
make[2]: *** No rule to make target `cpp-ethereum/libethereum/libethereum.a', needed by `qtumd'.  Stop.
```

### What version of Qtum are you using?
4269a882e83bbda7e6f272f337a67cf2170231f4

### Machine specs:
- OS: macOS 10.12.6
- CPU: 3.1 GHz Intel Core i7
- RAM: 16G

**Comment by Earlz** [comment]
Please make sure to do make clean and ./autogen ./configrue after the latest series of commits changing the build system

**Comment by Earlz** [comment]
Closing, please reopen if the problem persists
