### ISSUE TITLE
Where can I get qtum test net IP or URLs?

### ISSUE THREAD

**Issue by harikrishnanp** [qtumproject/qtum#294]
Where can I get qtum test net IP or URLs?

**Comment by Earlz** [comment]
There are no set of IPs needed, they are already configured into the wallet

**Comment by Earlz** [comment]
please reopen if more help is needed

**Comment by harikrishnanp** [comment]
I don't want to use wallet. What is the corresponding seeds for qtum test net like this ? https://github.com/bcoin-org/bcoin/blob/master/lib/net/seeds/testnet.js

**Comment by xiaolujidan** [comment]
How to call the test address remotely

**Comment by shannon1916** [comment]
> I don't want to use wallet. What is the corresponding seeds for qtum test net like this ? https://github.com/bcoin-org/bcoin/blob/master/lib/net/seeds/testnet.js

https://github.com/qtumproject/qtum/blob/master/src/chainparams.cpp#L252
