### ISSUE TITLE
The qtum(d|-qt) wallet does not work with the -txindex=0 option set.

### ISSUE THREAD

**Issue by crypt0m1nd3r** [qtumproject/qtum#300]
Having -txindex=0 set will cause the following after 5000 blocks:
```
2017-08-24 02:38:39 UpdateTip: new best=00003c57e285d10548029fa1fddded5de6e3d70fd707bc6f3a8fd9cee8ab2b6a height=5000 version=0x20000003 log2_work=28.288023 tx=5016 date='2017-08-14 10:36:29' progress=1.000000 cache=2.1MiB(5015tx)
2017-08-24 02:38:39 ProcessNetBlock: ACCEPTED
2017-08-24 02:38:39 ERROR: CheckProofOfStake() : INFO: read txPrev failed
2017-08-24 02:38:39 ERROR: AcceptBlock() : check proof-of-stake failed for block b4230bc023cc422bee78f75575852c155d110f2b538f1e3992fd836581ed0be8
2017-08-24 02:38:39 ERROR: AcceptBlock: UpdateHashProof():
```

NOTE: The first 5000 blocks of Qtum are POW (which is why it barfs at block 5000), see:
- https://github.com/qtumproject/qtum/blob/testnet-skynet-v1.1/src/chainparams.cpp#L165

The stack generating the debug log message `ERROR: CheckProofOfStake() : INFO: read txPrev failed` is:
-> https://github.com/qtumproject/qtum/blob/testnet-skynet-v1.1/src/pos.cpp#L114
--> https://github.com/qtumproject/qtum/blob/testnet-skynet-v1.1/src/validation.cpp#L1358
---> https://github.com/qtumproject/qtum/blob/testnet-skynet-v1.1/src/txdb.cpp#L150
----> https://github.com/qtumproject/qtum/blob/testnet-skynet-v1.1/src/dbwrapper.h#L206

The code https://github.com/qtumproject/qtum/blob/testnet-skynet-v1.1/src/validation.cpp#L1358 is added by Qtum (i.e. not present in Bitcoin).

I was trying to set up a 'steady-state' wallet (i.e. that doesn't grow without bounds) by using the -prune=<n> option which also requires using -txindex=0 .  However, by using -txindex=0, the leveldb index at <data_dir>/blocks/index/ isn't maintained and causes the error above.

I can submit a PR to either show a WARNING message, or terminate the qtum(d|-qt) in the init phase if either -prune=<n> or -txindex=0 is set.  Alternatively, these options can be removed entirely from the Qtum wallet.

Yet another option is to maintain the txindex even with pruning enabled (although I haven't looked into the potential consequences of this).

**Comment by Earlz** [comment]
Being able to even use `-txindex=0` was actually intended to be impossible. We don't support that at all because in order for the blockchain to check PoS block stakes at the consensus level it must use the txindex because manually scanning through blocks would be far too slow and would be an obvious DoS attack vector

**Comment by crypt0m1nd3r** [comment]
Yeah, clearly it won't work as it's written -- which is why I'm suggesting to submit a PR to remove the -prune and -txindex options from the wallet.  Would you be ok with me submitting a PR to remove these 2 options (I wanted to check with you before doing so)?

**Comment by Earlz** [comment]
I think there is hope for -prune working at some point with some modifications, and really there is no need to track transactions in txindex that are already spent, so there is definitely hope for a 'steady-state' configuration of Qtum at some point... That being said, definitely feel free to submit a PR, I don't expect we will have time to do anything but disable them until after the mainnet release so a PR to do that would be much appreciated, even if we later revert it to try to fix it.

**Comment by crypt0m1nd3r** [comment]
Ok, I'll send a PR to handle/disable the two options tomorrow (Thursday).  It would indeed be great to be able to run the wallet (e.g. for staking) with a fairly bounded resource requirement, and I agree that it can wait until the mainnet is released to look into doing this.

**Comment by Earlz** [comment]
fixed
