### ISSUE TITLE
Getting build error running autogen.sh

### ISSUE THREAD

**Issue by dwalintukan** [qtumproject/qtum#316]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
Getting the following error when trying to run `./autogen.sh`. I am in `the testnet-2` branch, but also tried this in `master` and got the same error.
```
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:45: error: required file 'build-aux/ltmain.sh' not found
autoreconf: automake failed with exit status: 1
```

### Can you reliably reproduce the issue?
Yes this happens every time I try to run the script.

#### If so, please list the steps to reproduce below:
1. run `./autogen.sh`

### Machine specs:
- OS: Mac OSX 10.12.6 Sierra 
- CPU:
- RAM: 16GB 
- Disk size:

**Comment by Earlz** [comment]
That's strange. It appears to not be finding `sed`. For OSX that should be in /usr/bin/sed, that's the a base system utility. Are you operating in a container or chroot environment or something?

**Comment by dwalintukan** [comment]
@Earlz Nope not in a special container or environment.

**Comment by Earlz** [comment]
If you search the internet for "/usr/local/Library/ENV/4.3/sed: No such file or directory" then you'll find a lot of other projects have the same issue, something with a brew upgrade. Maybe try doing a repair or reinstall of brew. It's not an issue specific to Qtum though either way, and not something any of us can reproduce.

**Comment by dwalintukan** [comment]
Ok no problem. Will try to sort this out. Thanks for the help!
