### ISSUE TITLE
OSX Qtum-qt korean translate issue 

### ISSUE THREAD

**Issue by mentalese** [qtumproject/qtum#356]
There is an error in translating the Korean language.
'비트코인' means BITCOIN. 
please change to '큐텀' or QTUM.

<img width="1019" alt="main_send" src="https://user-images.githubusercontent.com/82263/30386704-79c6a08a-98e5-11e7-9d7f-1b1010999709.png">
<img width="760" alt="file_receive" src="https://user-images.githubusercontent.com/82263/30386706-7c206492-98e5-11e7-8ccb-35217ab9ede3.png">
<img width="760" alt="file_send" src="https://user-images.githubusercontent.com/82263/30386709-7f2d98bc-98e5-11e7-834d-69a90b8ce751.png">

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/pull/357
Will be part of the next release, thanks for reporting.

**Comment by mentalese** [comment]
You'd better decide the official korean name of QTUM. It is called '퀀텀' in coinone, and '퀀텀' and '큐텀' in community.
