### ISSUE TITLE
No rule to make target 'cpp-ethereum/utils/libscrypt/b64.c'

### ISSUE THREAD

**Issue by Bushstar** [qtumproject/qtum#359]
I'm wondering if the build docs need to be updated for Qtum?

On Windows Subsystem for Linux I get an error trying to build the depends folder, this is for cross compilation for a Windows client with the build environment set up to build Bitcoin 0.13, I've not tested it on newer Bitcoin codebases. For reference I'm running Windows 10 64-bit.

Steps to reproduce the error.

    Install Windows Subsystem For Linux, run bash, accept license.

    // Install tools, deps and 32-bit mingw
    sudo apt-get install libboost-all-dev libminiupnpc-dev libzmq3-dev libdb4.8-dev libdb4.8++-dev libssl-dev libevent-dev
    sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl
    sudo apt-get install g++-mingw-w64-i686 mingw-w64-i686-dev 

    // Strips out Windows PATHs that create problems during compilation
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

    cd depends

    // Specify Autotools as blank to avoid "missing automake-1.14" error
    make HOST=i686-w64-mingw32 V=1 AUTOCONF=: AUTOHEADER=: AUTOMAKE=: ACLOCAL=:
    cd ..
    ./autogen.sh
    ./configure --prefix=`pwd`/depends/i686-w64-mingw32 --with-miniupnpc --with-qrencode --disable-tests --disable-gui-tests --disable-dependency-tracking --disable-bench
    make

    Making all in src
    make[1]: Entering directory '/mnt/f/github/HTMLCOIN/src'
    make[2]: Entering directory '/mnt/f/github/HTMLCOIN/src'
      CXX      crypto/libbitcoinconsensus_la-aes.lo
      CXX      crypto/libbitcoinconsensus_la-hmac_sha256.lo
      CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
      CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
      CXX      crypto/libbitcoinconsensus_la-sha1.lo
      CXX      crypto/libbitcoinconsensus_la-sha256.lo
      CXX      crypto/libbitcoinconsensus_la-sha512.lo
    make[2]: *** No rule to make target 'cpp-ethereum/utils/libscrypt/b64.c', needed by 'cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-b64.lo'. Stop.
    make[2]: Leaving directory '/mnt/f/github/HTMLCOIN/src'
    Makefile:12740: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/mnt/f/github/HTMLCOIN/src'
    Makefile:692: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

**Comment by Bushstar** [comment]
Nevermind, I've only just spotted that Eth CPP is a submodule that needs to be pulled.

**Comment by 1000ml** [comment]
Hey Bushstar, How do you resolve this ? I have the same trouble. Thanks

**Comment by Bushstar** [comment]
First time you checkout Qtum run.

git submodule update --init --recursive

Subsequent times run the following to update submodules.

git submodule update --recursive

**Comment by 1000ml** [comment]
Ok thanks !

**Comment by 1000ml** [comment]
Still have a problem ;/ . " `g++:` internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Makefile:8975: recipe for target 'libbitcoin_server_a-validation.o' failed
make[2]: *** [libbitcoin_server_a-validation.o] Error 4recipe for target 'all-recursive' failed"`

**Comment by 1000ml** [comment]
Hello Bushstar, I sucessfully compiled thanks to you. But I can't launch the qt wallet. It's an executable but he ask my which with application I wanna run the executable.. Any help ?

**Comment by Bushstar** [comment]
What OS are you building on?

**Comment by 1000ml** [comment]
Raspberry pi3 using git source

**Comment by Bushstar** [comment]
There's quite a few different OS you can run on a Pi. I did have a similar issue running on a Mac and running from a terminal allowed it to start.

**Comment by 1000ml** [comment]
In fact from the terminal it's Ok. Thanks 👍

**Comment by weltonmattos** [comment]
Thanks @Bushstar

**Comment by chenluyong** [comment]
Thanks @Bushstar

**Comment by mnoumanuaar32xc** [comment]
Hi 
when I make changes in Qtum and Compile it show following errors

make[1]: Entering directory '/home/ubuntu/qtumcusmto/src'                                                                                                                                        make[2]: Entering directory '/home/ubuntu/qtumcusmto/src'                                                                                                                                        make[3]: Entering directory '/home/ubuntu/qtumcusmto'                                                                                                                                            make[3]: Leaving directory '/home/ubuntu/qtumcusmto'                                                                                                                                             make[2]: *** No rule to make target 'cpp-ethereum/utils/libscrypt/b64.c', needed by 'cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-b64.lo'.  Stop.                                         make[2]: *** Waiting for unfinished jobs....                                                                                                                                                     make[2]: Leaving directory '/home/ubuntu/qtumcusmto/src'                                                                                                                                         Makefile:14755: recipe for target 'all-recursive' failed                                                                                                                                         make[1]: *** [all-recursive] Error 1                                                                                                                                                             make[1]: Leaving directory '/home/ubuntu/qtumcusmto/src'                                                                                                                                         Makefile:779: recipe for target 'all-recursive' failed                                                                                                                                           make: *** [all-recursive] Error 1
--
Is there any solution :)
