### ISSUE TITLE
Qtum Address is not valid osx Qt wallet

### ISSUE THREAD

**Issue by snakeys** [qtumproject/qtum#361]
I use the mac os Qtum qt wallet. (qtum-0.14.3-osx-unsigned)

After i try to change coins with changelly i get the message Address is not valid.

i use some qt wallet generated address, but it dosent work.

same on shapeshift.
someone can try QN36yx7Tar1aRBPKuRMncctMhpnzv7QHDi

**Comment by 1000ml** [comment]
Same here

**Comment by Earlz** [comment]
Works for me


```
validateaddress QN36yx7Tar1aRBPKuRMncctMhpnzv7QHDi
{
  "isvalid": true,
  "address": "QN36yx7Tar1aRBPKuRMncctMhpnzv7QHDi",
  "scriptPubKey": "76a9140fb8432b6411b2a9aa4c02a3e669dfdc23da2a4d88ac",
  "ismine": false,
  "iswatchonly": false,
  "isscript": false
}
```

**Comment by jaybkim1** [comment]
Could anyone try mine, too?

QT6n1wsko3fhZWq7yuGudpyTAsKRC5oakU
