### ISSUE TITLE
ledger/trezor/digitalbitbox for qtum wallet? 

### ISSUE THREAD

**Issue by briannyeko** [qtumproject/qtum#364]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
when will you have a qtum ledger/trezor/digitalbitbox wallet? 
#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Earlz** [comment]
This is coming as soon as we can make it happen. We will release an Electrum wallet soon and are actively working with Ledger to get Chrome app support
