### ISSUE TITLE
Bitcoin addresses left in code

### ISSUE THREAD

**Issue by Bushstar** [qtumproject/qtum#372]
There's still some Bitcoin addresses left in the code.

https://github.com/qtumproject/qtum/blob/master/src/rpc/misc.cpp#L321

https://github.com/qtumproject/qtum/blob/master/src/wallet/rpcwallet.cpp#L1532

https://github.com/qtumproject/qtum/blob/master/src/wallet/rpcwallet.cpp#L2989

**Comment by Earlz** [comment]
Fixed in #373
