### ISSUE TITLE
Trojan Trojan.MSIL.Disfa.mdvr in qtumd.exe

### ISSUE THREAD

**Issue by Audit08** [qtumproject/qtum#377]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
I was trying to install the mainnet, but my kaspersky antivirus complains that the qtumd.exe has trojan Trojan.MSIL.Disfa.mdvr inside. The test network was working fine before.
### Can you reliably reproduce the issue?
yes, tryied several times.
#### If so, please list the steps to reproduce below:
1. check \qtum-0.14.3\bin\test_qtum.exe or \qtum-0.14.3\bin\qtumd.exe from the windows qtum-0.14.3-win64.zip with antivirus

### Expected behaviour
No malware inside

### Actual behaviour
Trojan.MSIL.Disfa.mdvr found in \qtum-0.14.3\bin\test_qtum.exe and \qtum-0.14.3\bin\qtumd.exe

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS: Windows 10 64bit
- CPU: Intel I5 650
- RAM: 4GB
- Disk size: 1TB

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by tommyms** [comment]
Don't mean to hijack your thread, just downloaded qtum-0.14.3-win64-setup-unsigned.exe. When I launched it, had to reboot. It said it contained Trojan:Win32/Tilken.B!cl 
Windows Defender deleted it and I had to reboot. Are these real or false positives? Now I can't trust Qtum's files until this is cleared up.

**Comment by imshyuan** [comment]
I downloaded my qtum from https://github.com/qtumproject/qtum/releases/download/mainnet-ignition-v1.0.2/qtum-0.14.3-win64.zip. My Kaspersky detected exactly the same thing.

Trojan Trojan.MSIL.Disfa.mdvr - test_qtum.exe
Trojan Trojan.MSIL.Disfa.mdvo - qtumd.exe

**Comment by Earlz** [comment]
These are false positives. We are currently speaking to Anti-Virus vendors about this.

**Comment by douglasdeodato** [comment]
got the same, so it is a virus or not?
