### ISSUE TITLE
use of deleted function

### ISSUE THREAD

**Issue by wangh09** [qtumproject/qtum#378]
Hi, I got this error when making qtum by ` make -j2`:

CXX      cpp-ethereum/libethereum/libbitcoin_common_a-ExtVM.o
In file included from /usr/include/boost/optional.hpp:15:0,
                 from /usr/include/boost/format/internals.hpp:20,
                 from /usr/include/boost/format.hpp:38,
                 from /usr/include/boost/math/policies/error_handling.hpp:31,
                 from /usr/include/boost/multiprecision/detail/default_ops.hpp:9,
                 from /usr/include/boost/multiprecision/detail/generic_interconvert.hpp:9,
                 from /usr/include/boost/multiprecision/number.hpp:22,
                 from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from ./cpp-ethereum/libdevcore/Common.h:51,
                 from ./cpp-ethereum/libethcore/Common.h:28,
                 from cpp-ethereum/libethereum/ExtVM.h:26,
                 from cpp-ethereum/libethereum/ExtVM.cpp:22:
/usr/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::construct(boost::optional_detail::optional_base<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional_detail::optional_base<T>::argument_type = const dev::eth::owning_bytes_ref&]’:
/usr/include/boost/optional/optional.hpp:230:20:   required from ‘boost::optional_detail::optional_base<T>::optional_base(boost::optional_detail::optional_base<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional_detail::optional_base<T>::argument_type = const dev::eth::owning_bytes_ref&]’
/usr/include/boost/optional/optional.hpp:526:46:   required from ‘boost::optional<T>::optional(boost::optional<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional<T>::argument_type = const dev::eth::owning_bytes_ref&]’
cpp-ethereum/libethereum/ExtVM.cpp:108:22:   required from here
/usr/include/boost/optional/optional.hpp:346:8: error: use of deleted function ‘dev::eth::owning_bytes_ref::owning_bytes_ref(const dev::eth::owning_bytes_ref&)’
        new (m_storage.address()) internal_type(val) ;
        ^
In file included from cpp-ethereum/libethereum/ExtVM.h:27:0,
                 from cpp-ethereum/libethereum/ExtVM.cpp:22:
./cpp-ethereum/libevm/ExtVMFace.h:72:2: error: declared here
  owning_bytes_ref(owning_bytes_ref const&) = delete;

**Comment by wangh09** [comment]
fixed by upgrading boost to 1.65

**Comment by dusupark** [comment]
Why don't you add the following sentence to 'Build on Ubuntu' on ReadMe.md?

Note: The version of Boost must be 1.65 or later.
