### ISSUE TITLE
Error making qtum

### ISSUE THREAD

**Issue by wangh09** [qtumproject/qtum#379]
Got this error:
  CXXLD    test/test_qtum_fuzzy
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `GetNumCores()':
/home/ubuntu/qtum/src/util.cpp:852: undefined reference to `boost::thread::physical_concurrency()'
libbitcoin_util.a(libbitcoin_util_a-utiltime.o): In function `sleep_for':
/usr/local/include/boost/thread/pthread/thread_data.hpp:252: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
  CXXLD    qtumd
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_qtum_fuzzy] Error 1
make[2]: *** Waiting for unfinished jobs....
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `GetNumCores()':
/home/ubuntu/qtum/src/util.cpp:852: undefined reference to `boost::thread::physical_concurrency()'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `MaybePushAddress':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1859: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `getreceivedbyaddress(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:970: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `ListReceived(UniValue const&, bool)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1690: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1693: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `sendmany(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1349: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `sendmanywithdupes(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1463: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `SendMoney':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:364: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `createcontract(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:591: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:538: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `ListTransactions(CWalletTx const&, std::string const&, int, bool, UniValue&, unsigned char const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1881: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1909: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `listaccounts(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:2123: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `listunspent(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:3037: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `getreceivedbyaccount(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1044: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1044: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `setaccount(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:256: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `sendtocontract(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:747: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `sendtocontract(JSONRPCRequest const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:801: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress::CBitcoinAddress(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): In function `Witnessifier::operator()(CKeyID const&)':
/home/ubuntu/qtum/src/wallet/rpcwallet.cpp:1564: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `copy_file':
/usr/local/include/boost/filesystem/operations.hpp:539: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::IsChange(CTxOut const&) const':
/home/ubuntu/qtum/src/wallet/wallet.cpp:1487: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWalletTx::GetAmounts(std::list<COutputEntry, std::allocator<COutputEntry> >&, std::list<COutputEntry, std::allocator<COutputEntry> >&, long&, std::string&, unsigned char const&) const':
/home/ubuntu/qtum/src/wallet/wallet.cpp:1717: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::DelAddressBook(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)':
/home/ubuntu/qtum/src/wallet/wallet.cpp:3551: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::GetAddressBalances()':
/home/ubuntu/qtum/src/wallet/wallet.cpp:3739: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::CreateTransaction(std::vector<CRecipient, std::allocator<CRecipient> > const&, CWalletTx&, CReserveKey&, long&, int&, std::string&, CCoinControl const*, bool, long, bool)':
/home/ubuntu/qtum/src/wallet/wallet.cpp:2881: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/wallet/wallet.cpp:2859: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/wallet/wallet.cpp:3090: undefined reference to `CTxMemPool::CalculateMemPoolAncestors(CTxMemPoolEntry const&, std::set<boost::multi_index::detail::hashed_index_iterator<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolEntry, std::allocator<CTxMemPoolEntry> > > > > > >, boost::multi_index::detail::hashed_unique_tag>, boost::multi_index::detail::bucket_array<std::allocator<CTxMemPoolEntry> >, boost::multi_index::detail::hashed_index_global_iterator_tag>, CTxMemPool::CompareIteratorByHash, std::allocator<boost::multi_index::detail::hashed_index_iterator<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolEntry, std::allocator<CTxMemPoolEntry> > > > > > >, boost::multi_index::detail::hashed_unique_tag>, boost::multi_index::detail::bucket_array<std::allocator<CTxMemPoolEntry> >, boost::multi_index::detail::hashed_index_global_iterator_tag> > >&, unsigned long, unsigned long, unsigned long, unsigned long, std::string&, bool) const'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::AddKeyPubKey(CKey const&, CPubKey const&)':
/home/ubuntu/qtum/src/wallet/wallet.cpp:353: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::SetAddressBook(boost::variant<CNoDestination<CKeyID, CScriptID> > const&, std::string const&, std::string const)':
/home/ubuntu/qtum/src/wallet/wallet.cpp:3525: undefined reference to `IsMine(CKeyStore const&, boost::variant<CNoDestination<CKeyID, CScriptID> > const&, SigVersion)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::GetAccountPubkey(CPubKey&, std::string, bool)':
/home/ubuntu/qtum/src/wallet/wallet.cpp:1031: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CWallet::GetAddressGroupings()':
/home/ubuntu/qtum/src/wallet/wallet.cpp:3803: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
/home/ubuntu/qtum/src/wallet/wallet.cpp:3773: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
/home/ubuntu/qtum/src/wallet/wallet.cpp:3786: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CAffectedKeysVisitor::Process(CScript const&)':
/home/ubuntu/qtum/src/wallet/wallet.cpp:4041: undefined reference to `ExtractDestinations(CScript const&, txnouttype&, std::vector<boost::variant<CNoDestination<CKeyID, CScriptID> >, std::allocator<CNoDestination<CKeyID, CScriptID> > >&, int&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcdump.o): In function `ImportScript(CScript const&, std::string const&, bool)':
/home/ubuntu/qtum/src/wallet/rpcdump.cpp:175: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcdump.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcdump.o): In function `ImportAddress(CBitcoinAddress const&, std::string const&)':
/home/ubuntu/qtum/src/wallet/rpcdump.cpp:183: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcdump.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcdump.o): In function `ProcessImport(UniValue const&, long)':
/home/ubuntu/qtum/src/wallet/rpcdump.cpp:682: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/wallet/rpcdump.cpp:741: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/wallet/rpcdump.cpp:826: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
/home/ubuntu/qtum/src/wallet/rpcdump.cpp:834: undefined reference to `GetScriptForDestination(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
/home/ubuntu/qtum/src/wallet/rpcdump.cpp:899: undefined reference to `ExtractDestination(CScript const&, boost::variant<CNoDestination<CKeyID, CScriptID> >&, txnouttype*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcdump.o): In function `CBitcoinAddress':
/home/ubuntu/qtum/src/./base58.h:113: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_util.a(libbitcoin_util_a-utiltime.o): In function `sleep_for':
/usr/local/include/boost/thread/pthread/thread_data.hpp:252: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-rbf.o): In function `IsRBFOptIn(CTransaction const&, CTxMemPool&)':
/home/ubuntu/qtum/src/policy/rbf.cpp:39: undefined reference to `CTxMemPool::CalculateMemPoolAncestors(CTxMemPoolEntry const&, std::set<boost::multi_index::detail::hashed_index_iterator<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolEntry, std::allocator<CTxMemPoolEntry> > > > > > >, boost::multi_index::detail::hashed_unique_tag>, boost::multi_index::detail::bucket_array<std::allocator<CTxMemPoolEntry> >, boost::multi_index::detail::hashed_index_global_iterator_tag>, CTxMemPool::CompareIteratorByHash, std::allocator<boost::multi_index::detail::hashed_index_iterator<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolEntry, std::allocator<CTxMemPoolEntry> > > > > > >, boost::multi_index::detail::hashed_unique_tag>, boost::multi_index::detail::bucket_array<std::allocator<CTxMemPoolEntry> >, boost::multi_index::detail::hashed_index_global_iterator_tag> > >&, unsigned long, unsigned long, unsigned long, unsigned long, std::string&, bool) const'
collect2: error: ld returned 1 exit status
make[2]: *** [qtumd] Error 1
make[2]: Leaving directory `/home/ubuntu/qtum/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/qtum/src'
make: *** [all-recursive] Error 1

**Comment by Earlz** [comment]
What version of Boost are you using, and which operating system?

**Comment by Earlz** [comment]
Could not reproduce

**Comment by wangh09** [comment]
Hi, This error was found on Ubuntu 14.04, and I managed to find out that it was caused by the versions of the dependencies. I just moved to docker, but I think there should be some guide on using different operating systems, or at least tell others to use >=16.04 (ubuntu for example). Thanks anyway!

**Comment by dusupark** [comment]
@wangh09 Are you sure Qtum Core cannot be built on Ubuntu 14.04 LTS?

**Comment by silence48** [comment]
I get this error on ubuntu 18.04
