### ISSUE TITLE
open ssl issue. while installing ubuntu linux on make command

### ISSUE THREAD

**Issue by inzig** [qtumproject/qtum#382]
CXX      libbitcoin_common_a-key.o
key.cpp: In function ‘bool EnsureLowS(std::vector<unsigned char>&)’:
key.cpp:149:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (BN_cmp(sig->s, halforder) > 0) {
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                                  ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
Makefile:7303: recipe for target 'libbitcoin_common_a-key.o' failed
make[2]: *** [libbitcoin_common_a-key.o] Error 1
make[2]: Leaving directory '/home/iqvis/Downloads/qtum/src'
Makefile:12811: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/iqvis/Downloads/qtum/src'
Makefile:692: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Earlz** [comment]
What version of OpenSSL and what OS version?

**Comment by leejh970** [comment]
Ubuntu 16.04.3 LTS
OpenSSL 1.1.0f 

and i'm having same issue with him, even the error codes are same

**Comment by inzig** [comment]
Hello Jordan @Earlz .. Waiting for follow up on this issue
Ubuntu 16.04.3 LTS
OpenSSL 1.1.0f

**Comment by felipemcmont** [comment]
In debian you can fix this problem with a downgrade
apt-get install libssl1.0-dev

**Comment by inzig** [comment]
tried that didn't work ,.

**Comment by Earlz** [comment]
When downgrading OpenSSL did you make sure to uninstall the new version, or explicitly tell ./configure to use the old version? It is probably still detecting the newer version

**Comment by EricCrosson** [comment]
Downgrading openssl fixed the issue for me

```
$ sudo apt-get install libssl1.0-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libssl-doc
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  libssl-dev
The following NEW packages will be installed:
  libssl1.0-dev
0 upgraded, 1 newly installed, 1 to remove and 4 not upgraded.
Need to get 1,150 kB of archives.
After this operation, 80.9 kB of additional disk space will be used.
Get:1 http://mirrors.syringanetworks.net/raspbian/raspbian stretch/main armhf libssl1.0-dev armhf 1.0.2l-2+deb9u1 [1,150 kB]
Fetched 1,150 kB in 2s (499 kB/s)
(Reading database ... 57394 files and directories currently installed.)
Removing libssl-dev:armhf (1.1.0f-3+deb9u1) ...
Selecting previously unselected package libssl1.0-dev:armhf.
(Reading database ... 57308 files and directories currently installed.)
Preparing to unpack .../libssl1.0-dev_1.0.2l-2+deb9u1_armhf.deb ...
Unpacking libssl1.0-dev:armhf (1.0.2l-2+deb9u1) ...
Setting up libssl1.0-dev:armhf (1.0.2l-2+deb9u1) ...

$ make
```

👍

**Comment by brunocasado** [comment]
ubuntu 16.04 lts solution

sudo apt install libssl-dev=1.0.2g-1ubuntu4

**Comment by tmzlatiajs** [comment]
Making all in src
make[1]: Entering directory `/home/qtum_data/qtum/src'
make[2]: Entering directory `/home/qtum_data/qtum/src'
  CXX      crypto/libbitcoinconsensus_la-aes.lo
  CXX      crypto/libbitcoinconsensus_la-chacha20.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha256.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-b64.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto-mcf.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-check.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-hash.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-hexconvert.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-nosse.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto-scrypt-saltgen.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-sha256.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-slowequals.lo
  CXX      libbitcoinconsensus_la-arith_uint256.lo
  CXX      consensus/libbitcoinconsensus_la-merkle.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      primitives/libbitcoinconsensus_la-block.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      script/libbitcoinconsensus_la-script_error.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory `/home/qtum_data/qtum/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
make[3]: Leaving directory `/home/qtum_data/qtum/src/secp256k1'
  CXXLD    libbitcoinconsensus.la
copying selected object files to avoid basename conflicts...
  CXX      qtumd-bitcoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-dbwrapper.o
  CXX      libbitcoin_server_a-merkleblock.o
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-net_processing.o
  CXX      libbitcoin_server_a-noui.o
  CXX      policy/libbitcoin_server_a-fees.o
  CXX      policy/libbitcoin_server_a-policy.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-pos.o
  CXX      libbitcoin_server_a-rest.o
  CXX      rpc/libbitcoin_server_a-blockchain.o
  CXX      rpc/libbitcoin_server_a-mining.o
  CXX      rpc/libbitcoin_server_a-misc.o
  CXX      rpc/libbitcoin_server_a-net.o
  CXX      rpc/libbitcoin_server_a-rawtransaction.o
  CXX      rpc/libbitcoin_server_a-server.o
  CXX      script/libbitcoin_server_a-sigcache.o
  CXX      script/libbitcoin_server_a-ismine.o
  CXX      libbitcoin_server_a-timedata.o
  CXX      libbitcoin_server_a-torcontrol.o
  CXX      libbitcoin_server_a-txdb.o
  CXX      libbitcoin_server_a-txmempool.o
  CXX      libbitcoin_server_a-ui_interface.o
  CXX      libbitcoin_server_a-validation.o
  CXX      libbitcoin_server_a-validationinterface.o
  CXX      libbitcoin_server_a-versionbits.o
  CXX      qtum/libbitcoin_server_a-qtumstate.o
  CXX      qtum/libbitcoin_server_a-qtumtransaction.o
  CXX      qtum/libbitcoin_server_a-qtumDGP.o
  CXX      consensus/libbitcoin_server_a-consensus.o
  CXX      qtum/libbitcoin_server_a-storageresults.o
  AR       libbitcoin_server.a
  CXX      libbitcoin_common_a-amount.o
  CXX      libbitcoin_common_a-base58.o
  CXX      libbitcoin_common_a-chainparams.o
  CXX      libbitcoin_common_a-coins.o
  CXX      libbitcoin_common_a-compressor.o
  CXX      libbitcoin_common_a-core_read.o
  CXX      libbitcoin_common_a-core_write.o
  CXX      libbitcoin_common_a-key.o
key.cpp: In function ‘bool EnsureLowS(std::vector<unsigned char>&)’:
key.cpp:149:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (BN_cmp(sig->s, halforder) > 0) {
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: error: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: error: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                                  ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: error: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
make[2]: *** [libbitcoin_common_a-key.o] Error 1
make[2]: Leaving directory `/home/qtum_data/qtum/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/qtum_data/qtum/src'
make: *** [all-recursive] Error 1


my server Environment

OS - Linux xxxxxxx-X10SLL-F 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux openssl version - OpenSSL 1.0.2g

How can I solve this problem?

**Comment by timemarkovqtum** [comment]
`ECDSA_SIG_st` is private for 1.1, so another possible fix (workaround) is to define it in `qtum/src/key.cpp` before it is used:

```
#include <openssl/opensslv.h>

#if OPENSSL_VERSION_NUMBER >= 0x10100000L
typedef struct ECDSA_SIG_st {
    BIGNUM *r;
    BIGNUM *s;
} ECDSA_SIG;
#endif
```

**Comment by qtum-neil** [comment]
Fixed in https://github.com/qtumproject/qtum/commit/3bb11303525156cea41e972a2f578155fa8d04d0

**Comment by Bandicoot** [comment]
Ubuntu 18.04 LTS requires:

sudo apt install libssl-dev=1.0.2n-1ubuntu4.10

**Comment by Vishwas1** [comment]
Guys how long it takes to finally build the Qtum-bitcore after running make command? For me it is running since past 20mins?
