### ISSUE TITLE
How to call test faucet for qtum core?

### ISSUE THREAD

**Issue by inzig** [qtumproject/qtum#383]
How to call test faucet for qtum core? qtum.me provide for skynet and sparknet not for qtum core.

**Comment by Earlz** [comment]
We've had problems with people draining our faucets and hoarding testnet coins. We are looking into a better solution. For right now if you need testnet coins, please ask with your address on our reddit https://reddit.com/r/qtum, or in our Slack community.

**Comment by inzig** [comment]
@Earlz  Thanks for getting in touch. I am using reddit group. but i am unable get answers.
I am blockchain developer and our organization is looking to Make dapps on top of Qtum core. 
Is there any language to communicate i.e (web3.js in ethereum , Blockstack.js in blockstack)??

Please give me starting point to start development.

**Comment by qtum-neil** [comment]
@inzig you can request test coins here: http://testnet-faucet.qtum.info

Currently, what you can use to communicate are rpc calls, you can also have a look at our bitcore API: https://github.com/qtumproject/insight-api/blob/master/README.md

Another solution would be to fork bitcoin tools like bitcoinjs ...

We will provide more tools and documentation for developers soon.
