### ISSUE TITLE
How to build a Dapp on top of Qtum core,. can we have a demo

### ISSUE THREAD

**Issue by inzig** [qtumproject/qtum#385]
I am a blockchain developer. I am building dapps (web apps using Node) in blockstack and ethereum. How can i use build dapps in qtum?
How can i find liberary?

**Comment by Earlz** [comment]
Please ask these kinds of questions at our reddit https://reddit.com/r/qtum or in our Slack community. This issue tracker is only for technical problems related to Qtum Core. There is some documentation out there about getting started with Qtum: https://steemit.com/qtum/@cryptominder/quantum-qtum-blockchain-developer-tutorial-hello-world
