### ISSUE TITLE
Consensus:ContextualCheckBlockHeader Error Issue

### ISSUE THREAD

**Issue by akahard2dj** [qtumproject/qtum#386]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
When wallet starts a PoS, Consensus::ContextualCheckBlockHeader error is occurred.
But OS time is already syncing to timeserver.

When I change a timezone from SEOUL to UTC, the error is cleared. 

interestingly, there is no error in ubuntu but sporadically happening.

#### If so, please list the steps to reproduce below:
1. In my opinion, it is not applying a time with timezone when a PoS call a function of int64_t GetTime() in qtum/src/utiltime.cpp

### Expected behaviour
Tell us what should happen

### Actual behaviour
error messages in debug.log

Error Message:
2017-10-16 13:00:30 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 38d0ffe1e9ac3c6832ef0423e28295ec9db611a8cd7f36420af74b1de14fc320, time-too-new, block timestamp too far in the future (code 16)
2017-10-16 13:00:30 ERROR: invalid header received

### What version of Qtum are you using?
last release version

### Machine specs:
- OS: windows10, ubuntu
- CPU: 
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Earlz** [comment]
Does everything still work when your timezone is set to Seoul? Like does it download the entire blockchain?

**Comment by akahard2dj** [comment]
Yes. It seems to be ok for a staking when the timezone is SEOUL.
what does that mean a downloading the entire blockchain?
I already have downloaded the entire blockchain.

**Comment by Earlz** [comment]
Could not reproduce

**Comment by noctime** [comment]
Hi there, I'm having the same issue. 
I starting in UTC timezone mining 1 block, but I moved to UTC +1 and this started to promt. 
I tried re-formatting the computer,  setting timezone back to UTC and even creating a new wallet but I'm still stuck in this.
I need help!

**Comment by rootux** [comment]
Hi there. I'm having the same issue. Just started out of the blue.
I've moved to seoul recently. Not sure if related

**Comment by rootux** [comment]
Also syncing my clock with
sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"

**Comment by rootux** [comment]
This is the fix - Sync your date clock
sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
