### ISSUE TITLE
Unable to restore wallet.dat

### ISSUE THREAD

**Issue by dotnetspec** [qtumproject/qtum#396]
I recently tried re-opening my original QTUM wallet (ver 0.14.0). It reported 0 node connections and was unable to update the blockchain (stuck at 31 weeks behind), so effectively never opens and I am unable to access my QTUM. I therefore downloaded the latest wallet ver 0.14.3 which synchronized successfully but didn't recognize/display the QTUM from the ver. 0.14 wallet. The original wallet, when I attempt to open, now reports "Error loading block database. Do you want to rebuild the block database now?" and then, when I do, gets stuck at 31 weeks behind again with 0 node connections. I tried your instructions for restoring the wallet but no data directory is re-created in Windows: %APPDATA%\Qtum (on my system I have: E:\AppData\qtum)

So now the old wallet won't sync and the new wallet won't recognize any QTUM in my wallet.dat. What am I doing wrong?

Steps to reproduce below:
1. Start Qtum-Qt.32bit.Windows.exe wallet (ver.  0.14.0)
2. or start ver 0.14.3 wallet

### Expected behaviour
Wallet syncs and QTUM balance (non-zero) displays

### Actual behaviour
For 1: stuck at 31 weeks behind
For 2: balance displays zero

### What version of Qtum are you using?
Tried both 0.14.0 and 0.14.3

### Machine specs:
- OS: win 10
- CPU: x86 32 bit
- RAM: 2GB
- Disk size: 28 GB on C: + 28 GB on E: (now configured as D:) USB drive

**Comment by Dubbeldwars** [comment]
Hi dotnetspec

I have the same issue right now..Do you already have a sollution for it? i cant find anything :( hope to hear from you!

**Comment by dotnetspec** [comment]
Hi Dubbledwars,
I have no solution currently. I have posted to the Reddit as well. I have tried the -rescan and -reindex flags as suggested with the cli. Perhaps there is someone out there that can help?

**Comment by Dubbeldwars** [comment]
ppff :(... I also dowloaded the new wallet on a other laptop and tried to use my wallet.dat file 
but nothing seems to work.

**Comment by mikehash** [comment]
Sorry for the very late response, are you still getting this issue ?

**Comment by dotnetspec** [comment]
Hi

Has anything been changed? I can try again ...

**Comment by mikehash** [comment]
Please update to the latest wallet, restore from backup and select "salvagewallet" as shown here:
https://github.com/qtumproject/qtum/wiki/Qtum-Wallet-Tutorial#on-windows

**Comment by dotnetspec** [comment]
Will do.

**Comment by dotnetspec** [comment]
Hi,

I get 'insufficient permissions' when I try to download:
Qtum Core
0.14.13  2018-01-08
(never had that problem on my machine before)

Qtum Electrum
0.17.5  2018-01-08
downloads and loads ok, but on attempting to load wallet.dat the app crashes

what should I try next?
