### ISSUE TITLE
Failed to make -j2 ./cpp-ethereum/libevm/ExtVMFace.h:72:2: error: declared here

### ISSUE THREAD

**Issue by biskandar** [qtumproject/qtum#397]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
Failed to make -j2

/usr/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::construct(boost::optional_detail::optional_base<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional_detail::optional_base<T>::argument_type = const dev::eth::owning_bytes_ref&]’:
/usr/include/boost/optional/optional.hpp:230:20:   required from ‘boost::optional_detail::optional_base<T>::optional_base(boost::optional_detail::optional_base<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional_detail::optional_base<T>::argument_type = const dev::eth::owning_bytes_ref&]’
/usr/include/boost/optional/optional.hpp:526:46:   required from ‘boost::optional<T>::optional(boost::optional<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional<T>::argument_type = const dev::eth::owning_bytes_ref&]’
cpp-ethereum/libethereum/ExtVM.cpp:108:22:   required from here
/usr/include/boost/optional/optional.hpp:346:8: error: use of deleted function ‘dev::eth::owning_bytes_ref::owning_bytes_ref(const dev::eth::owning_bytes_ref&)’
        new (m_storage.address()) internal_type(val) ;
        ^
In file included from cpp-ethereum/libethereum/ExtVM.h:27:0,
                 from cpp-ethereum/libethereum/ExtVM.cpp:22:
./cpp-ethereum/libevm/ExtVMFace.h:72:2: error: declared here
  owning_bytes_ref(owning_bytes_ref const&) = delete;
  ^
make[2]: *** [cpp-ethereum/libethereum/libbitcoin_common_a-ExtVM.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/opt/lacak/qtum/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/lacak/qtum/src'
make: *** [all-recursive] Error 1

#### If so, please list the steps to reproduce below:
1. ./autogen.sh
2. ./configure
3. make -j2

### Machine specs:
- OS: Ubuntu 14.04
- CPU: 4G
- RAM: 4G
- Disk size: 64G

**Comment by 2101648015pio** [comment]
我也遇到这个问题了，apt安装的boost版本比较低，官网下载安装最新版boost就好了

**Comment by Earlz** [comment]
You need a more up to date version of Boost.

**Comment by rootux** [comment]
@Earlz I'm getting a similar version and I have the latest `Boost` library

**Comment by rootux** [comment]
@Earlz Can you please specify which `Boost` library we should be compiling against?

**Comment by rootux** [comment]
So actually we have 1.54 version of boost which is 4 years old
