### ISSUE TITLE
Wallet issue

### ISSUE THREAD

**Issue by Dubbeldwars** [qtumproject/qtum#405]
My pc has been crashed and now i downloaded the new Qtum software on my pc 
I have stored my wallet.dat file correctly and when i tried to replace it all again it aint loading my new wallet.
I have backed it up 3 times, last time was last night (today new pc) 
I have tried all the information i could find and youtube restore features..but nothing seems to work.

Is it possible to help me ?

This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1.downloaded new wallet
2.using wallet.dat file
3.all blocks has been loaded

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
the wallet does not restore 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID
01.4.7.0
### Machine specs:
Windows

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Earlz** [comment]
Did you make sure to place the wallet.dat file in the correct data directory for Qtum?

**Comment by ozee1** [comment]
I have a problem where the wallet app Qtum core is not opening (it seems its running in the background though) while i didnt do any backup ? does anybody know how to help?
