### ISSUE TITLE
Staking not working or super slow with QRC 20 version?

### ISSUE THREAD

**Issue by kiahmed** [qtumproject/qtum#406]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
since I upgraded to QRC 20 version of wallet, it was never able to get any reward for staking. Even tho it shows its staking and 90 other nodes connected to my node with 82 incoming and 8 outgoing. The approximate days to get reward is extremely variable and its been running since last 12 days with weight 1747? Any thoughts what to do to improve?

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS: Win2012 r2
- CPU: intrl cor i5 4 core
- RAM: 16 gb
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Earlz** [comment]
Staking is always up to chance and network conditions. A notable number of people have dry-spells where they can go 2-3x as much time as the "expected time". In addition, when there are more people staking, you are less likely to stake a block and your expected time decreases. If you are having problems with never getting a block, then you should make sure that your wallet is unlocked for staking.

**Comment by kiahmed** [comment]
understood..thanks for the reply. I had few blocks. Yesterday I noticed got .40 reward but just to mature that it took 2/3 of my stake offline and was only staking with few. Is there any way to tweak that or not necessary ?
