### ISSUE TITLE
Release documentation lists SHA512 as file hash instead of SHA256

### ISSUE THREAD

**Issue by aaronmboyd** [qtumproject/qtum#410]
### Describe the issue
Documentation issue only.

Hash sums in download section of Release pages are listed as SHA512 when they appear to be SHA256.

```
sha512sum qtum-0.14.8-x86_64-linux-gnu.tar.gz | grep a94a5e61473eb83a90e34bae29b1d44af8ed966cac09003148778aa63a46e081

<no result>
```

```
sha256sum qtum-0.14.8-x86_64-linux-gnu.tar.gz | grep a94a5e61473eb83a90e34bae29b1d44af8ed966cac09003148778aa63a46e081

a94a5e61473eb83a90e34bae29b1d44af8ed966cac09003148778aa63a46e081
```

**Comment by Earlz** [comment]
good catch. We will make sure to specify that it is a SHA512 hash in the next release.

**Comment by aaronmboyd** [comment]
@Earlz Additionally, I checked the _Contributing_ page before submitting an issue, and it still references the Bitcoin project.
