### ISSUE TITLE
virtual memory exhausted: Cannot allocate memory

### ISSUE THREAD

**Issue by bereska** [qtumproject/qtum#412]
# building qtum for stacking on ubuntu 16.04 vm on AWS, I ran into this at step 'make -j2'

ubuntu@ip-172-31-46-217:~/qtum$ make -j2
Making all in src
make[1]: Entering directory '/home/ubuntu/qtum/src'
make[2]: Entering directory '/home/ubuntu/qtum/src'
  CXX      crypto/libbitcoinconsensus_la-chacha20.lo
  CXX      crypto/libbitcoinconsensus_la-aes.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha256.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-b64.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto-mcf.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-check.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-hash.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-hexconvert.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto_scrypt-nosse.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-crypto-scrypt-saltgen.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-sha256.lo
  CC       cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-slowequals.lo
  CXX      consensus/libbitcoinconsensus_la-merkle.lo
  CXX      primitives/libbitcoinconsensus_la-block.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      script/libbitcoinconsensus_la-script_error.lo
  CXX      libbitcoin_server_a-addrman.o
**virtual memory exhausted: Cannot allocate memory**
Makefile:8715: recipe for target 'libbitcoin_server_a-addrman.o' failed
make[2]: *** [libbitcoin_server_a-addrman.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/ubuntu/qtum/src'
Makefile:13327: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/qtum/src'
Makefile:692: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
ubuntu@ip-172-31-46-217:~/qtum$ free -m
              total        used        free      shared  buff/cache   available
Mem:            990          47         835           6         108         807
Swap:             0           0           0

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Earlz** [comment]
Use `make -j1`. In general, Qtum requires 1G of RAM per thread to build, so if your VPS only has 1G of RAM, then only use one thread

**Comment by bereska** [comment]
thank you)

**Comment by bereska** [comment]
unfortunately i have the same problem after running make -j1
does  it have anything to do with my aws security settings? should i edit inbound rules to let all traffic in? now it is limited to my current location ip via ssh only

**Comment by qtum-neil** [comment]
Try increasing the swap memory to 4gb.

**Comment by bereska** [comment]
could you give me ALL requirements for a VPS to run qtum staking? ram, swap, volume, etc.
