### ISSUE TITLE
Cannot Unencrypt Wallet after Ubuntu Backup on Windows

### ISSUE THREAD

**Issue by DEADP0OL** [qtumproject/qtum#417]
### Describe the issue
I am able to unlock, stake, and send qtum from my wallet on a linux computer. When I export the wallet.dat file to my windows computer, I am unable to unencrypt the wallet with the same password. I am able to see the correct account balances and transactions. 

#### If so, please list the steps to reproduce below:
1. Back up wallet on Ubuntu computer
2. Replace wallet.dat file on windows computer with the Ubuntu wallet.dat file
3. Start qtum on windows computer, unable to unencrypt wallet with same password

### Expected behaviour
I expect to be able to unlock the same wallet on my windows computer to make transactions.

### Actual behaviour
I am able to unlock the wallet on my linux (origin) computer but not on my windows computer.

**Comment by mikehash** [comment]
Hello, we haven't been able to reproduce this issue, please make sure there are no caps locked on the windows computer.

**Comment by DEADP0OL** [comment]
I got it to work after using the salvagewallet instructions.
