### ISSUE TITLE
Kaspersky detects Trojan virus in Qtum Core (Windows 64-bit)

### ISSUE THREAD

**Issue by peterjmarko** [qtumproject/qtum#423]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
Scan by Kaspersky Total Security finds Trojans in two Qtum EXE files:

- Trojan.MSIL.Disfa.mlia in qtum-qt.exe (main app)
- Trojan.Win32.Generic in qtumd.exe (daemon)

#### If so, please list the steps to reproduce below:
1. Start Kaspersky Total Security
2. Click Scan in main window
3. Wait (the two EXE files above will be identified and moved to the quarantine)

### Expected behaviour
EXE files should be virus-free

### Actual behaviour
Trojans identified in EXE files. This might be a false positive but assurances by the development would be needed.

### What version of Qtum are you using?
Qtum Core version v0.14.8.0-2a7afc9-dirty (64-bit)

**Comment by Earlz** [comment]
This is a known issue. We've contacted Kaspersky and 2 other anti-virus vendors about this.

**Comment by peterjmarko** [comment]
Thank you!
