### ISSUE TITLE
qtum "staking": false / vps

### ISSUE THREAD

**Issue by bereska** [qtumproject/qtum#432]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
I had some qtum staking in my vps qtumd
After sending some more qtum to the same address of this wallet, it stopped staking.
I understand that the new qtum must mature for 500+ confirmations but what about the old qtum in the same wallet? isn't it supposed to keep on staking?! Or do i have to re-initiate staking somehow after receiving more qtum?
Please help
Thanks

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
ubuntu@qtum-node:~$ qtum-cli getstakinginfo
{
  "enabled": true,
  "staking": true,
  "errors": "",
  "currentblocksize": 1000,
  "currentblocktx": 0,
  "pooledtx": 11,
  "difficulty": 1989470.594889778,
  "search-interval": 61451,
  "weight": 367713986,
  "netstakeweight": 1536883446364730,
  "expectedtime": 534983951
}
ubuntu@qtum-node:~$ qtum-cli getinfo
{
  "version": 140800,
  "protocolversion": 70016,
  "walletversion": 130000,
  "balance": 102.62468607,
  "stake": 0.00000000,
  "blocks": 59534,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": {
    "proof-of-work": 1.52587890625e-05,
    "proof-of-stake": 2505131.843143152
  },
  "testnet": false,
  "moneysupply": 100218136,
  "keypoololdest": 1511735172,
  "keypoolsize": 100,
  "unlocked_until": 2512674092,
  "paytxfee": 0.00000000,
  "relayfee": 0.00400000,
  "errors": ""
}
ubuntu@qtum-node:~$ qtum-cli getstakinginfo
{
  "enabled": true,
  "staking": false,
  "errors": "",
  "currentblocksize": 1000,
  "currentblocktx": 0,
  "pooledtx": 2,
  "difficulty": 2773252.680092013,
  "search-interval": 61579,
  "weight": 0,
  "netstakeweight": 1774236146417864,
  "expectedtime": 0
}

**Comment by bereska** [comment]
i forgot to mention that before receiving more qtum to this address, i sent 1 qtum from this address to other wallet for testing. Maybe it was this sendtoaddress operation that reset the staking amount? i am just guessing since i did't netinfo after spending

**Comment by mikehash** [comment]
I'm not sure if your wallet was encrypted or not, if it was, then you need to unlock your wallet for staking first, in any case, your staking was affected by that 1 Qtum you sent out to the other wallet, when an outgoing transaction takes place, a "change" transaction is sent back to your wallet. I'm sure you're not getting this issue anymore.
