### ISSUE TITLE
下载钱包并且同步数据后，怎么查看自己在不在节点map里？

### ISSUE THREAD

**Issue by z7658329** [qtumproject/qtum#433]
下载钱包并且同步数据后，怎么查看自己在不在节点map里？
![image](https://user-images.githubusercontent.com/5474723/33796638-b6cc3930-dd33-11e7-9fe9-1b71ff095317.png)
![image](https://user-images.githubusercontent.com/5474723/33796639-b6d66112-dd33-11e7-983c-44b4726b66b5.png)

**Comment by Baiqiang** [comment]
节点地图使用种子节点的peerinfo作为数据源，如果你连上了其中一个种子节点，那么就在地图里，否则不在。
