### ISSUE TITLE
running qtumd on a vps

### ISSUE THREAD

**Issue by bereska** [qtumproject/qtum#435]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
first of all THANKS for the great tutorial
i just launched my qtumd, bought some coins and started staking. All looks good for now.
However I've noticed that qtumd -daemon stops after reboot so I have to restart it and open wallet for staking manually again.
Is there a way to automate this without exposing password too much?
thank you

**Comment by hhmingw** [comment]
The command " qtum-cli walletpassphrase password seconds true" is used to open wallet for staking, but it is not safe to automate due to the exposing wallet password.
