### ISSUE TITLE
Staking broken since nov27

### ISSUE THREAD

**Issue by greggdourgarian** [qtumproject/qtum#438]
What's up with staking problems?  There is a whole [thread](https://www.reddit.com/r/Qtum/comments/7h54jl/no_staking_reward_since_27th_nov/) of ppl complaining about it on reddit since several days ago w no dev response as far as i can tell.  Getting the same issue myself.   Met up with a qtum rep in Columbia who told me it was a version issue even though i had been staking successfully before.

**Comment by pandazwb** [comment]
First, Please update to the latest release of Qtum core: https://github.com/qtumproject/qtum/releases ;
And then follow the instructions for Staking: https://github.com/qtumproject/qtum/wiki/How-to-Stake-QTUM-using-a-Linux-Virtual-Private-Server-(VPS);

Note that the block reward is not guaranteed even if you have some QTUM that is staking, the reward time is only an expected time, and it depends on how much QTUM you have, as well as the whole network weight for staking.
