### ISSUE TITLE
taking

### ISSUE THREAD

**Issue by greggdourgarian** [qtumproject/qtum#439]
What's up with staking problems?  There is a whole [thread](https://www.reddit.com/r/Qtum/comments/7h54jl/no_staking_reward_since_27th_nov/) of ppl complaining about it on reddit since several days ago w no dev response as far as i can tell.  Getting the same issue myself.   Met up with a qtum rep in Columbia who told me it was a version issue even though i had been staking successfully before.

**Comment by stephenxxl** [comment]
please refer to this issue #438
