### ISSUE TITLE
Could you build a qtum binary with musl?

### ISSUE THREAD

**Issue by montvid** [qtumproject/qtum#441]
Unfortunately I have an Alpine Linux (Postmarketos) running phone  that does not use/have glibc so I can't use the ARM 32bit binaries. Could you provide qtum ARM binaries compiled with musl too? Thanks.

**Comment by Earlz** [comment]
We have no plans of this in the near future, but welcome contributors who would like to undertake this project. Our build system (gitian) makes using a different libc a huge ordeal.
