### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hqxluoyang** [qtumproject/qtum#443]
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentserver.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::protobuf::Arena::CreateInternal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(bool)':
/usr/include/google/protobuf/arena.h:640: undefined reference to `google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/include/google/protobuf/arena.h:642: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentserver.o): In function `google::protobuf::internal::GetEmptyStringAlreadyInited[abi:cxx11]()':
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
collect2: error: ld returned 1 exit status
Makefile:4993: recipe for target 'qt/qtum-qt' failed
make[2]: *** [qt/qtum-qt] Error 1
make[2]: Leaving directory '/home/hqx/qtum/qtum/src'
Makefile:13422: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hqx/qtum/qtum/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by hhmingw** [comment]
qt编译相关出现问题了，看相关库有没有安装好？参考：
apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
