### ISSUE TITLE
编译错误求大神解决

### ISSUE THREAD

**Issue by hqxluoyang** [qtumproject/qtum#444]
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o):(.data.rel.ro._ZTVN8payments14PaymentRequestE[_ZTVN8payments14PaymentRequestE]+0xb0): undefined reference to `google::protobuf::Message::SpaceUsed() const'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o):(.data.rel.ro._ZTVN8payments16X509CertificatesE[_ZTVN8payments16X509CertificatesE]+0xb0): undefined reference to `google::protobuf::Message::SpaceUsed() const'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o):(.data.rel.ro._ZTVN8payments7PaymentE[_ZTVN8payments7PaymentE]+0xb0): undefined reference to `google::protobuf::Message::SpaceUsed() const'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o):(.data.rel.ro._ZTVN8payments10PaymentACKE[_ZTVN8payments10PaymentACKE]+0xb0): more undefined references to `google::protobuf::Message::SpaceUsed() const' follow
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequestplus.o): In function `google::protobuf::internal::GetEmptyStringAlreadyInited[abi:cxx11]()':
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequestplus.o):/usr/include/google/protobuf/generated_message_util.h:86: more undefined references to `google::protobuf::internal::empty_string_[abi:cxx11]' follow
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentserver.o): In function `payments::Output* google::protobuf::Arena::CreateInternal<payments::Output>(bool)':
/usr/include/google/protobuf/arena.h:640: undefined reference to `google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/include/google/protobuf/arena.h:642: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentserver.o): In function `google::protobuf::internal::GetEmptyStringAlreadyInited[abi:cxx11]()':
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentserver.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::protobuf::Arena::CreateInternal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(bool)':
/usr/include/google/protobuf/arena.h:640: undefined reference to `google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/include/google/protobuf/arena.h:642: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentserver.o): In function `google::protobuf::internal::GetEmptyStringAlreadyInited[abi:cxx11]()':
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
/usr/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
collect2: error: ld returned 1 exit status
Makefile:4993: recipe for target 'qt/qtum-qt' failed
make[2]: *** [qt/qtum-qt] Error 1
make[2]: Leaving directory '/home/hqx/qtum/qtum/src'
Makefile:13422: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/hqx/qtum/qtum/src'
Makefile:693: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by hhmingw** [comment]
该问题和qt编译依赖库有关，先保证预先安装好，可以参考：
apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
