### ISSUE TITLE
Issue adding a QRC20 token to Qtum wallet

### ISSUE THREAD

**Issue by jfuentep** [qtumproject/qtum#446]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
If you add the contract adress provided for https://qtumexplorer.io/contracts , is diferent at the contract adress that I got displayed in a transfer, and as such, make imposible to see the number of that QRC20 token that you have in your designed adress.

### Can you reliably reproduce the issue?
For example the adress provided for QBT in https://qtumexplorer.io/contracts  is  fbb3be981b61eee7f4c7cefcf02c97056323117c , as we can see.

With that address you can add the QBT token without problem  but the contract adress that I got in the transaction is diferent, it is QMUDYjQpjkxZjjfEdKznqsim7VMS5LZzqp  as we can see here:

https://explorer.qtum.org/token/QMUDYjQpjkxZjjfEdKznqsim7VMS5LZzqp/transfers?a=QR7sJZnuugNQE3gg1iJMDYoMxCxkP8X6db

And with that last adress we can not add the QBT token.

So if we add QBT with the first adress, I can not see the QBT trasferred to my Core wallet ( I have used at the time of adding the QRC20 token the adress used for the transaction), and I am not able to send them using the wallet, as you can see in the scans

![image](https://user-images.githubusercontent.com/33816457/34137376-ef08d55e-e46a-11e7-90d4-fa11429eb54c.png)

![image](https://user-images.githubusercontent.com/33816457/34137413-235b03ea-e46b-11e7-837d-248981c5d13f.png)

### What version of Qtum are you using?
Qtum Core versión v0.14.11.0-5be981c-dirty (64-bit)

**Comment by jfuentep** [comment]
Looks like the apropiate adress for QBT is 09800417b097c61b9fd26b3ddde4238304a110d5 , but I think than for easier use , there must be a complete index, or that you can add the new token also with token symbol

**Comment by icodeface** [comment]
qtumexplorer.io is not the official explorer, and you'd better not trust it too much.
you can got token contract addresses here https://dapps.qtum.org/
