### ISSUE TITLE
Error: Incorrect or no genesis block found. Wrong datadir for network?

### ISSUE THREAD

**Issue by BioCryptTechnologies** [qtumproject/qtum#450]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
Error: Incorrect or no genesis block found. Wrong datadir for network?

#### If so, please list the steps to reproduce below:
1.cloning the github
2.make install
3.qtumd

### Expected behaviour
qtum node should be up and running

### Actual behaviour
program doesn't start as it tells me incorrect or no genesis block

### What version of Qtum are you using?
Qtum Core Daemon version v0.14.12.0-6cd1c7d-dirty

### Machine specs:
- OS:  4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hhmingw** [comment]
Could you provide the ~/.qtum/debug.log file?
