### ISSUE TITLE
 g++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by mbalance** [qtumproject/qtum#452]
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:9622: recipe for target 'wallet/libbitcoin_wallet_a-rpcwallet.o' failed
make[2]: *** [wallet/libbitcoin_wallet_a-rpcwallet.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/wallets/qtum/src'
Makefile:13422: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wallets/qtum/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by mbalance** [comment]
Can't build any qtum wallet. After wasting my time for days now trying to build first the electrum and now the full wallet without any success.

Ubuntu 16.04 LTS

I've built 10+ wallet from various project and never had such a bad experience...

**Comment by mbalance** [comment]
These are the instructions i followed:

`This is a quick start script for compiling Qtum on  Ubuntu


sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils git cmake libboost-all-dev
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev

# If you want to build the Qt GUI:
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler

git clone https://github.com/qtumproject/qtum --recursive
cd qtum

# Note autogen will prompt to install some more dependencies if needed
./autogen.sh
./configure 
make -j2`

**Comment by Bushstar** [comment]
At a guess you ran out of RAM, please add a couple of GB swap and try again.

**Comment by Earlz** [comment]
Make sure you have enough RAM. At least 1.5G of RAM and/or swap is required per compiler thread.
