### ISSUE TITLE
Please explain "Have a transaction with more than 500 confirmations on the blockchain"

### ISSUE THREAD

**Issue by blackoutworm** [qtumproject/qtum#454]
Hi.
I want to stake QTUM, but not sure what you mean by "Have a transaction with more than 500 confirmations on the blockchain".
Please explain this one.

**Comment by Bushstar** [comment]
A transaction has to have 500 confirmations before it can be used to generate PoS blocks, after 500 confirms it is considered mature and will be used in staking.

https://medium.com/@jb395official/qtum-proof-of-stake-mining-439d2b82802d

**Comment by blackoutworm** [comment]
And what does 500 conformations mean?

**Comment by Bushstar** [comment]
That there needs to be 500 more blocks created since your transaction was added to a block, each new block is seen as another confirmation that your transaction will persist.

https://en.bitcoin.it/wiki/Confirmation
