### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by munakaya** [qtumproject/qtum#456]
I tried to install qtum on ubuntu.
I did what exactly same as guide but it gives following errors.
Can I get some tips to fix this?

qt/bitcoin.cpp: In member function ‘void BitcoinApplication::restoreWallet()’:
qt/bitcoin.cpp:552:35: error: invalid user-defined conversion from ‘char’ to ‘const QString&’ [-fpermissive]
         commandLine = arg.join(' ');
                                   ^
In file included from /usr/include/qt4/QtCore/qobject.h:48:0,
                 from /usr/include/qt4/QtGui/qwidget.h:47,
                 from /usr/include/qt4/QtGui/qframe.h:45,
                 from /usr/include/qt4/QtGui/qlabel.h:45,
                 from /usr/include/qt4/QtGui/QLabel:1,
                 from qt/bitcoingui.h:14,
                 from qt/bitcoin.cpp:9:
/usr/include/qt4/QtCore/qstring.h:419:43: note: candidate is: QString::QString(const char*) <near match>
     inline QT_ASCII_CAST_WARN_CONSTRUCTOR QString(const char *ch) : d(fromAscii_helper(ch))
                                           ^~~~~~~
/usr/include/qt4/QtCore/qstring.h:419:43: note:   conversion of argument 1 would be ill-formed:
qt/bitcoin.cpp:552:35: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
         commandLine = arg.join(' ');
                                   ^
qt/bitcoin.cpp:552:35: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
In file included from /usr/include/qt4/QtCore/qobject.h:48:0,
                 from /usr/include/qt4/QtGui/qwidget.h:47,
                 from /usr/include/qt4/QtGui/qframe.h:45,
                 from /usr/include/qt4/QtGui/qlabel.h:45,
                 from /usr/include/qt4/QtGui/QLabel:1,
                 from qt/bitcoingui.h:14,
                 from qt/bitcoin.cpp:9:
/usr/include/qt4/QtCore/qstring.h:419:43: note:   initializing argument 1 of ‘QString::QString(const char*)’
     inline QT_ASCII_CAST_WARN_CONSTRUCTOR QString(const char *ch) : d(fromAscii_helper(ch))
                                           ^~~~~~~
In file included from /usr/include/qt4/QtGui/qcolor.h:47:0,
                 from /usr/include/qt4/QtGui/qpalette.h:46,
                 from /usr/include/qt4/QtGui/qwidget.h:50,
                 from /usr/include/qt4/QtGui/qframe.h:45,
                 from /usr/include/qt4/QtGui/qlabel.h:45,
                 from /usr/include/qt4/QtGui/QLabel:1,
                 from qt/bitcoingui.h:14,
                 from qt/bitcoin.cpp:9:
/usr/include/qt4/QtCore/qstringlist.h:162:16: note:   initializing argument 1 of ‘QString QStringList::join(const QString&) const’
 inline QString QStringList::join(const QString &sep) const
                ^~~~~~~~~~~
qt/bitcoin.cpp:562:39: error: ‘static void QThread::sleep(long unsigned int)’ is protected within this context
             QThread::currentThread()->sleep(2);
                                       ^~~~~
In file included from /usr/include/qt4/QtCore/QThread:1:0,
                 from qt/intro.h:10,
                 from qt/bitcoin.cpp:15:
/usr/include/qt4/QtCore/qthread.h:115:17: note: declared protected here
     static void sleep(unsigned long);
                 ^~~~~
qt/bitcoin.cpp:562:46: error: ‘static void QThread::sleep(long unsigned int)’ is protected within this context
             QThread::currentThread()->sleep(2);
                                              ^
In file included from /usr/include/qt4/QtCore/QThread:1:0,
                 from qt/intro.h:10,
                 from qt/bitcoin.cpp:15:
/usr/include/qt4/QtCore/qthread.h:115:17: note: declared protected here
     static void sleep(unsigned long);
                 ^~~~~
Makefile:12329: recipe for target 'qt/qt_qtum_qt-bitcoin.o' failed
make[2]: *** [qt/qt_qtum_qt-bitcoin.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/user/my_work/qtum/qtum/src'
Makefile:13546: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/my_work/qtum/qtum/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
user@user-PMBSB09A-Samsung-DeskTop:~/my_work/qtum$

**Comment by pandazwb** [comment]
Would you please update to qt5 and try to re-build?
