### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by Vietwnhat** [qtumproject/qtum#457]
The other day I sent Qtum from Ledger nanos to Qtum core wallet.

＜January 2, 2018 ＞
Qutm20/ Qtum0.00075,Custom fee(USD 0.04)
Qtum0.2/Qtum0.01,High fee(USD 0.59)

＜January 3, 2018＞
Qtum0.2/Qtum0.01,High fee(USD 0.59)
All are in an unapproved state.

https://explorer.qtum.org
　　　　↑　「There are no transactions involving this address.」This is displayed.

Where did my transaction go?

### Can you reliably reproduce the issue?

Currently Ledger nanos will result in a remittance error.
Qtum can not be sent anywhere

#### If so, please list the steps to reproduce below:
1.Get new Qtum address
2.Sent from Ledger nanos
3.Trouble occurs

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
It is the latest.
 
### Machine specs:
- OS:Windows10（64）
- CPU:core i5
- RAM:16GB
- Disk size:465GB

**Comment by Earlz** [comment]
We do not have any expertise in the Ledger wallet. Please contact Ledger support about problems
