### ISSUE TITLE
Installing update on a OSX MAC computer 

### ISSUE THREAD

**Issue by lolo33433** [qtumproject/qtum#462]
I need to install the latest update on my OSX mac computer.  I have the old Qtum wallet already installed with my coins in it.  Do I need to delete my old wallet (Qtum Core version v0.14.11.0-5be981c-dirty (64-bit)) first before adding the new update to my Applications folder?

Thanks.

**Comment by qtum-neil** [comment]
No need to delete anything, but it's recommended to make a backup using your working wallet before updating.

**Comment by lolo33433** [comment]
Thank you, that was easy!
