### ISSUE TITLE
mobile wallet - token sending

### ISSUE THREAD

**Issue by wtjeong** [qtumproject/qtum#465]
This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1.  In mobile qtum wallet, select send menu.
2. choose 'MED Token'. then send.
3. Only 21 token is sent, no matter how much was sent.

### Expected behaviour
Correct amount of token should be sent.

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by stephenxxl** [comment]
https://github.com/qtumproject/qtum-ios/issues/2
refer to this
