### ISSUE TITLE
QTUM core

### ISSUE THREAD

**Issue by jimy3535** [qtumproject/qtum#467]
No QTUM help in same class as shapeshift.io level of issue help.

This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1. Dont want to try again
2.
3.

### Expected behaviour
Stable wallet receive address that actually works

### Actual behaviour
QTUM core wallet displayed initial Rx address, MED tokens then sent from exchange to same address. Now initial Rx address is not shown in wallet. Different address is now shown. Tokens apparently lost to mystery address, Address is view able on QTUM explorer. HOW can the wallet generate an address that is not associated with that actual wallet?? 

QTUM explorer: No transactions logged for lost address, but my tokens do show up.

### What version of Qtum are you using?
v0.14.13.0-b4e73b7-dirty (64-bit)

### Machine specs:
- OS: win 7 
- CPU: i3-2310M
- RAM: 8G
- Disk size: 1T

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Earlz** [comment]
Make sure you're using the same wallet.dat as you were when you saw this initial address. Also, make sure that the "log events" option if checked in the preferences menu
