### ISSUE TITLE
Trojan:Win32/Tiggre!plock(qtum-0.14.13-win64-setup-unsigned.exe) detecting

### ISSUE THREAD

**Issue by zzoiraek** [qtumproject/qtum#468]
This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1. qtum-0.14.13-win64-setup-unsigned.exe download
2. microsoft defender found it
3. Trojan:Win32/Tiggre!plock

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by basementcloud** [comment]
Same thing happened to me just now.

**Comment by qtum-neil** [comment]
These are false positives, as explained previously.
