### ISSUE TITLE
Mobile Wallet token sending bug 

### ISSUE THREAD

**Issue by lloyd-jeon** [qtumproject/qtum#471]
This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1.  Click the token send button in your mobile wallet
2. 100 HLC Send
3. The actual number of HLCs received is very small.
 ex) 1 send -> 2 HLCs 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by qtum-neil** [comment]
Please post this in the mobile wallets repos:

https://github.com/qtumproject/qtum-android

https://github.com/qtumproject/qtum-ios

**Comment by lloyd-jeon** [comment]
@qtum-neil Thank you.
