### ISSUE TITLE
listtransactions如何区分正常的交易和找零的交易还有QRC20返还部分手续费的交易

### ISSUE THREAD

**Issue by lanmp** [qtumproject/qtum#472]
你好，rpc 方法里面的listtransactions 未过滤找零的交易，如何区分？
还有QRC20返回部分手续费的记录可以区分吗

**Comment by icodeface** [comment]
调用合约多支付的gas fee会以一笔挖矿收入的形式返还，而挖矿交易在区块中的位置是固定的index=1,可以以此来判断。
