### ISSUE TITLE
QRC token endless sync issue [Enable log events] win_x86_64 0.14.13.0 and previous versions.

### ISSUE THREAD

**Issue by Illasera** [qtumproject/qtum#476]
Binary : qtum-qt.exe Windows, x86_64 0.14.13.0

(Issue applies to the latest 3 stable versions of qtum core wallet)

Background : A mandatory step when dealing with QRC tokens is to go to qtum-core wallet and toggle ON the option "Enable log events", Doing so results in a restart of the QTUM core wallet and a reindexing/resync process.

Bug : When you enable log events, to accept QRC tokens , The more you progress with the sync process, the less responsive the software becomes to the point of stepping into a full halt reported by the window manager (The software is still creating / modifying state files on the hard drive like crazy, but it seems to be in an endless loop as far as i can tell without looking at the source code to see what its actually doing.

Can the problem be duplicated? check reddit, by almost every qtum core user in the world that enabled the option.

What have i tried : Nuking all the QTUM wallet files and a fresh installation with the latest stable version, No luck.

Hardware info i can supply is that the endless writing cycle lasted for 10 hours until manual termination
on one setup of 4 intel SSD's at raid 0 
and another setup of 2 WD hard drive at raid 0
And from what i can tell, the main overload/bottleneck was on the hard-drives.

The hardware specs are irrelevant, the sync process with log events is more stressing on the hard drive than HDD crystalmark banchmark tools, and it seems to be getting us nowhere when it comes to wallet sync progression...

This issue should be addressed ASAP , you guys are playing with investors money... QRC tokens as of this moment are pretty much uselsss to many users.

Not to mention : 
1.)The poor activity of the moderation team on the reddit site. (reddit.com/r/Qtum)
2.)The inability to register to qtum's forums website due to unknown API config error (forum.qtum.org)
3.)Having CloudFlare kicking in on every 3rd query on qtum blockexplorer (explorer.qtum.org).

I am getting a strong bit-connect vibe here (Not implying a scam but a very faulty product), Maybe unintentional but i am worried about my investment...
I would like to know the status of the log-events issue before going public with this issue and warn people regarding QRC tokens.

Thanks in advance, sorry i can't make it more constructive.

**Comment by qtum-neil** [comment]
We are currently addressing this issue with Qt wallet, a temporary workaround is to sync with qtumd, then start Qt wallet.

**Comment by Illasera** [comment]
Thanks for the quick reply mate, But in the meantime, I would highly recommend, that the info will be on the main github page as a known issue, I think we can both agree that this is a big deal and people should know that its getting fixed and there is a way around it.

Not being transparent about it is a way to lose consumers trust.

**Comment by qtum-neil** [comment]
fixed here: https://github.com/qtumproject/qtum/releases/tag/mainnet-ignition-v0.14.14
