### ISSUE TITLE
Qbao IOS wallet issue?

### ISSUE THREAD

**Issue by lilbuck73** [qtumproject/qtum#477]
My Qbao IOS App wallet would not open yesterday so I had to delete it and reinstall and reverify the app. I opened app up and restored  my wallet from my mnemonic passphrase and 6 digit password. I had no tokens in my wallet. After I checked where I transferred tokens from, the MED token address was different than the MED token address on the Qbao wallet after restoring it? I also looked up the transaction on explorer.qtum.org and everything is there but for some reason the restore backup didn’t work and just gave me a different wallet? So how do I get my tokens back? I followed instructions exactly to make sure my wallet was backed up prior to any of this happening and now I don’t know to retrieve my tokens? Please help!
This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by qtum-neil** [comment]
Please contact QBao wallet team regarding this issue, this is the Qtum core repo.
