### ISSUE TITLE
QTUM-CLI - DEFAULT SHELL $VARS

### ISSUE THREAD

**Issue by cbowman596** [qtumproject/qtum#481]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue

Shells have default variables set, using BASH as an example: echo $$ will print the current PID of the BASH shell you run the command in.

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:

1.  Verify the syntax needed to create a wallet passphrase
```
qtum-cli help walletpassphrase
walletpassphrase "passphrase" timeout
```

2. Set the passphrase as a double quoted string

`qtum-cli encryptwallet "ohno$$bad"`
`wallet encrypted; Qtum server stopping, restart to run with encrypted wallet. The keypool has been flushed and a new HD seed was generated (if you are using HD). You need to make a new backup.`

3.  Start qtumd

`qtumd -daemon`
`Qtum server starting
`

4. Unlock encrypted wallet

`qtum-cli walletpassphrase "ohno$$bad" 99999`

5. Confirm wallet is unlocked

```
qtum-cli getwalletinfo
{
  "walletversion": 130000,
  "balance": 0.00000000,
  "stake": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1517379428,
  "keypoolsize": 101,
  "unlocked_until": 1517479461,
  "paytxfee": 0.00000000,
  "hdmasterkeyid": "89625149dfacebf1c2b9acaf93e94cb21e484f85"
}
```
6. Reboot machine at some point in the future

7. Unlock encrypted wallet

```
qtum-cli walletpassphrase "ohno$$bad" 99999
error code: -14
error message:
Error: The wallet passphrase entered was incorrect.
```
 8. Self observe instant transformation of two skin tones lighter as you grow pale

9. Realize $$ is a default shell variable, in which BASH holds the PID value of your BASH shell

```
echo "ohno$$bad"
ohno1219bad
```
 10. Realize after reboot the PID of BASH changed

```
echo "ohno$$bad"
ohno3288bad
```

### Expected behaviour
In the case above it was expected that passphrase would = ohno$$bad as set

### Actual behaviour
Passphrase is actually dynamic based on the current PID of BASH qtum-cli is run in due to $$ being a default variable in BASH.

### What version of Qtum are you using?
Qtum Core RPC client version v0.14.13.0-b4e73b7-dirty

### Machine specs:
- OS: Linux 024c31c9b020 4.9.69-rancher #1 SMP Fri Dec 15 01:57:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (qtumd and qtum-cli inside a Docker container)
- CPU: x86_64
- RAM: 8G
- Disk size: 128G

### Any extra information that might be useful in the debugging process.

Only the obvious, that all default vars for various shells could cause unpredictable results when setting a wallet passphrase

**Comment by xuanyan0x7c7** [comment]
Arguments passed to qtum-cli is already transformed by BASH, you should escape your inputs in the console.

**Comment by cbowman596** [comment]
I agree the inputs should be escaped by the user, but following the syntax provided by qtum-cli help shows double quotes which will not escape most special characters
