### ISSUE TITLE
qtum-cli sendfrom invalid

### ISSUE THREAD

**Issue by jerardq** [qtumproject/qtum#486]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue

./qtum-cli setaccount <myaddress> my_account
./qtum-cli sendfrom my_account <other_address> 0.01

I get txid in stdout

I check this txid in blockchain browser, I find that the from address is not <myaddress>. 

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by ATJohnson** [comment]
This is not a technical issue, this is user error. 
How about ` qtum-cli setaccount "ACCOUNT_ADDRESS" "ACCOUNT_NAME"`
You can see this in the help documents. `qtum-cli help setaccount`

**Comment by jerardq** [comment]
@ATJohnson  Of course I do that step first and make sure there is only one address in my account. Buy it doesn't work and also I watch all through the ` qtum-cli help ` command, still don't know how to solve this.

**Comment by jerardq** [comment]
@ATJohnson Thanks for your help. My wallet has many addresses. The ` from address ` always change each time I send coin to other.  That's make no sense

**Comment by ATJohnson** [comment]
Yes, all wallets have many addresses, that's why you set an address to an account.
setaccount "QXfDR7ovf5rPTTJEm97ELwcMmx65N6aaYB" "XYZ" <- This sets the address to account XYZ. 

If you don't set an address to an account and just send coins. Yes, it will send from any address is your wallet. 

Anyway, this is not a technical issue and this should be closed. 
I showed a working example of the issue you posted.

**Comment by jerardq** [comment]
@ATJohnson 

[bin]#./qtum-cli -conf=/qdata/bin/qtum_curr/bin/qtum.conf setaccount Qddgaw1UAz6Nk51HTRHwWsxckN6Zf9myTB testsendaccount
[bin]#
[bin]#./qtum-cli -conf=/qdata/bin/qtum_curr/bin/qtum.conf sendfrom testsendaccount Qf86H5JH29YTN34oxiSkCM5L7dY4BCRejv 0.05
d3ceb0dd83a4f78629492340f1c0673095b0f642d431eb4f5996bd0b9f4ed90d

[bin]#./qtum-cli -conf=/qdata/bin/qtum_curr/bin/qtum.conf gettransaction d3ceb0dd83a4f78629492340f1c0673095b0f642d431eb4f5996bd0b9f4ed90d
{
  "amount": 0.00000000,
  "fee": -0.00090923,
  "confirmations": 0,
  "trusted": true,
  "txid": "d3ceb0dd83a4f78629492340f1c0673095b0f642d431eb4f5996bd0b9f4ed90d",
  "walletconflicts": [
  ],
  "time": 1518138407,
  "timereceived": 1518138407,
  "bip125-replaceable": "no",
  "details": [
    {
      "account": "testsendaccount",
      "address": "Qf86H5JH29YTN34oxiSkCM5L7dY4BCRejv",
      "category": "send",
      "amount": -0.05000000,
      "label": "other_account",
      "vout": 0,
      "fee": -0.00090923,
      "abandoned": false
    },
    {
      "account": "other_account",
      "address": "Qf86H5JH29YTN34oxiSkCM5L7dY4BCRejv",
      "category": "receive",
      "amount": 0.05000000,
      "label": "other_account",
      "vout": 0
    }
  ],
  "hex": "0200000001affb91b5e7d750d1408f2d6f3a82feb26ed658def4f8a6b39fd07a6e3f7be4a1000000006b483045022100ea8c2f88bf6182fea5b2384699e023fc41a8f64f01690acaed84b3035d45c116022038fb13e3eda697437aba984f6bf561b1782c625a3922ecbdbf4c4d5bfbd5926b0121028d1ddf7a075b9735879936270edbc2e98c619dc318a613f1fe360fc519f29562feffffff02404b4c00000000001976a914cb23e467dc276585dc16ace828399ca76e57469088ac54db4100000000001976a9149b4bafcbda646d5b250eff6d1e725842d102adbe88acc57a0100"
}
[bin]#

**Comment by Earlz** [comment]
It is STRONGLY recommended to not use any of the account functionality in Qtum Core's RPC interface and to instead use external methods of separating coins within your wallet (ie, external database, etc). The account functionality is old, buggy, and in the next major release will be removed entirely.
