### ISSUE TITLE
QTUM core wallet takes tremendous fee to send BOT QRC 

### ISSUE THREAD

**Issue by Illasera** [qtumproject/qtum#496]
### Describe the issue
Trying to send BOT as a test from one wallet to another ended up (Almost) costing me 
10 QTUM in fee (Currently $220), Is this right? (Default gas Limit : 250000,  Gas Price : 0.00000040)

First of all, is there a way to get more information when we are about send a token
to how much QTUM is going to leave the wallet?

Another issue is when you don't have enough QTUM to send a token, It does say that :
"You need to have QTUM on address X", Well, that's not very informative, How much QTUM/subunit of QTUM do you need? you guys should supply that much.

I can not ask anyone else to replicate the issue , Because NOBODY in their right mind will throw away 10 QTUM.

### Expected behaviour
I expected to send the amount of BOT token i wrote down + the actual amount of QTUM required in GAS to compute the transaction, Even if that was the case, and i would get a refund for my gas (But 10 QTUM to begin with to send BOT?) But let's say that's the case and everything worked just fine, You guys need to supply information on how much QTUM you are going to spend, Obviously you can tell since the wallet reduces that amount before it broadcasts the transaction to the pools.

### Actual behaviour
End up paying x1000000 more.

### Screenshots.
Was too busy to trying revert the transaction than taking screenshots.

### What can you guys do?
Supply more info, Make the wallet more verbose and user friendly, a shining UI is not enough (Although the theme is too dark and most buttons look grey'd disabled even though they are not)

### What version of Qtum are you using?
Qtum Core version v0.14.14.0-100334a-dirty (64-bit)

**Comment by qtum-neil** [comment]
The default gas set in the wallet is 250000*0.0000004=0.1 QTUM (Not 10 QTUM, I don't know how you got that number). The actual cost is around 0.022 for a simple token transfer, the unused gas will be refunded to your address.
For simple transfers you can about 55000 for the gas limit.
