### ISSUE TITLE
qtumd keeps crashing on a Raspberry Pi 3

### ISSUE THREAD

**Issue by beamzer** [qtumproject/qtum#503]
### Describe the issue
Installed qtum as per
https://github.com/qtumproject/qtum/wiki/Installing-Qtum-on-Raspberry-Pi
on a Raspberry Pi 3
but after startup it never manages to retreive all the blocks

Feb 12 23:08:03 osmc systemd[1]: Starting Qtum daemon service...
Feb 12 23:08:03 osmc systemd[1]: Started Qtum daemon service.
Feb 12 23:14:54 osmc systemd[1]: qtumd.service: Main process exited, code=killed, status=11/SEGV
Feb 12 23:14:54 osmc systemd[1]: qtumd.service: Unit entered failed state.
Feb 12 23:14:54 osmc systemd[1]: qtumd.service: Failed with result 'signal'.
Feb 12 23:14:55 osmc systemd[1]: qtumd.service: Service hold-off time over, scheduling restart.
Feb 12 23:14:55 osmc systemd[1]: Stopped Qtum daemon service.
Feb 12 23:14:55 osmc systemd[1]: Starting Qtum daemon service...
Feb 12 23:14:55 osmc systemd[1]: Started Qtum daemon service.
Feb 12 23:23:23 osmc systemd[1]: qtumd.service: Main process exited, code=killed, status=11/SEGV
Feb 12 23:23:23 osmc systemd[1]: qtumd.service: Unit entered failed state.
Feb 12 23:23:23 osmc systemd[1]: qtumd.service: Failed with result 'signal'.
Feb 12 23:23:24 osmc systemd[1]: qtumd.service: Service hold-off time over, scheduling restart.
Feb 12 23:23:24 osmc systemd[1]: Stopped Qtum daemon service.
Feb 12 23:23:24 osmc systemd[1]: Starting Qtum daemon service...
Feb 12 23:23:24 osmc systemd[1]: Started Qtum daemon service.
Feb 12 23:29:15 osmc systemd[1]: qtumd.service: Main process exited, code=killed, status=11/SEGV
Feb 12 23:29:15 osmc systemd[1]: qtumd.service: Unit entered failed state.
Feb 12 23:29:15 osmc systemd[1]: qtumd.service: Failed with result 'signal'.
Feb 12 23:29:16 osmc systemd[1]: qtumd.service: Service hold-off time over, scheduling restart.
Feb 12 23:29:16 osmc systemd[1]: Stopped Qtum daemon service.
Feb 12 23:29:16 osmc systemd[1]: Starting Qtum daemon service...
Feb 12 23:29:17 osmc systemd[1]: Started Qtum daemon service.

I expected the daemon to continue with fetching blocks from the point where it crashed
but it seems to start over again, so it never reaches full duplication

root@~# qtumd -version
Qtum Core Daemon version v0.14.14.0-100334a-dirty
Copyright (C) 2017 The Qtum Core developers

Please contribute if you find Qtum Core useful. Visit <https://qtum.org> for
further information about the software.
The source code is available from <https://github.com/qtumproject/qtum>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
Eric Young and UPnP software written by Thomas Bernard.

**Comment by Earlz** [comment]
Please check your debug.log for any additional information and ensure that enough memory is free on the system. As is though, we have no way of diagnosing this issue without more info

**Comment by Brownie79** [comment]
Check the disk space usage on the RasPi, mine crashes due to out of disk space errors.
