### ISSUE TITLE
Setting gasLimit too high causes transaction to not be accepted by mempool/miners

### ISSUE THREAD

**Issue by dwalintukan** [qtumproject/qtum#504]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
We were testing our Airdropper contract on the mainnet: 
```
contract Airdropper is Ownable {
    function Airdropper() Ownable(msg.sender) public {
    }

    function multisend(address _tokenAddr, address[] _dests, uint256[] _values)
        onlyOwner
        public
        returns (uint256 _numTxs) 
    {
        uint256 i = 0;
        while (i < _dests.length) {
           ERC20(_tokenAddr).transfer(_dests[i], _values[i]);
           i += 1;
        }
        return(i);
    }
}
```

We are using a python script to construct the `datahex` for the transaction using `eth_abi.encode_abi()`. The data of addresses are in a CSV file.

Here are the following tests/outcomes:
1. batch of 500 addresses/values with a 40M gasLimit - transaction not in mempool and no transaction receipt. abandoned.
2. batch of 10 with 40M gasLimit - transaction not in mempool and no transaction receipt. abandoned. **(this should be accepted, only 10 transfers() with 40M gas)**
3. batch of 200 with 20M gasLimit - accepted in mempool and transaction receipt returned with failure due to hitting gas limit.
4. batch of 100 with 30M gasLimit - transaction not in mempool and no transaction receipt. abandoned
5. batch of 100 with 20M gasLimit - transaction succeeds. 2992538 gasUsed

#### If so, please list the steps to reproduce below:
1. deploy QRC token on mainnet
2. clone repo: https://github.com/bodhiproject/airdropper
3. construct transaction datahex with 100 addresses and values using eth_abi
4. set `gasLimit: 30000000` & `gasPrice: 0.0000004`
5. execute transaction

### Expected behaviour
The transaction gets accepted in mempool/miners with a 30M+ gas limit. Something about setting the gasLimit too high causes a transaction to sit in the queue and not get accepted by the mempool/miners.

### Actual behaviour
Setting the gas limit too high causes the transaction to sit in the queue waiting to be included in the mempool.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
qtum-0.14.14 mac

### Machine specs:
- OS: Mac OSX
- CPU:
- RAM: 16GB
- Disk size:

### Any extra information that might be useful in the debugging process.
This tx was a batch of 50 with 40M gasLimit. Abandoned txid: `75293a9b45aba136a2f23464526fb52b57cb21c7f437d1a953d51608b64a388e`
```
2018-02-14 08:22:49 CWalletTx::GetAmounts: Unknown transaction type found, txid 75293a9b45aba136a2f23464526fb52b57cb21c7f437d1a953d51608b64a388e
2018-02-14 08:27:35 Address : 4060e21ac01b5c5d2a3f01cecd7cbf820f50be95
2018-02-14 08:27:35 Address : 49665919e437a4bedb92faa45ed33ebb5a33ee63
2018-02-14 08:27:35 Address : 49665919e437a4bedb92faa45ed33ebb5a33ee63
2018-02-14 08:27:35 Address : 49665919e437a4bedb92faa45ed33ebb5a33ee63
2018-02-14 08:27:35 Address : 49665919e437a4bedb92faa45ed33ebb5a33ee63
2018-02-14 08:27:35 Address : 49665919e437a4bedb92faa45ed33ebb5a33ee63
```

**Comment by Earlz** [comment]
You are doing this testing on testnet, correct? I highly recommend giving yourself plenty of room before hitting the block gas limit. Individual stakers can set their own per-tx and per-block gas limits. I believe there are some mempool gas limits as well to prevent potential attacks. Also, if you do try to use the max, like 40M gas, and you do get it in front of a staker, if the staker receives another gas using transaction 1st, your transaction won't fit into the block. 

I would be hesitant about using anything more than 20M gas, and would prefer to use less. Also, there is a limit on the number of transfers you can do per transaction in Qtum. I believe that limit is around 400. If you exceed this limit, it will be treated like an out of gas condition.

**Comment by dwalintukan** [comment]
@Earlz Sorry I forgot about this issue.

Was testing this on the testnet. Makes sense about not being accepted in the block if you set the 40M gas limit.

My real concern is between these two tests:
3. batch of 200 with 20M gasLimit - accepted in mempool and transaction receipt returned with failure due to hitting gas limit.
5. batch of 100 with 20M gasLimit - transaction succeeds. 2992538 gasUsed

Why was did doubling the batch size hit the gas limit? From a successful 100 batch tx that cost `2992538 gas`, just under 3M gas. When doubling the batch, it caused it to use more than 20M gas.

**Comment by Earlz** [comment]
You would need to use a gas profiling tool to figure out why that is, and what the actual gas used would be. I'd recommend using regtest for this so that you can control the blockchain completely
