### ISSUE TITLE
"Change" transaction displaying not correct in MacOS core wallet

### ISSUE THREAD

**Issue by tonymorony** [qtumproject/qtum#507]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue

I used v0.14.14.0-100334a-dirty QTUM Core MacOS wallet.

I've sent a test 0.006 QTUM test transaction from my wallet (address QfNF9JoV82ncGWTe9zMnorcBsf4QBUVCfV) back to my wallet (address QfNF9JoV82ncGWTe9zMnorcBsf4QBUVCfV).  I wanted to test behavior in such situations. 
0.006 QTUM as expected was moved back to my address QfNF9JoV82ncGWTe9zMnorcBsf4QBUVCfV but all other balance moved to some random address which not belongs to my wallet (QMksgFmpf8cmoLeSE8rekW1nuTiEX11CqR). So now by some reason I don't have a control over my funds. Moreover I don't see this transaction in QTUM Linux wallet transactions list but can see in QTUM Explorer (https://explorer.qtum.org/tx/401c9dd17a70cd352dbc3288b630c92b6da8b20fb9f9a6afab864b929ec6824b).
When I'm trying to send any amount (even 0.001) via console wallet I receive an error Account has insufficient funds.
Also I don't see this transaction via listtransactions in Linux wallet but see on desktop.

#### If so, please list the steps to reproduce below:
1. Send not whole balance to myself to same address from which transaction doing

### Expected behaviour
Only gas spending.

### Actual behaviour
My balance minus transaction amount was sent to some random address.

### Screenshots.

![desktop](https://user-images.githubusercontent.com/24797699/36390376-e8fb7c14-15b3-11e8-8a1a-37ed78f9beea.png)
![linux](https://user-images.githubusercontent.com/24797699/36390379-eb3e206c-15b3-11e8-979f-ed26c0c0f80d.png)
![linux2](https://user-images.githubusercontent.com/24797699/36390382-ede5197e-15b3-11e8-9a31-1dc408b02442.png)

### What version of Qtum are you using?
v0.14.14.0-100334a-dirty QTUM Core MacOS wallet

### Machine specs:
- OS: Macbook AIR 2017, Google Haswell Ubuntu 14.04 VPS

**Comment by mikehash** [comment]
Hi there,

I've checked your transaction and the output is a "change" address transaction, that address belongs to you. 
Please take a look at https://en.bitcoin.it/wiki/Change
Also, you can double check this on your own wallet, if you're using the UI do the following:
Help->Debug->Console 
type "listaddressgroupings" without the ""
or, from the linux CLI wallet you have there, type:
qtum-cli listaddressgroupings
It'll show all your transactions and the balance on each one.

**Comment by tonymorony** [comment]
Thanks for a prompt reply, Mike!  I have a different outputs for same wallet in Linux and Mac (but blockchain is up to date on both). 

Also I've tried to restore my wallet.dat on other MacOS PC and there is the same wrong balance displaying. 

Only on VPS where I originally created this wallet displaying is correct.

 And I've tried to restore wallet from backup + reindex in desktop one
![image](https://user-images.githubusercontent.com/24797699/36393134-5c16fbdc-15bf-11e8-98e0-4034a8436112.png)
![image](https://user-images.githubusercontent.com/24797699/36393139-60d3c826-15bf-11e8-890d-847e26fa129c.png)
![2018-02-19 21 54 08](https://user-images.githubusercontent.com/24797699/36393150-7401498c-15bf-11e8-834a-141b57b54b48.png)
![image](https://user-images.githubusercontent.com/24797699/36393701-b2e8db18-15c1-11e8-92af-ceaaff296925.png)
![image](https://user-images.githubusercontent.com/24797699/36393706-b7c5310e-15c1-11e8-9b8b-bbe625945f3b.png)

**Comment by Earlz** [comment]
This does look like a bug. Where did you create the wallet.dat file originally? On your VPS or on Mac? Also, what version of Qtum are you using on your VPS and did you compile it yourself?

**Comment by tonymorony** [comment]
Hi Jordan,

1) Originally I've created wallet.dat on VPS.
2) Transaction was made from my colleague MacBook Air (not mine)
3) Transactions/balance indication was correct on my colleague laptop and
on VPS but not correct on my MacBook AIr laptop with same up to date
blockchain state.
4) After my colleague did restore/reindex from wallet.dat from my MacBook
he reached same wrong state with wrong indication of transactions/balance

I've compiled wallet via this instruction:
https://github.com/qtumproject/qtum/wiki/How-to-Stake-QTUM-using-a-Linux-Virtual-Private-Server-%28VPS%29
Version is: Qtum Core RPC client version v0.14.14.0-c572eac-dirty

I've found a solution of this problem for my case: re-downloaded wallet.dat
from VPS and did Restore/reindex and transactions and balance were restored
to correct values.
But please note that when I've tried to do re-index from wallet.dat on my
laptop (for same wallet actually) it didn't help.

So I guess wallet.dat on laptop was corrupted somehow with not correct
record about "change" transaction and then wallet didn't grab correct
information about transactions from blockchain because of the corruption.

Sorry for my poor English. Feel free to contact me in case of any
additional info needed. Go go QTUM :)

2018-02-23 1:53 GMT+03:00 Jordan Earls <notifications@github.com>:

**Comment by qtum-neil** [comment]
This looks like a corrupted wallet.dat issue, can you try starting qtumd with `-salvagewallet` on both machines (make sure to backup your wallet.dat first!)

**Comment by qtum-neil** [comment]
This looks like a corrupted wallet.dat issue, can you try starting qtumd with `-salvagewallet` on both machines (make sure to backup your wallet.dat first!)
