### ISSUE TITLE
Failed to compile version 0.14.15.01

### ISSUE THREAD

**Issue by vascoosx** [qtumproject/qtum#515]
### Describe the issue
When trying to `make -j2` I get the following error:
```
qtum/storageresults.cpp: In member function ‘bool StorageResults::readResult(const h256&, std::vector<TransactionReceiptInfo>&)’:
qtum/storageresults.cpp:121:130: error: ‘NoInformation’ is not a member of ‘dev::eth::TransactionException’
                                        state.itemCount() == 11 ? static_cast<dev::eth::TransactionException>(tris.excepted[j]) : dev::eth::TransactionException::NoInformation
```

#### If so, please list the steps to reproduce below:
1. `make clean`
2.  `./autogen.sh`
3. `./configure`
4. `make -j2`

### What version of Qtum are you using?
commit ID: dd9904a5f189064
version: 0.14.15.01

### Machine specs:
- OS: ubuntu 16.04

**Comment by xuanyan0x7c7** [comment]
#508 try `git submodule update`
