### ISSUE TITLE
Issue updating wallet from 14.14 to 14.15

### ISSUE THREAD

**Issue by Miro195** [qtumproject/qtum#517]
I installed the new version in the same folder but when I open the program it is still the previous version.

**Comment by Baiqiang** [comment]
Which platform are you using? Where're did you download it?

**Comment by Miro195** [comment]
I have windows 10 64 bit laptop. I downloaded from here qtum-0.14.15-win64-debug.zip

**Comment by Baiqiang** [comment]
@Miro195 
Have you tried the exe version? https://github.com/qtumproject/qtum/releases/download/mainnet-ignition-v0.14.15/qtum-0.14.15-win64-setup-unsigned.exe

**Comment by Miro195** [comment]
No. It seems that this version works, thanks. For future reference, which version types I should install for my windows?

**Comment by Baiqiang** [comment]
You can always use setup-unsigned.exe version.
