### ISSUE TITLE
make check Fail:2 

### ISSUE THREAD

**Issue by linkinbird** [qtumproject/qtum#518]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
make check failed and can't launch it

install in MacOS 10.11.6 
brew install OK
clone OK
./autogen.sh OK
./configure OK with 3 warnings:
```
configure: WARNING: libzmq version 4.x or greater not found, disabling
configure: WARNING: "xgettext is required to update qt translations"
configure: WARNING: jni headers/dependencies not found. jni support disabled
```
configure finished with:
```
Options used to compile and link:
  with wallet   = yes
  with gui / qt = yes
    qt version  = 5
    with qr     = yes
  with zmq      = no
  with test     = yes
  with bench    = yes
  with upnp     = auto
  debug enabled = no
  werror        = no

  target os     = darwin
  build os      = darwin

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DQTUM_BUILD -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -I/usr/local/opt/berkeley-db4/include -DMAC_OSX
  CXX           = g++ -std=c++11
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -Wno-unknown-pragmas
  LDFLAGS       =  -Wl,-headerpad_max_install_names -Wl,-dead_strip
```
make finish with several warnings but no error
```
...
  AR       qt/libbitcoinqt.a
  OBJCXXLD qt/qtum-qt
  CXXLD    qt/test/test_qtum-qt
Making all in doc/man
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all-am'.`
```
then make check will fail 
```
> make check
# FAIL:  2
See src/test-suite.log
```
and can't launch the command tool
```
> src/qtumd
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
Referenced from: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Expected in: flat namespace
```

#### If so, please list the steps to reproduce below:
1. make check
2. src/qtumd

### What version of Qtum are you using?
List the version number/commit ID
Merge pull request #513 from qtumproject/neil/bump-version-to-14-15-1
git just cloned totay

### Machine specs:
- OS: Mac OX EI Capitan
- CPU:1.8 GHz Intel Core i5
- RAM:4 GB 1600 MHz DDR3
- Disk size: 20GB available out of 256GB total

### Any extra information that might be useful in the debugging process.
[test-suite.log](https://github.com/qtumproject/qtum/files/1766597/test-suite.log)

**Comment by linkinbird** [comment]
some one said related to Ruby and  [xcode command line tools](https://stackoverflow.com/questions/39302619/missing-symbol-when-installing-ruby-2-3-0-on-os-x-10-11-6-by-rvm)
so i tried `sudo xcode-select --install`
but still don't work do i have to reconfigure and remake?

**Comment by xuanyan0x7c7** [comment]
@akahard2dj run `git submodule update` first

**Comment by akahard2dj** [comment]
@xuanyan0x7c7 Thanks! it works ;)
