### ISSUE TITLE
qttools5-dev error

### ISSUE THREAD

**Issue by munakaya** [qtumproject/qtum#524]
To run qtum gui, qttools5-dev is required. But when I run "sudo apt-get install qttools5-dev"
it throws an error. 

"The following packages will be upgraded:
  libdrm-amdgpu1 libdrm2 libegl1-mesa libgbm1 libgl1-mesa-dri libwayland-egl1-mesa
6 upgraded, 55 newly installed, 0 to remove and 27 not upgraded.
Need to get 70.5 kB/27.7 MB of archives.
After this operation, 123 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://kr.archive.ubuntu.com/ubuntu xenial/main i386 xtrans-dev all 1.3.5-1
  403  Forbidden
Err:1 http://kr.archive.ubuntu.com/ubuntu xenial/main i386 xtrans-dev all 1.3.5-1
  403  Forbidden
E: Failed to fetch http://kr.archive.ubuntu.com/ubuntu/pool/main/x/xtrans/xtrans-dev_1.3.5-1_all.deb  403  Forbidden

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
test@test-VirtualBox:~/qtum$ 

"

**Comment by mikehash** [comment]
for Ubuntu you can use this tutorial. We have an official repository which we always keep up-to-date and it's the safest and easiest option of running Qtum on ubuntu.
https://github.com/qtumproject/qtum/wiki/Setting-up-QTUM-Ubuntu,-Debian-and-Mint-repository
