### ISSUE TITLE
Error: Invalid value for gasPrice

### ISSUE THREAD

**Issue by dwalintukan** [qtumproject/qtum#528]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
Getting the error `Error: Invalid value for gasPrice` when calling qtumd `sendtocontract` via HTTP.

Just verified that this only happens when upgrade to 0.14.15. 

This seems to be related to using exponential format for the gasPrice. Before it would except `4e-7`, but in the latest version it does not.

#### If so, please list the steps to reproduce below:
1. Deploy contract
2. Run qtumd 0.14.14 and do a sendtocontract via HTTP with gasPrice set as 4e-7
3. Run qtumd 0.14.15 and do a sendtocontract via HTTP with gasPrice set as 4e-7

### Expected behaviour
gasPrice should behave as it did in previous versions and allow exponential format.

### Actual behaviour
gasPrice param exponential format not accepted.

### Screenshots.
SS of log output of our dapps backend API.
![image](https://user-images.githubusercontent.com/4350404/37755427-0c4c9342-2dd8-11e8-9ba7-4a79c9e444f5.png)

### What version of Qtum are you using?
List the version number/commit ID
0.14.15

**Comment by qtum-neil** [comment]
The current version does not accept exponential representation, please try to use the full representation, It was causing an issue with number conversion in some cases.

**Comment by dwalintukan** [comment]
I see. Ok we can change this.
