### ISSUE TITLE
./qtum-cli getbalance is not working in arm32 bit image

### ISSUE THREAD

**Issue by munakaya** [qtumproject/qtum#529]
./qtum-cli getbalance is not working in arm 32 bit image.
When you send your qtum from x86 wallet to arm 32bit wallet(rasberypi), can't find balance. it shows nothing but 0.

**Comment by mikehash** [comment]
did you check your transaction in the block explorer at https://qtum.info or https://explorer.qtum.org

**Comment by d3orn** [comment]
having the same issue on my raspberrypi checked tx and was confirmed

**Comment by d3orn** [comment]
you should try getinfo and there you are able to see blocks: "xxx" this will tell you up to what block your wallet is synced.
This is missing in most tutorials had to figure it out myself as well
