### ISSUE TITLE
How can I get some qtum coins for testnet ?

### ISSUE THREAD

**Issue by munakaya** [qtumproject/qtum#530]
Hi
I need some qtum coins in testnet for dev. Someone can share me some testnet qtums?
my qtum address is qaDALH3TJT1TMoj2qn3vdVNmdWdgGt3tCp

Or I want to know how to get some qtums in testnet.
thx.

**Comment by qtum-neil** [comment]
http://testnet-faucet.qtum.info/#!/

**Comment by ethdig** [comment]
http://testnet-faucet.qtum.info/#!/

not working   
           not working

**Comment by JB395** [comment]
Seems to be working for me. You can use the faucet to withdraw coins once a day. Try reloading your browser or hitting the check mark send button several times in a row.

**Comment by smk762** [comment]
![image](https://github.com/qtumproject/qtum/assets/35845239/e364ddd8-c859-4acd-bdbd-3d84c72b7958)
