### ISSUE TITLE
Wallet Network Weight Calculation Incorrect

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#534]
The wallet network weight calculation is reporting about half the correct network weight. The wallet network weight is only used to calculate the estimated time to a block reward, and because the network weight calculation is so low, this causes people staking to be frustrated when their actual block reward time is so much longer than the wallet estimated time to reward calculation.

## Target Spacing Denominator Fix
The wallet estimated weight calculation also suffers from a bad algorithm, using the 72-period moving average of block spacings in the denominator of the calculation, while the block spacing time is irrelevant to the network weight calculation (for PoS retargeting where the target is adjusted for every block). This causes unnecessary variation in the Network Weight.
A better algorithm would be to replace the nStakesTime moving average with a fixed value of 72 * TargetSpacing. This fixes the current situation where a long block causes the block spacing moving average to jump up and the network weight to be slammed down.
The code in blockchain.cpp line 127 is

    result = dStakeKernelsTriedAvg / nStakesTime;

Replace with

    result = dStakeKernelsTriedAvg / 9216;  // just take fixed value in denominator

This number 9216 should probably be referenced as something like 72 * consensusParams.nPowTargetSpacing: 

    result = dStakeKernelsTriedAvg / 72 * consensusParams.nPowTargetSpacing;  // just take fixed value in denominator

which value is initially set in chainparams.cpp line 90, but a C++ programmer should figure out how to make this reference.

## Scaling Factor Fix
The other fix is to correct the scaling factor, given in blockchain.cpp line 114:

    dStakeKernelsTriedAvg += GetDifficulty(pindexPrevStake) * 4294967296.0;

While this number appears to be significant as 2**32, it has no basis in reality (or any surviving comments) and is the main reason the network weight calculation is wrong. It is an arbitrary scaling factor for network weight.
For the days March 8 to March 21, 9 big wallets with a stable known total balance of 5.86 million won 1,276 of 8,346 blocks, so the correct average network weight for those 14 days is 5.86 / (1276 / 8346) = 38.33 million. Of course, there is some variation in this value, but its accuracy is one or two orders of magnitude better than a 72-period simple moving average.
Ripping the blockchain for difficulties for blocks 113,099 – 121,458 (March 8 – 21) plus blocks 113,027 – 113,098 to allow for the 72 period SMA run up to block 113,099, the average difficulty for these 8,431 blocks is 3842099. With the additional multiplier of 16 (STAKE_TIMESTAMP_MASK + 1), solving for the new scaling factor gives:
     (3842099 * 72 / 9216) * newScalingFactor * 16 = 38800000
newScalingFactor = 8080170908.0
With the added comment, blockchain.cpp line 114 should be: 

    // scaling factor 8080170908, based on 38330000 network weight March 21, 2018
    dStakeKernelsTriedAvg += GetDifficulty(pindexPrevStake) * 8080170908.0; 

Note the new scaling factor could be rounded down, it currently includes a reference to the Qtum Mainnet launch date of September 8, 2017.

**Comment by JB395** [comment]
Closing 5/31/2018. Network weight seems to be back in range around 20 million.

**Comment by Neologist** [comment]
Was this a self-healing problem or do you still think your solution should be implemented?

**Comment by JB395** [comment]
The network weight seems to be closer to reality now. This calculation will always be an estimate due to the nature of decentralized nodes. For what network weight is doing (only used to calculate the expected time to a block reward) it is probably good enough.
