### ISSUE TITLE
sudo make -j2

### ISSUE THREAD

**Issue by 13576972947** [qtumproject/qtum#538]
CXX      qt/qt_libbitcoinqt_a-qtumversionchecker.o
In file included from qt/qtumversionchecker.cpp:1:0:
qt/qtumversionchecker.h: In constructor ‘Version::Version(QString)’:
qt/qtumversionchecker.h:30:21: error: variable ‘QStringList parts’ has initializer but incomplete type
         QStringList parts = str.split(".");
                     ^
qt/qtumversionchecker.h:30:42: error: invalid use of incomplete type ‘class QStringList’
         QStringList parts = str.split(".");
                                          ^
In file included from /usr/include/qt5/QtCore/qobject.h:49:0,
                 from /usr/include/qt5/QtCore/QObject:1,
                 from qt/qtumversionchecker.h:4,
                 from qt/qtumversionchecker.cpp:1:
/usr/include/qt5/QtCore/qstring.h:81:7: error: forward declaration of ‘class QStringList’
 class QStringList;
       ^
make[2]: *** [qt/qt_libbitcoinqt_a-qtumversionchecker.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/ubuntu/erlei/qtum/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/erlei/qtum/src'
make: *** [all-recursive] Error 1

**Comment by hhmingw** [comment]
Can you provided your build env, such as os type, the version of gcc, qt...?

For ubuntu please follow build instruction:

sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils git cmake libboost-all-dev
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev

# If you want to build the Qt GUI:
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler qrencode

git clone https://github.com/qtumproject/qtum --recursive
cd qtum

# Note autogen will prompt to install some more dependencies if needed
./autogen.sh
./configure 
make -j2
