### ISSUE TITLE
Retrieving tokens from Nano Ledger using Qtum wallet 

### ISSUE THREAD

**Issue by Miro195** [qtumproject/qtum#540]
Hello,

I have sent my SPC tokens on Nano Ledger S Qtum wallet. I was not aware that this wallet does not support tokens build on Qtum. From the help desk I got information that it might be possible to retrieve the tokens using BIP39 tool and Qtum wallet. 

Is it true? If so, would you please help me how to do it? I think sooner or later there will be more people doing the same mistake.

Thank you very much. 

Miro

**Comment by JB395** [comment]
Use the Qtum Web wallet https://qtumeco.io/wallet - select Web - Visit Website, then Restore from Ledger. You can also reach the Web wallet by navigating from the qtum.org home page - select WALLET.

Add QRC20 tokens with the contract address for SPC from the Explorer tokens page https://explorer.qtum.org/tokens/search

This should give you full control of the SPC tokens.
