### ISSUE TITLE
why the minimal  protocol version is 70016

### ISSUE THREAD

**Issue by WalkerLiuFei** [qtumproject/qtum#541]
I saw the  p2p version message source code which  set the  limit lowest protocol to 70016,but why ?

**Comment by JB395** [comment]
Because the developers wanted to use some features that were only available for protocol version 70016 or later. There is one comment in the code that this version is related to bip-31 for ping/pong. You can see other features being added, with increasing minimum protocol versions, in the file version.h.

**Comment by WalkerLiuFei** [comment]
@JB395 but ping / pong  message is already supported in version 60001, and I don't see any comment about the protocol version 70016 support in file versioh.h 
`static const int PROTOCOL_VERSION = 70016;

//! initial proto version, to be increased after version/verack negotiation
static const int INIT_PROTO_VERSION = 209;

//! In this version, 'getheaders' was introduced.
static const int GETHEADERS_VERSION = 31800;

//! disconnect from peers older than this proto version
static const int MIN_PEER_PROTO_VERSION = 70016;

//! nTime field added to CAddress, starting with this version;
//! if possible, avoid requesting addresses nodes older than this
static const int CADDR_TIME_VERSION = 31402;

//! BIP 0031, pong message, is enabled for all versions AFTER this one
static const int BIP0031_VERSION = 60000;

//! "mempool" command, enhanced "getdata" behavior starts with this version
static const int MEMPOOL_GD_VERSION = 60002;

//! "filter*" commands are disabled without NODE_BLOOM after and including this version
static const int NO_BLOOM_VERSION = 70011;

//! "sendheaders" command and announcing blocks with headers starts with this version
static const int SENDHEADERS_VERSION = 70012;

//! "feefilter" tells peers to filter invs to you by fee starts with this version
static const int FEEFILTER_VERSION = 70013;

//! short-id-based block download starts with this version
static const int SHORT_IDS_BLOCKS_VERSION = 70014;

//! not banning for invalid compact blocks starts with this version
static const int INVALID_CB_NO_BAN_VERSION = 70015;`

**Comment by qtum-neil** [comment]
PROTOCOL_VERSION was bumped to 70016 along with MIN_PEER_PROTO_VERSION to kick out nodes from pre mainnet versions trying to connect to the mainnet network.
