### ISSUE TITLE
启动qtumd server 后，getinfo 查看信息 “testnet：true”

### ISSUE THREAD

**Issue by zhangjinyang** [qtumproject/qtum#542]
![image](https://user-images.githubusercontent.com/11783190/38729712-6504e7a8-3f46-11e8-83b5-cbff2354c757.png)
这里显示testnet为true。我是下载的最新的release 版本。那说明我现在启动起来的是测试网络吗？那么如何切换到正式网络呢？

**Comment by JB395** [comment]
This means you are connected to Testnet. Any core wallet can connect to Testnet with the appropriate startup parameters, or with no parameters, will startup on Mainnet. See {this blog](https://medium.com/@jb395official/testnet-and-qtum-mainnet-performance-january-1-8-e7af03a5d430) for more info on connecting to Testnet or Mainnet.

**Comment by zhangjinyang** [comment]
@JB395  Thank you for your answer.Ok,I have looked through your blog. The explaination is awesome.But I want to know how to run the server on "Mainnet"? I have not seen anything about how to switch from testnet to mainnet.Did I miss something important?

**Comment by JB395** [comment]
I think we chatted on Telegram. The default command line "qtumd" will start on Mainnet, "qtumd -testnet" will start on Testnet, but check the switches in your config file as well.
