### ISSUE TITLE
QR Code Reading Problems with Android Wallet App

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#543]
1. A community member using the Android mobile wallet (Android version: 8.0 Galaxy Note 8 Qtum wallet version 0.12(113)) reported problems reading the address QR code on the Upbit exchange. Here is a QR code from the Upbit exchange:

![upbit qr code](https://user-images.githubusercontent.com/29760787/38779857-4e5e5802-409c-11e8-85ff-2c869e331848.jpg)

Which gives this error “Invalid QR Code” on the Android wallet app:

![invalid qr code](https://user-images.githubusercontent.com/29760787/38779866-689592da-409c-11e8-8aaf-61f00b4600cd.jpg)

The Android wallet correctly reads the address QR code on the Explorer (explorer.qtum.org).

2. As a reference, the Qbao wallet also produces and error for the Upbit QR code, with the message “Please scan the correct QR code” and correctly reads the Explorer QR code and the QR image for qtum-qt – Receive – RECEIVE A PAYMENT.

3. Using a generic QR code scanner (https://itunes.apple.com/us/app/free-qr-code-reader-barcode-scanner-for-iphone/id903799541?mt=8) , for the Upbit image, the scanner reads the Q address only, for the Explorer image the scanner reads “qtum:QSyiND…?label=QTUM Mobile Wallet” where QSyiND… is the full Q address, and the scanner cannot read the QR image from qtum-qt.

**Comment by qtum-neil** [comment]
Please post this in the android app repo.
