### ISSUE TITLE
Execute multiple commands in RPC console of GUI

### ISSUE THREAD

**Issue by ksmin295** [qtumproject/qtum#544]
Hello, I'm using Qtum Core GUI in Windows 10 64bit.

I'm trying to execute multiple command in **RPC console** in **Debug window** for addnode command.

For example, 
addnode "123.456.789.012:3888 " add
addnode "111.222.333.444:3888 " add

But, Qtum Core GUI is shut down suddenly.

So, I'm thinking to use qtum-cli.exe to attach rpc console to GUI node.
Is there any way to attach it? or execute multiple commands in rpc console in GUI is also fine.

Thank you always.

**Comment by JB395** [comment]
I think you want to use the qtum.conf file (see attached), in the Qtum directory, which qtum-qt will load at startup. You will have to experiment with this – I haven’t tried it. Rename this file as "qtum.conf" and edit the addnode lines to remove the comment and put your IP address in.

[qtum.conf.txt](https://github.com/qtumproject/qtum/files/1918045/qtum.conf.txt)

**Comment by ksmin295** [comment]
Thank you! I will try it.

**Comment by ksmin295** [comment]
It works really well!
Thanks~
