### ISSUE TITLE
RPC gasPrice parsing is not longer JSON compliant

### ISSUE THREAD

**Issue by hayeah** [qtumproject/qtum#546]
Quite a lot of JS code (as well as my golang code that uses the JSON RPC) is now broken because of this backward incompatible change that modified how gasPrice is parsed:

https://github.com/qtumproject/qtum/commit/e774728ea8644f4ec52eb01604b28df94af119be#diff-df7d84ff2f53fcb2a0dc15a3a51e55ce

Can we support gasPrice specified as a JS number, which is more natural than going back and change gasPrice to strings in libraries.

**Comment by hayeah** [comment]
Is there a way to fix the problem a remain JSON number compliant?

Perhaps we can check that if the type is number, use JSON number from Univalue as is. If type is string, use ParseMoney.

**Comment by qtum-neil** [comment]
We'll look into that

**Comment by qtum-neil** [comment]
Fixed in https://github.com/qtumproject/qtum/commit/f5ddd5d741487e2d335fa2460cdf9dca45e46587
