### ISSUE TITLE
Upgrade EVM for better compatibility with ETH ecosystem

### ISSUE THREAD

**Issue by hayeah** [qtumproject/qtum#548]
The popular OpenZeppelin contracts can't run on QTUM's EVM. Two instructions are missing:

+ returndatasize
+ returndatacopy

There are also upcoming "revert with reason" instruction ([EIP 140](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md)) that would help a lot with debugging. Toolchains and Solidity will soon have support for this.

**Comment by mahuaibo** [comment]
I have the same problem.
1）returndatasize
2）returndatacopy
The contract does not work properly.

**Comment by hayeah** [comment]
Just to add more detail to this problem. `returndatasize` and `returndatacopy` are used when a contract calls another contract's method, and uses the return value.

```
contract A {
  B b;
  function callBar() returns(uint256) {
    return b.bar();
  }
}

contract B {
  function bar() returns(uint256) {
    return 2;
  }
}
```

**Comment by hayeah** [comment]
To follow up further on this issue, we can work around this problem by asking solc to emit code for homestead instead of byzantium:

```
solc --bin --asm --evm-version homestead Foo.sol
```

The generated code would avoid using returndatacopy and returndatasize

**Comment by dwalintukan** [comment]
👍 for upgrading the EVM. 

Just tried deploying my compiled contracts which was compiled with the newest `solc 0.4.24`, but it results in throwing a `BadInstruction` error.

It compiles and deploys fine on Remix though.

**Comment by Earlz** [comment]
An upgraded EVM is planned to be included in the x86 hard fork

**Comment by ethgamble** [comment]
use my fork of solar, add  --evm-version homestead  by default

go get -u github.com/ethgamble/solar/cli/solar

**Comment by paulofelipe84** [comment]
Hi, I just wanted to confirm if I get it right:

As of now, isn't there any way of calling a contract function from another contract in qtum?

**Comment by qtum-neil** [comment]
> Hi, I just wanted to confirm if I got it right:
> 
> As of now, isn't there any way of calling a contract function from another contract in qtum?

You can call other contract's functions in Qtum, make sure to compile both contracts with `--evm-version homestead`

**Comment by paulofelipe84** [comment]
Thanks! Is there a way of compiling for that version using Remix?

**Comment by paulofelipe84** [comment]
> Thanks! Is there a way of compiling for that version using Remix?

Just replying that question, using Remix's compiler version 0.4.21 will do it.

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/pull/736
