### ISSUE TITLE
"<address>.balance (uint256)" doesn't work in Qtum smart contract(solidity).

### ISSUE THREAD

**Issue by KimKyungup** [qtumproject/qtum#551]
"<address>.balance (uint256)" doesn't work in Qtum smart contract.
I made a smart contract which can check the owner or another address's balance.
But, It doens't work. 
With same smart contract, in ETH smart contract, it can check the balances.
Does Qtum smart contract have a plan to support that global variable in solidity?
Or, is there another way to resolve it?

http://solidity.readthedocs.io/en/v0.4.23/units-and-global-variables.html?highlight=address%20balance

**Comment by qtum-neil** [comment]
Qtum currently only supports <address>.balance for contract addresses.

The balance is returned in satoshis.

**Comment by KimKyungup** [comment]
Thanks. Neil.
I also understand that kind of situation because Qtum is new one with bitcoin + eth.
But, For newbie in Qtum, If there is a document for comparing with ETH Smart Contract, it will be helpful. 
If you know one, please share to us. :) Thanks.
