### ISSUE TITLE
What is difference between Mined TX and Recevied TX?

### ISSUE THREAD

**Issue by KimKyungup** [qtumproject/qtum#553]
Hello. :)
I am trying to categorize Mined TX in qtum-cli.
But I can't see the big difference between Mined TX and Recevied TX.

Both TXs have same like below.
"category": "receive"

Is there any easy way to know which is mined TX? :-)

Should I decode the hex? Could you let me know how to decode it?
I tried to decode by decoderawtransaction/decodescript. But. It is now easy for me.

Help me.

Here are my example of Mined TX and Received TX.

#####################Mined TX##########################################
{
  "amount": 2000.00000000,
  "confirmations": 7219,
  "blockhash": "6ba97e9cde0b7afa9515f91964c732aa3a145654d4a0a6b26deaa4dfdeb0ada7",
  "blockindex": 1,
  "blocktime": 1524019216,
  "txid": "aa7265969bdb095b5f033ef64b2df0e2092dd35ea73a52f6faeacf2199009ab3",
  "walletconflicts": [
  ],
  "time": 1524019202,
  "timereceived": 1524019202,
  "bip125-replaceable": "no",
  "details": [
    {
      "account": "",
      "address": "qejpDVJy3DpavfxEQ3GZKthCT3xQ9JZR6H",
      "category": "receive",
      "amount": 2000.00000000,
      "vout": 3
    }
  ],
  "hex": "0200000001ebcab3a37e2e09baae18cb059078fa6b61acaf727c29de46e79b7b4f401620ed060000006a4730440220385277138ee1ef67c8e309fc5aaa0c2eb5001b871b1ccfd049bb8e3b30d2c0ec0220339efcb0c7e6b0e2467c5fe79796afc12a80ff756812b7238c9466a3ee96bbb301210297b07babe9557eaa73612403d9f5938cfcb436343345c75a4854da42e73a2cdfffffffff0c00000000000000000000d0ed902e00000023210297b07babe9557eaa73612403d9f5938cfcb436343345c75a4854da42e73a2cdfac00d0ed902e00000023210297b07babe9557eaa73612403d9f5938cfcb436343345c75a4854da42e73a2cdfac00d0ed902e0000001976a914e853b8441f801edf7160989b8b99cb174fcc739488ac00d0ed902e0000001976a91477ff478a3809c17f68d66a2d01354a60f598a9a188ac00d0ed902e0000001976a914f4dc48431b8a9ae52df5450c5502ee900d80214488ac00d0ed902e0000001976a91477ff478a3809c17f68d66a2d01354a60f598a9a188ac00d0ed902e0000001976a91477ff478a3809c17f68d66a2d01354a60f598a9a188ac00d0ed902e0000001976a91477ff478a3809c17f68d66a2d01354a60f598a9a188ac00d0ed902e0000001976a91477ff478a3809c17f68d66a2d01354a60f598a9a188ac00d0ed902e0000001976a91477ff478a3809c17f68d66a2d01354a60f598a9a188ac00d0ed902e0000001976a91477ff478a3809c17f68d66a2d01354a60f598a9a188ac00000000"
}

###################Received TX ################################################

￼
{
  "amount": 50.00000000,
  "confirmations": 7247,
  "blockhash": "22a687eb4e5361dc0a84bc0450e1d58c7cacf9f4bff9582c46395445608e84e3",
  "blockindex": 3,
  "blocktime": 1524018768,
  "txid": "7eda9a994df384fe91ab79352ac038ce5d62e4b4450d8453fb0f8ff478e3ade1",
  "walletconflicts": [
  ],
  "time": 1524018753,
  "timereceived": 1524018753,
  "bip125-replaceable": "no",
  "details": [
    {
      "account": "",
      "address": "qej2EhPyS3SkixpzWdkasDH9xsiHkVCVra",
      "category": "receive",
      "amount": 50.00000000,
      "vout": 0
    }
  ],
  "hex": "02000000012c9ab8e8b008460106e7ee9e308ea5461bab8020644dada7ab7057462dafc5d50000000001c3ffffffff0100f2052a010000001976a914e82d569bcbd480116ff3974e8c873f18b3ed421488ac00000000"
}

**Comment by qtum-neil** [comment]
Indeed mined txs always have "blockindex": 1 as @JB395 mentionned.

**Comment by KimKyungup** [comment]
Wow. JB395 and Neil. 
Thanks for your kind answer.
I spent much time to know that.
You guys saved me.
