### ISSUE TITLE
Time zone isn't my OS date

### ISSUE THREAD

**Issue by deanrobin** [qtumproject/qtum#554]
HI , I run a qtum application on my centOS
`./qtumd -daemon -datadir=/mnt/data/log/qtum -server -rpcpassword=password -rpcport=8009 -rpcuser=user`
And I look log
`tail -f debug.log`
Log print
`2018-05-10 06:37:11 receive version message: /Satoshi:0.14.14/: version 70016, blocks=151016, us=47.52.229.70:53112, peer=300`
But My OS date time is 14:37 (I'm in China)

**Comment by JB395** [comment]
The debug.log uses UTC timestamps, so if you are UTC+6 (0637 hours to 1437 hours) that would be about tight. You can check the time synchronization with your wallet using the “getinfo” command. The “timeoffset” field will show the difference in seconds between your computer clock and Qtum network time. A good timeoffset is zero, or a few seconds.
