### ISSUE TITLE
Allow x86 contracts to hold tokens and to retrieve their own balance as well as external contract balances

### ISSUE THREAD

**Issue by Earlz** [qtumproject/qtum#564]
As a contract developer, I want for my contracts to be capable of holding tokens and checking the balance, so that my contracts can be used for financial transactions like escrow, etc. 

For this story, it should be possible to use OP_CALL transactions to send tokens to a contract. In this, the AAL should be working properly as well so that if a previous OP_CALL tx is owned by the contract, they should be condensed into a single UTXO the same way as this works for the EVM. As part of this, 3 new system calls should be introduced:

* GetBalance - Retrieves the balance (as a 64bit integer) of the current contract
* GetBalanceOfAddress - Retrieves the balance of an external contract. This takes a UniversalAddress and returns a 64bit integer. 
* GetCallValue - Retrieves how much value was sent to the contract as part of the current call. During OP_CREATE this should return 0. 

As part of this, also update libqtum so that these syscalls can be used easily.

**Comment by Earlz** [comment]
If storage is required to make this story work, make sure to look at #568. The planned database storage for the AAL UTXO data is `txid + vout_number + balance`

**Comment by hhmingw** [comment]
Add  storage of AAL data in deltaDB and Get* syscall.
