### ISSUE TITLE
Add syscall so that contract can get it's own address

### ISSUE THREAD

**Issue by Earlz** [qtumproject/qtum#565]
As a contract developer, I want to be able to write code so that a contract can retrieve it's own address so that I can tell other contracts how to refer to my contract. 

Right now in x86 it's not possible for a contract to figure out it's own address from within code. Add a system call that returns a UniversalAddress for their own address.

As part of this, also update libqtum so that this syscall can be used easily.

**Comment by hhmingw** [comment]
Added a syscall to this function in qtum-x86 and libqtum.
