### ISSUE TITLE
qtum-qt will exit exceptionally  if the default data directory is not exist in  X11 environment

### ISSUE THREAD

**Issue by johncao888** [qtumproject/qtum#579]
### Describe the issue
qtum-qt will exit exceptionally  if the default data directory is not exist in  X11 environment. 
### Can you reliably reproduce the issue?
yes,every time as the same condition.
#### If so, please list the steps to reproduce below:
1.Ssh login server.
2.Delete ~/.qtum , 
3.qtum/src/qt/qtum-qt -regtest
4.The issue is reproduced one more time. 

### Expected behaviour
![intro](https://user-images.githubusercontent.com/38059245/42076173-89341292-7ba6-11e8-8eda-3cfab4ae7426.png)

### Actual behaviour
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
qtum-qt: Fatal IO error 2 (No such file or directory) on X server localhost:12.0.
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

![issue](https://user-images.githubusercontent.com/38059245/42076297-2729f62e-7ba7-11e8-984d-d6f1979b3994.png)

### What version of Qtum are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
Qtum Core version v0.14.16.0-5a80ca6-dirty (64-bit)/5a80ca6ee9381a98a55efed429da1e64cf3e9af8
### Machine specs:
- OS:Ubuntu 16.04.4 LTS/xenial
- CPU:Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
- RAM:4G
- Disk size:200G
- Disk Type (HD/SDD):HDD

### Any extra information that might be useful in the debugging process.
bug can be fixed by below:
diff --git a/src/qt/intro.cpp b/src/qt/intro.cpp
index ea5e3d8..dea0e65 100644
--- a/src/qt/intro.cpp
+++ b/src/qt/intro.cpp
@@ -188,7 +188,7 @@ bool Intro::pickDataDirectory()
         /* If current default data directory does not exist, let the user choose one */
         Intro intro;
         intro.setDataDirectory(dataDir);
--        intro.setWindowIcon(QIcon(":icons/bitcoin"));
++        intro.setWindowIcon(QIcon(":icons/bitcoin.ico"));

**Comment by qtum-neil** [comment]
Cannot reproduce, will close, please reopen if you can still reproduce the issue with the latest release binaries
