### ISSUE TITLE
Remove RPi UI reference from readme

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#586]
In the readme.md file, please remove "Unofficial Raspberry Pi Web UI" since this is deprecated software that is no longer supported.

**Comment by JB395** [comment]
This is a dead link now, gives a 404 error.

**Comment by qtum-neil** [comment]
Fixed https://github.com/qtumproject/qtum/commit/73fe5999ed55c6cbfdf4ed646dfcaec2b8b52c93
