### ISSUE TITLE
Not able to get the balance of an address

### ISSUE THREAD

**Issue by usmananwar** [qtumproject/qtum#598]
Hi,
I am trying to use getreceivedbyaddress by using qtum-cli on testnet, but it always returns 0 balance for each address;
qtum-cli -conf="/home/ubuntu/applications/qtum/qtum.conf" getreceivedbyaddress "qaEnrNyKxqGegoTv5PYgx6h6W41jZ9ANJL" 0

Is there anything I am doing wrong?

### What version of Qtum are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

Qtum Core Daemon version mainnet-ignition-v0.15.2

**Comment by xuanyan0x7c7** [comment]
you need -testnet

**Comment by usmananwar** [comment]
It's because I was trying to get the balance of a non wallet account
