### ISSUE TITLE
HD wallet does not provide deterministic addresses

### ISSUE THREAD

**Issue by tushar00jain** [qtumproject/qtum#599]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
HD wallet does not provide deterministic addresses

#### If so, please list the steps to reproduce below:
1. start qtumd on docker
2. encrypt the wallet with mnemonic `qtum-cli encryptwallet`
3. run `qtum-cli getnewaddress`
4. repeat the process

### Expected behaviour
The output of `qtum-cli getnewaddress` should be the same everytime

### Actual behaviour
The output of `qtum-cli getnewaddress` is not the same

### What version of Qtum are you using?
0.15.3

**Comment by qtum-neil** [comment]
`getnewaddress` is supposed to give a new address each time it's called, it uses the next hdkeypath on each call.

**Comment by tushar00jain** [comment]
but the same hdkeypath have different addresses

**Comment by qtum-neil** [comment]
`encryptwallet` is not used to set wallet mnemonics or private keys, it's used to encrypt the actual wallet.dat file so it cannot be opened without a passphrase, so two different wallets will have different private keys even if they are encrypted with the same passphrase.

**Comment by xuanyan0x7c7** [comment]
That's impossible due to security
