### ISSUE TITLE
Duplicate transactions bug from bitcoin core

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#604]
Please check validate.cpp line 3999 for this bug from bitcoin core, where a malicious miner can put two duplicate transactions it a block, causing nearby peers to crash:

https://github.com/bitcoin/bitcoin/commit/b8f801964f59586508ea8da6cf3decd76bc0e571

**Comment by qtum-neil** [comment]
Thanks will check that!

**Comment by tjbaker** [comment]
There is a numbered CVE about this, you should be more explicit in your PR.

**Comment by qtum-neil** [comment]
Will do

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/816f61c883770f12c74759904c6a0e960a8ebbca
