### ISSUE TITLE
Help text does not correctly describe unlock for staking only

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#608]
Help text does not correctly describe how to unlock the wallet for staking only.

At rpcwallet.cpp line 2950 should say:
     `"walletpassphrase \"passphrase\" timeout stakingonly\n"`

Line 2952 should say:

`"This is needed prior to performing transactions related to private keys such as sending QTUM and staking\n"`

Line 2956 should say:

`"3. Staking only        (bool, optional, omitted=false, enabled=true) Unlock wallet for staking only.\n"`

Add example at line 2964:

```
Unlock the wallet for staking only, for a long time:
> qtum-cli walletpassphrase "my pass phrase" 99999999 true
```
Line 3015 should say

```
"walletpassphrase <passphrase> <timeout> <stakingonly>\n"
```

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/f9d9383b0be225799580f09fa210dd49018cba08
