### ISSUE TITLE
Command getnetworkhashps is Deprecated

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#614]
The command “getnetworkhashps” is a legacy bitcoin value, related to difficulty, which has no relevance for Qtum Proof of Stake. Qtum network hashes per second is actually the number of active nodes divided by 16 seconds, typically a three-digit value. This command is also meaningless for QtumX.

Please add at the top of the help text in mining.cpp line 95:
“DEPRECATED. Qtum network hashes per second is the total number of nodes divided by 16 seconds.”

![getnetworkhashps](https://user-images.githubusercontent.com/29760787/47605410-22816680-d9d4-11e8-996e-c9165a349ca8.jpg)

**Comment by qtum-neil** [comment]
This is not exactly deprecated, it's related to PoW mining, it might still be useful in some cases (ie regtest mode running in PoW).
Made the description a bit clearer here: https://github.com/qtumproject/qtum/commit/f9d9383b0be225799580f09fa210dd49018cba08
