### ISSUE TITLE
Error after running make command

### ISSUE THREAD

**Issue by Vishwas1** [qtumproject/qtum#615]
I am trying to build Qtum. I ran the make command after running ./autogen.sh and ./configure but first of all it took more than 30 mins to complete. And after 30mins it gave this error.
```
Makefile:10692: recipe for target 'qt/qt_libbitcoinqt_a-paymentrequestplus.o' failed
make[2]: *** [qt/qt_libbitcoinqt_a-paymentrequestplus.o] Error 1
make[2]: Leaving directory '/home/vishwasb/vab/projects/zagg/qtum-bitcore/src'
Makefile:13736: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vishwasb/vab/projects/zagg/qtum-bitcore/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
I am using Ubuntu 18.04 machine.

Any help would be highly appreciated. Thanks.

**Comment by qtum-neil** [comment]
The error shows you are compiling the bitcore branch, please create this issue under that branch: https://github.com/qtumproject/qtum-bitcore/issues

The main Qtum core branch is here: https://github.com/qtumproject/qtum
