### ISSUE TITLE
qtum-cli sendtomany uses wrong UTXO for input of transaction

### ISSUE THREAD

**Issue by BCsRock** [qtumproject/qtum#623]
I wanted to move QTUM between my accounts on my wallet. So I created a transaction which sends coins from Account A to account B and C.

In order to do so, I used command `./qtum-cli sendmany`.
In there, I specified the account from which to send: `./qtum-cli sendmany "myAccountA"`.
The account `"myAccountA"` has only one address associated, which is `Qbn1q4FevdXoV1KXQXXh3iZavRA1ZeZ63a`

In total the command I used was: 
`./qtum-cli sendmany "myAccountA" "{\"QjB563xtRr6jvT6WxrGbbnPXU4Qc87d7kp\":1.7108,\"QaYGYtgPEvoFAT795ZYJaRnSqGHoeDo7jV\":5.4658}" 1 "test"`

The wallet created a transaction. [Link to block explorer](https://qtum.info/tx/ebe39e15d0926e7c2bafa9b48d52b9d6d28e40f66988bb2e15d712ed0091c7e6).

There you can see that the transaction used UTXO for inputs not only from account `"myAccountA"` but also from my other accounts B and C. 

I expect the transactions should only use UTXOs from account `"myAccountA"`.

Instead UTXOs have been used from all accounts which my wallet has registered. 

In order to save transactions fees, I did not repeat this command yet. I assume there is some problem or bug in the UTXO selection algorithm when using the command `"sendmany"` in combination with `"fromaccount"` flag.

Version: qtum core 0.16.2, downloaded the binaries from qtum core github repo. 

Machine: RaspberryPi 3 with Ubuntu 16.04 LTS

**Comment by JB395** [comment]
This can be closed. Accounts do not control selection of UTXOs, this must be done manually using createrawtransaction, etc., or with coin control select INPUTS with the GUI wallet.

Accounts are fully deprecated in v0.17 and will be removed in v.18, with some of this functionality replaced by labels.
