### ISSUE TITLE
Help Text for getaccountinfo

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#624]
Help text for getaccountinfo is not very descriptive, it is not clear that this command is referencing a smart contract vs. the Core "account" concept. Suggest blockchain.cpp line 781

```
            "1. \"address\"          (string, required) The account address\n"
```

be changed and add two results lines:

```
            "1. \"address\"  (string, required) The contract address hash\n"
            "\nResult:\n"
            "Contract details including complete storage table and code\n"
```

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/1774408722fe0b332b6109a33b21e8018dd73b6d
