### ISSUE TITLE
Ubuntu Client Upgrade

### ISSUE THREAD

**Issue by NFhbar** [qtumproject/qtum#625]
I have `v0.15.3` installed in a Ubuntu machine which is installed through the regular ubuntu build from the `README`:
```
This is a quick start script for compiling Qtum on  Ubuntu


sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils git cmake libboost-all-dev
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev

# If you want to build the Qt GUI:
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler qrencode

git clone https://github.com/qtumproject/qtum --recursive
cd qtum

# Note autogen will prompt to install some more dependencies if needed
./autogen.sh
./configure 
make -j2

```

I can run `qtumd` no problem, however I am upgrading to the new client via:
`wget -q -O- "https://github.com/qtumproject/qtum/releases/download/mainnet-ignition-v0.16.2/qtum-0.16.2-arm-linux-gnueabihf.tar.gz" | tar -xzv -C /home/ubuntu`

The installation completes just fine but when I try to start the client it fails unless I add a `-reindex` flag:
`qtumd -daemon -server -reindex`

Any ideas?

**Comment by qtum-neil** [comment]
No reindex is required when upgrading from `v0.15.3` to a newer version, unless you are switching options like `-txindex` or `-logevents`.
If for some reason a reindex is required, then let it finish once, then it should work fine after that without having to use `-reindex` every time.
If the issue persists, please reopen the issue and provide the `debug.log` file startup logs.
