### ISSUE TITLE
multi sign address send qtum token raw transaction error

### ISSUE THREAD

**Issue by bebest2010** [qtumproject/qtum#626]
On testnet : 
$ ./qtum-cli --testnet  sendtocontract  a7e29015d41bc4e55c5b8b65309ddebb1760611a a9059cbb000000000000000000000000172e06536546e31410058d9edf0b2ea759b153270000000000000000000000000000000000000000000000000000000000123456  0 100000 0.0000004  mHJEeR2UXHsGjMn6hVyQ1Si4pJymWpG7cp
{
  "txid": "b8c15b12055416b3e4bf7e67bd34770b42bd330c14a627b0bf9c8cdebf7267fc",
  "sender": "mHJEeR2UXHsGjMn6hVyQ1Si4pJymWpG7cp",
  "hash160": "0000000000000000000000000000000000000000"
}

then I get the rawtransaction of txid :b8c15b12055416b3e4bf7e67bd34770b42bd330c14a627b0bf9c8cdebf7267fc

./qtum-cli --testnet gettransaction b8c15b12055416b3e4bf7e67bd34770b42bd330c14a627b0bf9c8cdebf7267fc
{
  "amount": 0.00000000,
  "fee": -0.04164000,
  "confirmations": 0,
  "trusted": false,
  "txid": "b8c15b12055416b3e4bf7e67bd34770b42bd330c14a627b0bf9c8cdebf7267fc",
  "walletconflicts": [
  ],
  "time": 1542790883,
  "timereceived": 1542790883,
  "bip125-replaceable": "unknown",
  "details": [
    {
      "account": "",
      "address": "mHJEeR2UXHsGjMn6hVyQ1Si4pJymWpG7cp",
      "category": "send",
      "amount": -0.95836000,
      "label": "testing",
      "vout": 0,
      "fee": -0.04164000,
      "abandoned": false
    },
    {
      "account": "",
      "category": "send",
      "amount": 0.00000000,
      "vout": 1,
      "fee": -0.04164000,
      "abandoned": false
    },
    {
      "account": "testing",
      "address": "mHJEeR2UXHsGjMn6hVyQ1Si4pJymWpG7cp",
      "category": "receive",
      "amount": 0.95836000,
      "label": "testing",
      "vout": 0
    }
  ],
  "hex": "020000000198f4483ff59d324fc234de59981a969b70bf88f88bf334d3753e2d5ee34ae67600000000da00483045022100cc72db7041e37c04c9a18f31406e1845eb545c59ea04cc050a7325402da0c182022036e4835e26ed3c3f0a8288ac3749d8d83ac12b65e8b6642e540fc0970d0ffcc10147304402201a1746082302c34d534579b00af695de1d44f013b775aa051376f4ab91171dc6022043d0a0ecf356590ad6780785a691755e30a014c8751047e7cc9afca7b8f461800147522102badbcd25a1fd0d350208b1ee20092c8addf389b2f114e0dff2bdd5a8614f2ad62103882474e940da24138f56d172980c9fc3a3aef17af466edcd4b47a40dbb06dff752aefeffffff026057b6050000000017a9140c457973e48c1b9a8d7881967ad2781600aa2b3887000000000000000063010403a08601012844a9059cbb000000000000000000000000172e06536546e31410058d9edf0b2ea759b15327000000000000000000000000000000000000000000000000000000000012345614a7e29015d41bc4e55c5b8b65309ddebb1760611ac2c4df0300"
}
then I try to broadcast this rawtransaction:
./qtum-cli --testnet sendrawtransaction 020000000198f4483ff59d324fc234de59981a969b70bf88f88bf334d3753e2d5ee34ae67600000000da00483045022100cc72db7041e37c04c9a18f31406e1845eb545c59ea04cc050a7325402da0c182022036e4835e26ed3c3f0a8288ac3749d8d83ac12b65e8b6642e540fc0970d0ffcc10147304402201a1746082302c34d534579b00af695de1d44f013b775aa051376f4ab91171dc6022043d0a0ecf356590ad6780785a691755e30a014c8751047e7cc9afca7b8f461800147522102badbcd25a1fd0d350208b1ee20092c8addf389b2f114e0dff2bdd5a8614f2ad62103882474e940da24138f56d172980c9fc3a3aef17af466edcd4b47a40dbb06dff752aefeffffff026057b6050000000017a9140c457973e48c1b9a8d7881967ad2781600aa2b3887000000000000000063010403a08601012844a9059cbb000000000000000000000000172e06536546e31410058d9edf0b2ea759b15327000000000000000000000000000000000000000000000000000000000012345614a7e29015d41bc4e55c5b8b65309ddebb1760611ac2c4df0300
error code: -26
error message:
16: bad-txns-invalid-sender-script

**Comment by qtum-neil** [comment]
The current design does not allow the use of multisig addresses as contract sender, thus the error message. The upcoming x86 design will allow that.

**Comment by bebest2010** [comment]
Why this command  :
./qtum-cli --testnet sendtocontract a7e29015d41bc4e55c5b8b65309ddebb1760611a a9059cbb000000000000000000000000172e06536546e31410058d9edf0b2ea759b153270000000000000000000000000000000000000000000000000000000000123456 0 100000 0.0000004 mHJEeR2UXHsGjMn6hVyQ1Si4pJymWpG7cp can input multi sig address?  Is this a bug?

**Comment by qtum-neil** [comment]
Yes, the rpc call should result in an error.
Will create a proper issue and fix in the next release.
