### ISSUE TITLE
Help: unknown command for 4 commands

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#631]
Help commands produce "unknown command" for 4 commands related to wallet locking and passphrase.

There is an extra Boolean (compared to bitcoin v0.17) of `pwallet->IsCrypted()` which must be true to produce help text for 

`walletpassphrase`
`walletpassphrasechange`
`walletlock`

and `pwallet->IsCrypted()` must be false to produce help for 

`encryptwallet`

otherwise requesting help for these commands returns "unknown command".

This doesn't seem "helpful." Help should provide the help text in every case as bitcoin Core does.

Unencrypted qtum-qt v0.16.2.0-47a30461d-dirty (64-bit):

![screenhunter 1862](https://user-images.githubusercontent.com/29760787/49056930-9a0d0600-f1cb-11e8-98ab-92c463a70c9d.jpg)

Suggested fix, remove the Boolean `pwallet->IsCrypted()` in rpcwallet.cpp lines:

2984  walletpassphrase()
3024  walletpassphrasechange()
3085  walletlock()
3125  encryptwallet()

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/aea8a16ca0cc89cf68e8adbb1159677423cd1d60
