### ISSUE TITLE
Update Solidity compiler (Remix) link

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#634]
Qtum Core v0.16.2

The "Solidity compiler" link on the Smart Contracts create page links to `https://ethereum.github.io/browser-solidity/` and a popup on that site gives this error message: 

"The Remix IDE has moved to http://remix.ethereum.org. This instance of Remix you are visiting WILL NOT BE UPDATED. Please make a backup of your contracts and start using http://remix.ethereum.org"

Suggest creartecontract.cpp line 112 should be updated to `http://remix.ethereum.org`, or maybe `https://qmix.blockchainspaceman.com/`

![create contract](https://user-images.githubusercontent.com/29760787/49329256-d92fb400-f549-11e8-8790-395a68a0320a.jpg)
Create Contract page

![popup message](https://user-images.githubusercontent.com/29760787/49329264-f19fce80-f549-11e8-8fc6-f4df4b9388e5.jpg)
Pop error message on old Remix

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/f1a94aae8db7dd99ecb480f92c59620496bb5836
