### ISSUE TITLE
Event emitter emit the event on caller contract instead of actual contract which has the event

### ISSUE THREAD

**Issue by patidarmanoj10** [qtumproject/qtum#652]
**Example:**

     contract Contract1 {

     Contract2 contract2;
     function initContract(address _c) {
       contract2 = Contract2(_c)
     }
     function callerFunction() public {
       contract2.somefunction();
     }
    }

    contract Contract2 {

     event myEvent(uint abc);
     function somefunction() public {
        .....
        emit myEvent(10);
     }
    }

When we call function of contract2 from other contract . Ex- contract1.callerFunction(), 'myEvent' is emitted on contract1 instead of contract 2.

**Actual**: 
var emitter = contract1.logEmitter({ minconf: 0 })
  emitter.on('myEvent', (event) => {
    console.log('1 received event in qtum', event)
  })

**Expected**:  

var emitter = contract2.logEmitter({ minconf: 0 })
  emitter.on('myEvent', (event) => {
    console.log('1 received event in qtum', event)
  })
Since myEvent is defined in contract2 this should listen event on contract2 instead of contract1 . This is how it work in ethereum and expected to work same way in qtum. If this is otherwise then should be documented 

qtum version - 0.17.1

PS: please ignore syntax error above. This is just for explanation.

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/122a02716128755a60bfc042c87048acf01cacda
