### ISSUE TITLE
v0.17.1 All Debug Output Printed to Console

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#654]
With qtumd running on Windows 10, 64 bit, after the v0.17.1 upgrade, all debug information is printed to the console. Previous versions (with default settings) did not print debug info to the console. 

Is there a config file parameter or command line switch to turn printing of debug info on and off?

**Comment by qtum-neil** [comment]
Set `-printtoconsole=0` to disable it, and set the log file using `-debuglogfile`
