### ISSUE TITLE
GUI Wallet Staking Icon not Updating Correctly

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum#655]
Telegram user Balázs reported an incorrect staking icon status, running qtum-qt v0.17.1 on Archlinux with kernel 4.20.4.

Balázs was using a new installation of qtum-qt and new transactions with about 900 confirmations (confirmed on Explorer). The staking icon showed a white center with the message “"Not staking because you don't have mature coins":

![image](https://user-images.githubusercontent.com/29760787/52534684-ad336a80-2d12-11e9-82cc-4afea408feaa.png)

At the same time, the wallet’s getstakinginfo gave:

```
{
  "enabled": true,
  "staking": true,
  "errors": "",
  "currentblocktx": 0,
  "pooledtx": 0,
  "difficulty": 2868384.619855732,
  "search-interval": 59981,
  "weight": <snip>,
  "netstakeweight": 1443014698081814,
  "expectedtime": <snip>
}
```
The wallet had been running about 17 hours by this point, so would have gone through the not mature -> mature transition.

The wallet’s getnetworkinfo gave:

```
{
  "version": 170100,
  "subversion": "/Satoshi:0.17.1/",
  "protocolversion": 70016,
  "localservices": "000000000000040d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
<snip>

```
Exiting and restarting the wallet gave a correct Staking Icon (black center).

### Reproducing on Win10 Testnet Machine

Able to reproduce using similar sequence for maturing coins on Testnet with v0.17.1 qtum-qt on Windows 10.

1. Install new wallet on Testnet, encrypt, send coins:

![image](https://user-images.githubusercontent.com/29760787/52534713-ea97f800-2d12-11e9-9ee0-d538410749a9.png)

![image](https://user-images.githubusercontent.com/29760787/52534715-f2579c80-2d12-11e9-9aae-1e138b54a2af.png)

2. Leave decrypted wallet setting on My Wallet page. getstakinginfo shows staking “false” (see below 06:52:17 )

3. 25 hours later the staking icon has not updated to a black center, getstakinginfo shows staking “true” at 07:54:27:

![image](https://user-images.githubusercontent.com/29760787/52534719-04d1d600-2d13-11e9-98cf-1893e1184999.png)

715 confirmations:

![image](https://user-images.githubusercontent.com/29760787/52534726-187d3c80-2d13-11e9-991d-fc7ffa829c41.png)

Mouseover the staking icon shows incorrect status:

![image](https://user-images.githubusercontent.com/29760787/52534736-27fc8580-2d13-11e9-949c-f66e4bf8ccb0.png)

4. Restarting the wallet and decrypting, after two seconds the staking icon showed a black center:

![image](https://user-images.githubusercontent.com/29760787/52534743-3b0f5580-2d13-11e9-8fb2-0c967d4016bc.png)

Debug log for this wallet attached.

[debug after restarting.log](https://github.com/qtumproject/qtum/files/2848954/debug.after.restarting.log)

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/ac170761aa7d3b9b65c50e1f5fa1a75d9ff0b27d
