### ISSUE TITLE
Where is `New Receiving Address` button?

### ISSUE THREAD

**Issue by susemi99** [qtumproject/qtum#661]
I Can't find `new receiving address` button. 

![screenshot](https://user-images.githubusercontent.com/1233318/53614066-dc574080-3c1b-11e9-8be0-68b701921b2d.jpg)

always on v0.17.2

self-compiled v0.17.2
![screenshot 1](https://user-images.githubusercontent.com/1233318/53614264-b7170200-3c1c-11e9-8295-05bdefca565b.jpg)

macOS High Sierra, i7 2GHz, SSD + HDD fusion drive

**Comment by qtum-neil** [comment]
You need to click the "REQUEST PAYMENT" button in the top right of the Receive tab.
