### ISSUE TITLE
Unaccounted for Qtum

### ISSUE THREAD

**Issue by Ogolero** [qtumproject/qtum#684]
Excuse my ignorance if I make it obvious in any part of this, I am a neophyte 2 finger typer. 

I’ve been staking Qtum since 2017 with no issue up till now. Last night I upgraded to version 17.5 and went to sleep with “x” amount of Qtum and woke up 6hrs later with a specific amount missing. The amount is what you would expect the stake to be for 3 mining blocks. There are no transactions going out on my log so it didn’t go anywhere. Im running Windows 10 on a laptop dedicated to staking Qtum. There’s no evidence of it having left anywhere and if I tally all my incoming trancations and my only ever outgoing transaction (.37 Qtum) the numbers don’t match. It’s almost as if they’re not being accounted for when the GUI sums everything up. The amount being held for “staking” seems right, the amount “pending” is zero which doesn’t seem right but also if it was what I would expect it to be it wouldn’t account for what’s missing, the amount “available” is what seems to be short. Also the amount available and the amount of “staking power” I have match up so it’s system wide. My only stab in the dark guess is that some amounts being held for staking didn’t transfer back to available after the 501 transactions but I’m completely guessing. Maybe it’s a bug in the update???

Thank you for your time and please advise if I can do anything to clarify for you. I purposely withheld exact amounts because it’s usually not appropriate but advise further and I will detail.

**Comment by qtum-neil** [comment]
You could have been affected by the bug that 0.17.5 fixes, I recommend backing up your wallet file and trying `-reindex` or sync from scratch.

**Comment by Ogolero** [comment]
qtum-neil,

Thank you so much. I used an old backup and reindexed and 6hrs later all was as it should be. I’m very grateful for your time and help in what now seems like an obvious solution. I wish you all the best now and in future endeavors.
