### ISSUE TITLE
WIN 64 QTUM Mainnet Wallet fails to launch

### ISSUE THREAD

**Issue by Breezin56** [qtumproject/qtum#686]
When downloading the QTUM wallet for WIN 64 from the QTUM website, I receive a message as follows:

![image](https://user-images.githubusercontent.com/34943318/57779372-f7523080-76f3-11e9-97f2-9ee7ca4bd903.png)

"Error Opening Block Database"
"Do you want to rebuild the Block Database now?"
"OK or Abort"

Pressing OK leads to the same result.  Any help or guidance would be greatly appreciated.

**Comment by shannon1916** [comment]
You can delete the datadir manually, which is located at 
    // Windows < Vista: C:\Documents and Settings\Username\Application Data\Qtum
    // Windows >= Vista: C:\Users\Username\AppData\Roaming\Qtum
by default. Notice! By this means, you will lost all your wallet data.

**Comment by qtum-neil** [comment]
Seems the block data is corrupt, try deleting everything but wallet.dat from the data directory (C:\Documents and Settings\Username\Application Data\Qtum) and relaunch.
