### ISSUE TITLE
Cannot open configuration file in QT wallet on Mac

### ISSUE THREAD

**Issue by shannon1916** [qtumproject/qtum#689]
When click "OPEN CONFIGURATION FILE", it shows "The configuration file could not be opened". This happens on Mac, when no default application is assigned for opening ".conf" files. This also happens in Bitcoin QT wallet as https://github.com/bitcoin/bitcoin/issues/15409.

![image](https://user-images.githubusercontent.com/3756217/57979320-cb65e080-7a4e-11e9-9e00-dc484b42c8d8.png)

**Comment by shannon1916** [comment]
A suitable solution seems to be using QProcess::startDetached to run "open -t qtum.conf" command on Mac, so as to open the configuration file with default text editor.

**Comment by shannon1916** [comment]
This is fixed in bitcoin by this PR https://github.com/bitcoin/bitcoin/pull/16044.

**Comment by JB395** [comment]
Seeing this same problem, as are others.

My system: Mac mini (2010) with macOS High Sierra v10.13.6.

Sequence for qtum-qt v0.17.3: Qtum Core – Preferences – OPEN CONFIGURATION FILE – OK

Got error “The configuration file could not be opened”:

![1](https://user-images.githubusercontent.com/29760787/59150909-a71b7500-89f8-11e9-8950-2410c14dfd91.png)

Looking in the Qtum data directory, there was a file “qtum.conf” with no application set:

![2](https://user-images.githubusercontent.com/29760787/59150915-b8fd1800-89f8-11e9-93b0-9bd05cca4213.png)

Set the Qtum Core application to open qtum.conf:

![3](https://user-images.githubusercontent.com/29760787/59150918-c74b3400-89f8-11e9-82fe-fa202b1198aa.png)

Trying OPEN CONFIGURATION FILE produced a brief popup “Qtum – Payment request file handling” (and the config file did not open):

![4](https://user-images.githubusercontent.com/29760787/59150923-daf69a80-89f8-11e9-8916-c12d833b4401.png)

Completely deleted Qtum Core 0.17.3 and installed 0.17.5.

Selecting the sequence Qtum Core – Preferences – OPEN CONFIGURATION FILE – OK produced no response. The debug log got the log line:

```
GUI: PaymentRequestPlus::parse: Error parsing payment request
```

**Comment by qtum-neil** [comment]
@shannon1916 please make a PR with the fix.

**Comment by shannon1916** [comment]
@JB395 You should not use `Qtum Core` to open `qtum.conf`. It should be opened with a text editor.  Anyway, this bug is fixed by us in Bitcoin https://github.com/bitcoin/bitcoin/pull/16044 and we'll merge it to Qtum soon.😆
