### ISSUE TITLE
Fail to sync

### ISSUE THREAD

**Issue by Ogolero** [qtumproject/qtum#690]
Hello and good day, requesting some help please. The Qtum GUI has appeared to have frozen for me and is unable to sync up ever since. I have been staking for over a year with success but it appears 5/17/2019 03:54 EST is the last time I was connected to the blockchain. Since then I have restarted many times, Deleted/Download/Installed, tried with previous versions, reindexed off a backup and cannot finish “Syncing Headers”. I’ve exhausted every resolution I could think of to not waste anybodies time with a simple fix but I cannot figure this out. 

Running ver 17.5 on WIN 10 64 off the provided zip. 

I have provided some pictures in case they help you. Thank you for your time and response. 

![5E5BA76B-8D97-4100-9F53-BA2A73588B16](https://user-images.githubusercontent.com/48522700/57991133-e8b0a400-7a7a-11e9-99f2-1e8f0395be9b.jpeg)
![E15AA7FD-84BF-45E8-8062-AD62E169D473](https://user-images.githubusercontent.com/48522700/57991134-e8b0a400-7a7a-11e9-9dcd-33198361efa5.jpeg)
![A997E4A5-C9A5-4267-A035-1FAA8F832270](https://user-images.githubusercontent.com/48522700/57991135-e8b0a400-7a7a-11e9-94b5-44a88325b9df.jpeg)
![2609374C-6396-4AAB-B83E-2DCB9F18704F](https://user-images.githubusercontent.com/48522700/57991137-e8b0a400-7a7a-11e9-9b25-f85ef6401fbd.jpeg)
![905CF606-01E3-4491-BBAA-CA6E03F9E67B](https://user-images.githubusercontent.com/48522700/57991136-e8b0a400-7a7a-11e9-8708-cd4fa248fab4.jpeg)

**Comment by qtum-neil** [comment]
Please go to the console and post the results for `getpeerinfo`

**Comment by JB395** [comment]
Hmm. Ogoloeo, your wallet appears to be making peer connections. If your blockchain syncing is stuck I suggest deleting the blockchain and resyncing the whole thing. Make sure you have a good backup of your wallet.dat file first, then follow the steps in this blog, Question 6, step 5: https://medium.com/@jb395official/top-10-qtum-new-user-questions-december-8-2018-fed45b18bf5e

**Comment by qtum-neil** [comment]
Moved here https://github.com/qtumproject/qtum/issues/690
