### ISSUE TITLE
Fail to sync #2

### ISSUE THREAD

**Issue by Ogolero** [qtumproject/qtum#691]
Sorry, I don’t know how to attach a picture without opening a new issue. 

As requested, Console, getpeerinfo

Thank you again

**Comment by qtum-neil** [comment]
Seems you are connected to a single node that is not synced, you need to get more connections.

You could also be on a bad fork, please make a backup of your wallet, clean your datadir (except wallet.dat), and try relaunching again.

You should get a few connection (8+), if not make sure your firewall is set to allow traffic on port 3888.

**Comment by Ogolero** [comment]
Thank you for the help. Turns out I was on a bad fork which explains why I was on the best 7 days of staking of my life, I knew it was too good to be true. I had no idea where my computer was storing the datadir but I was able to locate and delete the wrong chain to start all over and things are back to normal. Excuse my ignorance and thank you for your patience, I won’t have the same problem twice.
