### ISSUE TITLE
Minimal build fails to link

### ISSUE THREAD

**Issue by wkarshat** [qtumproject/qtum#710]
Ubuntu 18.04
git clone https://github.com/qtumproject/qtum --recursive
./configure --with-incompatible-bdb --disable-wallet --without-gui --without-miniupnpc

ld not finding GetMPoSOutputScripts(), CReserveKey::ReturnKey(), etc...

Full configuration and error output in attached files.

[qtum.txt](https://github.com/qtumproject/qtum/files/3336589/qtum.txt)
[config.log](https://github.com/qtumproject/qtum/files/3336591/config.log)

**Comment by xuanyan0x7c7** [comment]
--disable-wallet doesn't work well now, you may remove it

**Comment by qtum-neil** [comment]
Fixed https://github.com/qtumproject/qtum/pull/716
