### ISSUE TITLE
Link to source tar.gz?

### ISSUE THREAD

**Issue by swedebugia** [qtumproject/qtum#711]
Hi.
I could not find a link to a stable source tarball, but I see one mentioned in the shasums. Could you upload that to github or provide the link?

**Comment by qtum-neil** [comment]
You can download the source code from the [releases](https://github.com/qtumproject/qtum/releases) page, under `Source code (tar.gz)`.

We stopped uploading the source tarball that results from gitian builds, but only publish its hash (for gitian builders) as GitHub automatically offers tarball download.

**Comment by swedebugia** [comment]
Hi again :)
Thanks for the response. Unfortunately the github archive tarballs are worthless to Guix because they are not stable and thus not reproducible. That was the reason for my request.

**Comment by qtum-neil** [comment]
I uploaded the tarball in releases: https://github.com/qtumproject/qtum/releases/download/mainnet-ignition-v0.17.6/qtum-0.17.6.tar.gz

Will do it for next releases as well.
