### ISSUE TITLE
Build from checkout (non-recursive) of latest release fails

### ISSUE THREAD

**Issue by swedebugia** [qtumproject/qtum#712]
starting phase `build'
Making all in src
make[1]: Entering directory '/tmp/guix-build-qtum-core-0.17.6.drv-0/source/src'
make[2]: Entering directory '/tmp/guix-build-qtum-core-0.17.6.drv-0/source/src'
  CXX      qtumd-bitcoind.o
In file included from ./consensus/params.h:9:0,
                 from ./chainparams.h:10,
                 from bitcoind.cpp:10:
./uint256.h:18:31: fatal error: libdevcore/Common.h: No such file or directory
compilation terminated.

The line offending are:
https://github.com/qtumproject/qtum/blob/6c1d36ebf64bbf94d17da8b22b014bcdf72bfbde/src/uint256.h#L18 which is not present in bitcoin-core.

Is there some dependency i'm missing?

**Comment by qtum-neil** [comment]
Qtum implements the EVM as a submodule, so you either have to use `--recursive` when cloning, or to manually clone https://github.com/qtumproject/cpp-eth-qtum as `src/cpp-ethereum/`
