### ISSUE TITLE
fatal error: libdevcore/Common.h: No such file or directory

### ISSUE THREAD

**Issue by 01BTC10** [qtumproject/qtum#726]
Hello, I am trying to build mainnet-ignition-v0.17.6 from git on aarch64 Arch Linux ARM for raspberrypi 3B+. The system was updated and rebooted before attempting the build.

My configuration flags are:

> ./configure --disable-wallet --without-gui

The build logs show theses errors:

> Making all in src
make[1]: Entering directory '/home/r2d2/qtum/src'
make[2]: Entering directory '/home/r2d2/qtum/src'
  CXX      qtumd-bitcoind.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
In file included from ./consensus/params.h:9,
                 from ./chainparams.h:10,
                 from bitcoind.cpp:10:
./uint256.h:18:10: fatal error: libdevcore/Common.h: No such file or directory
 #include <libdevcore/Common.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:14168: qtumd-bitcoind.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ./protocol.h:15,
                 from ./addrman.h:10,
                 from addrman.cpp:6:
./uint256.h:18:10: fatal error: libdevcore/Common.h: No such file or directory
 #include <libdevcore/Common.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:10052: libbitcoin_server_a-addrman.o] Error 1
In file included from ./primitives/transaction.h:13,
                 from ./primitives/block.h:9,
                 from ./blockencodings.h:8,
                 from blockencodings.cpp:5:
./uint256.h:18:10: fatal error: libdevcore/Common.h: No such file or directory
 #include <libdevcore/Common.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:10080: libbitcoin_server_a-blockencodings.o] Error 1
In file included from ./primitives/transaction.h:13,
                 from bloom.cpp:7:
./uint256.h:18:10: fatal error: libdevcore/Common.h: No such file or directory
 #include <libdevcore/Common.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:10066: libbitcoin_server_a-bloom.o] Error 1
In file included from ./protocol.h:15,
                 from ./addrman.h:10,
                 from addrdb.cpp:8:
./uint256.h:18:10: fatal error: libdevcore/Common.h: No such file or directory
 #include <libdevcore/Common.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:10038: libbitcoin_server_a-addrdb.o] Error 1
make[2]: Leaving directory '/home/r2d2/qtum/src'
make[1]: *** [Makefile:15365: all-recursive] Error 1
make[1]: Leaving directory '/home/r2d2/qtum/src'
make: *** [Makefile:778: all-recursive] Error 1

I did successfully build bitcoin and zcash on this system. 
I did find this issue that was resolved but without any details: https://github.com/ethereum/solidity/issues/813
I am attaching the config.log to this post.
[config.log](https://github.com/qtumproject/qtum/files/3449540/config.log)

**Comment by qtum-neil** [comment]
Try cloning with `--recursive`:

`git clone --recursive https://github.com/qtumproject/qtum.git`

You can also use the ARM release in [releases](https://github.com/qtumproject/qtum/releases/).
