### ISSUE TITLE
non-p2pkh address can be selected as contract sender

### ISSUE THREAD

**Issue by icodeface** [qtumproject/qtum#748]
## description

In [Disallow P2SH addresses as sender in contract rpc calls](https://github.com/qtumproject/qtum/commit/3f9702578c6a5ec1ad8df7c7e04fc1aa2aa8f50b) we have a check for sender address, but when we call `createcontract` or `sendtocontract` without specifying sender address, Qtum Core wallet might choose a non-p2pkh address to the first place of inputs. 

## how to reproduce
1. create a new wallet
2. get a p2sh address by `qtum-cli getnewaddress "" "p2sh-segwit"`
3. send some coins to this address from outside
4. create a contract without specifying sender address
   ![](https://imgur.com/3As1sli.png)
5. the p2sh address was selected as sender
   ![](https://imgur.com/5l6rsoo.png)

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/pull/759
