### ISSUE TITLE
v0.18.1 jsonrpc issue

### ISSUE THREAD

**Issue by SeongKuk** [qtumproject/qtum#768]
Hello qtum team.

My qtum options are txindex, server, rest, rpcallowip, rpcport, rpcuser, rpcpassword.

I have a problem that json-rpc after upgrading v0.18.1

qtum-cli is working but curl connection refused if i send json-rpc using curl.

So, i tested crul after downgrading v0.17.6 .
It is working.

Can you check this problem??

**Comment by icodeface** [comment]
remove `-rest` and see https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md#configuration-option-changes
