### ISSUE TITLE
0.18.1 links agains glibc 2.18 not availble on CentOS 7

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [qtumproject/qtum#770]
This issue tracker is only for technical issues related to Qtum.

Describe the issue
Official build of qtum 0.18.1 is built agains glibc 2.18 that is not availble on CentOS 7

What behavior did you expect?
I'd like to run qtum on latest stable centos if it is supported by application

What was the actual behavior (provide screenshots if the issue is GUI-related)?
```
# ldd bin/qtumd 
bin/qtumd: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by bin/qtumd)
	linux-vdso.so.1 =>  (0x00007ffee14cd000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff31f62a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff31f40e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff31f10c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff31eef6000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff31eb29000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff320c6a000)
```

How reliably can you reproduce the issue, what are the steps to do so?

What version of Qtum are you using, where did you get it (website, self-compiled, etc)?
0.18.1

What type of machine are you observing the error on (OS/CPU and disk type)?
CentOS 7.7.1908

**Comment by qtum-neil** [comment]
The public release now requires GLIBC >=2.18, we will make a build for centos7 and add it to our repo soon.
