### ISSUE TITLE
What is the dust limit of qtum transfer

### ISSUE THREAD

**Issue by vae520283995** [qtumproject/qtum#774]
I see that the source code dust limit is 0.000728qtum, but my transfer 0.002 is wrong.

**Comment by JB395** [comment]
The dust limit for legacy addresses is 72800 Satoshis, which is hard coded.

**Comment by vae520283995** [comment]
> The dust limit for legacy addresses is 72800 Satoshis, which is hard coded.

https://explorer.qtum.org/insight-api/ limit is 218400 but self node is 72800
