### ISSUE TITLE
not able to run qtuminfo with 0.18.1 docker image

### ISSUE THREAD

**Issue by patidarmanoj10** [qtumproject/qtum#778]
I am running a qtumd version 0.18.1 from docker image.  I setup qtuminfo . It starts download headers to insert into mysql.  After headers downloads complete ,  I get error "method not found" and quit.   If I build and run qtumd from qtum/qtuminfo branch , everything work well. What is the difference between building & running qtumd from qtum/qtuminfo  and docker 0.18.1 image?

**Comment by xuanyan0x7c7** [comment]
Some new features used by blockchain explorer are added into the `qtuminfo` branch
