### ISSUE TITLE
181  gets stuck at syncing headers

### ISSUE THREAD

**Issue by Joehrs** [qtumproject/qtum#781]
when starting wallet, it gets stuck at syncing headers 99.6 percent

**Comment by JB395** [comment]
Hello Joehrs,

When the wallet gets stuck syncing the blockchain, I suggest exiting the wallet, deleting the local copy of the blockchain (in the Qtum data directory, delete the folders "blocks", "stateQtum" and "chainstate") and starting over. 

Assume you are running version 0.18.1 and have peer connections.

**Comment by Earlz** [comment]
Closing as this seems to be answered
