### ISSUE TITLE
Unit tests in constantinoplefork_tests.cpp fail when the test cases are shuffled

### ISSUE THREAD

**Issue by oyyq99999** [qtumproject/qtum#790]
The cases are likely to fail when they are shuffled by setting environment variable `BOOST_TEST_RANDOM` to `1`.
It fails 100% when `checking_constantinople_before_fork` runs before `checking_returndata_opcode_after_fork`.

**Comment by oyyq99999** [comment]
Currently fixed in a weird way [here](https://github.com/oyyq99999/qtum/commit/756a4129a842039137d401a584dfc91364e3b614).

**Comment by qtum-neil** [comment]
fixed here https://github.com/qtumproject/qtum/pull/791
