### ISSUE TITLE
Compile and report errors

### ISSUE THREAD

**Issue by wo4zhuzi** [qtumproject/qtum#794]
In file included from ./cpp-ethereum/libethereum/CommonNet.h:28:0,
                 from ./cpp-ethereum/libethereum/ClientBase.h:30,
                 from ./cpp-ethereum/libethereum/Client.h:27,
                 from ./cpp-ethereum/libethashseal/Ethash.h:25,
                 from ./validation.h:44,
                 from checkpoints.cpp:10:
./cpp-ethereum/libp2p/Common.h: In member function ‘dev::p2p::Node::operator bool() const’:
./cpp-ethereum/libp2p/Common.h:259:52: error: cannot convert ‘const NodeID {aka const dev::FixedHash<64u>}’ to ‘bool’ in initialization
     explicit operator bool() const { return bool{id}; }
                                                    ^
In file included from ./cpp-ethereum/libethereum/CommonNet.h:28:0,
                 from ./cpp-ethereum/libethereum/ClientBase.h:30,
                 from ./cpp-ethereum/libethereum/Client.h:27,
                 from ./cpp-ethereum/libethashseal/Ethash.h:25,
                 from ./validation.h:44,
                 from blockencodings.cpp:14:
./cpp-ethereum/libp2p/Common.h: In member function ‘dev::p2p::Node::operator bool() const’:
./cpp-ethereum/libp2p/Common.h:259:52: error: cannot convert ‘const NodeID {aka const dev::FixedHash<64u>}’ to ‘bool’ in initialization
     explicit operator bool() const { return bool{id}; }
                                                    ^
Makefile:11943: recipe for target 'libbitcoin_server_a-checkpoints.o' failed
make[2]: *** [libbitcoin_server_a-checkpoints.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ./cpp-ethereum/libethereum/CommonNet.h:28:0,
                 from ./cpp-ethereum/libethereum/ClientBase.h:30,
                 from ./cpp-ethereum/libethereum/Client.h:27,
                 from ./cpp-ethereum/libethashseal/Ethash.h:25,
                 from ./validation.h:44,
                 from ./txdb.h:20,
                 from ./index/txindex.h:10,
                 from init.cpp:24:
./cpp-ethereum/libp2p/Common.h: In member function ‘dev::p2p::Node::operator bool() const’:
./cpp-ethereum/libp2p/Common.h:259:52: error: cannot convert ‘const NodeID {aka const dev::FixedHash<64u>}’ to ‘bool’ in initialization
     explicit operator bool() const { return bool{id}; }
                                                    ^
Makefile:11901: recipe for target 'libbitcoin_server_a-blockencodings.o' failed
make[2]: *** [libbitcoin_server_a-blockencodings.o] Error 1
Makefile:12069: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 1
make[2]: Leaving directory '/root/qtum/src'
Makefile:18637: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/qtum/src'
Makefile:786: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by denuoweb** [comment]
How did you fix this?
