### ISSUE TITLE
qtumcore Asset disappeared

### ISSUE THREAD

**Issue by nearzen** [qtumproject/qtum#796]
Synchronization did not proceed in 96%, so after reblocking by checking enable log event in option, the number was reduced from 1,176.39226978 qtum to 270.1936 qtum.

address: QYgrQpGFME7RL59fBTDWSWWGmbfy4YNbwD, QiEijaNuKFDEbRqQs4837sgeL97AcKume3, QYvE5UWfUd7JGNGSbyAaD2KYeLVJpKK2GC

![마이](https://user-images.githubusercontent.com/23025861/71605160-4cbb4f00-2baa-11ea-9a94-dc76b9a0cc62.png)
![받은](https://user-images.githubusercontent.com/23025861/71605177-5775e400-2baa-11ea-9062-b09ba9c07bda.png)
![보낸](https://user-images.githubusercontent.com/23025861/71605181-5ba20180-2baa-11ea-826f-1b326f66a3ba.png)

**Comment by JB395** [comment]
Hello nearzen, if your wallet is fully synced it is possible it has a problem with an orphan block. In this case you may see a debug log entry for "CT_DELETED".

Please make a backup of your wallet.dat file and follow the procedure "2. Zap Your Wallet" in this blog: https://blog.qtum.org/qtum-hard-fork-part-2-7965f86c0f59

**Comment by nearzen** [comment]
Rescan the block with restore wallet. thank you.
