### ISSUE TITLE
0.18.3 estimatesmartfee error

### ISSUE THREAD

**Issue by yangjianyao** [qtumproject/qtum#806]
[root@localhost ~]# cd /data/qtum-data/qtum-0.18.3/bin/
[root@localhost bin]# ./qtum-cli estimatesmartfee 6
{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 6
}
[root@localhost bin]# 
我想获取feerate，但是这个接口报错。这个方法再btc,ltc上都是可用的，是不是qtum的问题，我使用的是testnet

**Comment by yangjianyao** [comment]
i want get feeRate by estimatesmartfee, but it error. how i fix it ? i use testnet

**Comment by JB395** [comment]
Hello yangjianyao, on Testnet there may be enough recent transactions for `estimatesartfee` to return a good value. Unless the blocks are full there is no reason to use a fee above the minimum and you can use a feerate of 0.004. Would this work for you?

**Comment by yangjianyao** [comment]
thanks,on Mainnet can use estimatesartfee for get feerate?

**Comment by JB395** [comment]
Yes, Mainnet will give something like

```
estimatesmartfee 6

{
  "feerate": 0.00419133,
  "blocks": 6
}
```

**Comment by xuanyan0x7c7** [comment]
If you are get `Insufficient data or no feerate found` on response, it means there are too few transactions on recent blocks, just use 0.004 instead.
