### ISSUE TITLE
Qtum wallet launch error: Cannot parse configuration file: parse error on line 2, using # in rpcpassword can be ambiguous and should be avoided.

### ISSUE THREAD

**Issue by moofidev** [qtumproject/qtum#853]
Downloaded the latest wallet version Mainnet Ignition v0.19.1 for Mac (qtum-0.19.1-osx-unsigned.dmg)
double click to open got error
**Error**: Cannot parse configuration file: parse error on line 2, using # in rpcpassword can be ambiguous and should be avoided.

**Comment by JB395** [comment]
Seems like a useful warning, # indicates a comment in the configuration file. Suggest you don't include # in a password.

**Comment by Earlz** [comment]
Closing as this seems to be answered
