### ISSUE TITLE
NBXplorer (Backend for BTCPayServer) not connecting to v0.19.1

### ISSUE THREAD

**Issue by dabura667** [qtumproject/qtum#857]
Related issue: #842 

v0.19.0 was syncing fine and detecting deposits for UTXO deposits, but upgrading to v0.19.1 causes P2P handshake to fail.

**Expected behavior**

NBXplorer is able to connect via P2P.

**Actual behavior**

P2P handshake failed

```
QTUM: NBXplorer connected to the remote node but failed to handhsake via P2P.
dotnet: Your node may not have an available connection slot, or you may try to connect to the wrong node. (ie, trying to connect to a LTC node on the BTC configuration).
dotnet: To make sure your node have an available connection slot, use "whitebind" or "whitelist" in your node configuration. (typically whitelist=127.0.0.1 if NBXplorer and the node are on the same machine.)
```

`"whitebind" or "whitelist"` was set and it still gave the same error.

Any ideas as to what change from v0.19.0 to 1 could affect P2P handshake? (or connection)

**Comment by qtum-neil** [comment]
0.19.1 is a hardfork release, it will drop connection with older peers, make sure your peers are using 0.19.1 as well.

**Comment by dabura667** [comment]
That makes sense.

https://github.com/MetacoSA/NBitcoin/blob/d822f191441b2da5abdd3ab4765cf82296dbea18/NBitcoin.Altcoins/Qtum.cs#L179-L182

So I should change `.SetMaxP2PVersion(70017)` to `.SetMaxP2PVersion(70018)` ?

**Comment by qtum-neil** [comment]
Yes that should work.

**Comment by dabura667** [comment]
I was told NBitcoin doesn't have the concept of MinP2PVersion, since relying on the peer to not lie to you with an easily changeable version is not safe, so if you are trying to keep certain peers from giving you bad information it is better to use a combination of verifying the info they give you and banning their IP if they give you too much garbage.

Though I do see how it could be a quick filter for noise. I also see why they wouldn't want to include such a thing.

**Comment by dabura667** [comment]
I made a PR https://github.com/MetacoSA/NBitcoin/pull/909

**Comment by qtum-neil** [comment]
Changing the max peer version should at least allow peers with the current version, so at least some of the peers will be ok, the others will get banned for sending bad blocks and such.

**Comment by dabura667** [comment]
BTCPay is passive and doesn't relay transactions or blocks, it just sucks them in from one peer (the one in the settings, which is also run by us, running 0.19.1)

But we will keep it in mind.

**Comment by luxsobcz** [comment]
Do u know how quntum work... If u can't connet u most probably use of only
data concept... Simply takes Infosys what u needed and now I have connect
to you...
But I also don't need more... 🙂
Connect to someone who need u, need your time.

czw., 10 wrz 2020, 03:36 użytkownik Dabura667 <notifications@github.com>
napisał:

**Comment by dabura667** [comment]
> I made a PR [MetacoSA/NBitcoin#909](https://github.com/MetacoSA/NBitcoin/pull/909)

This PR was merged and a new version of NBitcoin.Altcoins, NBXplorer where published.

Everything is working now post-fork.
