### ISSUE TITLE
RPC: callcontract should allow `amount` option

### ISSUE THREAD

**Issue by hayeah** [qtumproject/qtum#862]
in `sendtocontract` there is:

```
3. amount             (numeric or string) The amount in QTUM to send. eg 0.1, default: 0
```

need something similar for `callcontract`

(am i missing something again?)

**Comment by hayeah** [comment]
@qtum-neil ping. can we have this, kinda urgent to estimate gas for some calls.

**Comment by qtum-neil** [comment]
ACK

**Comment by hayeah** [comment]
thanks, this worked!
