### ISSUE TITLE
staking question

### ISSUE THREAD

**Issue by AGhub31** [qtumproject/qtum#871]
Good morning, could you tell me if QTUM core wallet is the only wallet to stake qtum or are there any other option?
On core wallet is it necessary the wallet is online and connected to internet in order to staking?
Many thanks.

**Comment by JB395** [comment]
Hey AGhum31. Yes, the Qtum Core wallet is the only way to stake Qtum. This wallet is a full node that validates and relays every transaction, block, and executes every EVM contract call. Additionally if it holds QTUM it can participate in Proof of Stake consensus and publish blocks to the network. The wallet must be online 24/7 to perform these actions in real time.

However there is an option to use offline staking protocol and delegate a Qtum address to an online super staker - a Qtum Core wallet configured to stake the UTXOs from a delegated address. With this approach a delegating wallet (currently the Qtum Core wallet, Qtum Electrum and Qtum Web wallets) can assign the address to delegate and then go offline while the super staker continues to stake the UTXOs for that address. Note only the address is delegated and the delegating wallet keeps full control of the coins (a non-custodial delegation). Read more about offline staking using the Qtum Core wallet at https://github.com/qtumproject/documents/blob/master/en/OfflineStaking.md#offline-staking.

**Comment by Earlz** [comment]
Closing as this seems to be answered
