### ISSUE TITLE
amount of qtum in conflicted transaction  is gone and never get back.

### ISSUE THREAD

**Issue by munakaya** [qtumproject/qtum#872]
I sent 1 qtum to another address by qtum-cli. But It did not came.
So after around 2 month, I run qtum-qy and I could see below log.
It shows the transaction conflicted.

I wonder why the qtum that used for transaction did not came to me and anywhere else.
If the transaction conflict then, is it gone forever ????
How can I get back my qtum????

Status: conflicted with a transaction with 34901 confirmations
Date: 20. 9. 28. 15:41
To: QifeXnLFATei6m7w7kBAwVhHvMz8sXe17Z
Debit: -1.00000000 QTUM
Transaction fee: -0.00083454 QTUM
Net amount: -1.00083454 QTUM
Transaction ID: 694ce90025c4580eaca62d53c5a06c1363ed57582b13e94872bba74da1bf1cd4
Transaction total size: 191 bytes
Transaction virtual size: 191 bytes
Output index: 1

**Comment by JB395** [comment]
Hello munakaya,

Assuming you were using wallet version 0.19.1 on September 28, the blockchain doesn't show that transaction ID or a send transaction on that date.

Please try this. After making a good backup of your wallet, run the "`zapwallettxes=2`" command on startup. This blog shows the steps (for Windows, others available). Just do Recovery part 2, C, C2 for starting qtumd with the `zapwallettxes` command. 

https://blog.qtum.org/hard-fork-special-windows-2c8febdbcd43

Does this work for you?

**Comment by munakaya** [comment]
yes, it is fixed. thank you a lot.

**Comment by JB395** [comment]
Very good. Take care.

**Comment by Earlz** [comment]
Closing as this seems to be answered
