### ISSUE TITLE
Error when unlocking Wallet...

### ISSUE THREAD

**Issue by Raptr4** [qtumproject/qtum#894]
Hi folks! I am going to try and outline my issue in hopes that someone here can help me...

I had 1080 QTUM on my QTUM core wallet. Unfortunately, this was version 15.2 of the wallet. And from my research here on the forums, my staking rewards on that wallet are completely useless and unsalvageable? Can someone confirm this?

Without my staking rewards, I had a initial dump of QTUM coins which I paid for back in 2017. This purchase totals to about 520 QTUM coins.

Back in early January 2021, I tried sending my 1080 QTUM to my Binance account. This transaction kept going and going and had over 30,000 confirmations but was still going up in confirmations and wasn't getting anywhere... This lead me to the above research I mentioned above.

So I made a backup file, and upgraded QTUM core wallet to the 20.1 version (latest as of this post). Sure enough only the 520 QTUM coins show up in this 20.1 version of the wallet.

When I try to send the 520 QTUM coins it asks me to unlock my wallet. When I use the correct password (I know it is correct) it give me an error message saying "passcode unlocks some but not all of your wallet, your wallet may be corrupted."

In efforts to trying to fix this I have jumped through multiple versions of the wallet but I keep getting the same error message. I also have tried going through the different options in the "Restore Wallet" tab.

Can someone please help me!!! Thank you so much!

**Comment by JB395** [comment]
1. Block rewards on a split chain after missing a hard for update are worthless.
2. Make some copies of your wallet.dat file and work on the copies. Try **salvagewallet** on startup. 
3. Try using any older backups of the wallet.dat file.
4. Long shot: try the **zapwallettxes=2** command on startup.
5. Use the **listaddressgroupings** command to see which addresses are holding the QTUM. 
6. If you can partially unlock your wallet, try the **dumprivkey** command to grab the private keys for those addresses. 

Not sure what else to suggest.
