### ISSUE TITLE
mainnet-ignition-v0.20.1 not syncing headers to 100%

### ISSUE THREAD

**Issue by MarkyMarkATFB** [qtumproject/qtum#895]
My mainnet CPU wallet isn't completing the sync. I was running an old version so upgraded to v0.20.1 and still the same issue. I read the above note but don't know how to runn memtest or linpack. Please advise as to a fix for my wallet or how to run above suggestions.

**Expected behavior**

 Wallet to sync to 100% in order to utilize my qtum tokens

**Actual behavior**

![frozen sync](https://user-images.githubusercontent.com/79244989/108315639-ebbd5480-7178-11eb-82e4-22247569a899.jpg)

**To reproduce**

 Every time I open my wallet it happens

**System information**

 v0.20.1, got it from github

 windows 8.1/toshiba laptop

windows 8.1

 It worked for a while, I didn't open the wallet for a couple days and when I went in it hasn't been able to sync to 100%

**Comment by JB395** [comment]
If your wallet gets stuck syncing the blockchain the best thing to do is exit the wallet, delete the local blockchain and resync the whole thing.

Make sure your have a good backup of the wallet, then exit the wallet, and in the Qtum data directory, delete the folders **blocks**, **chainstate** and **stateQtum**. Then restart the wallet.
