### ISSUE TITLE
pass phrase no longer working

### ISSUE THREAD

**Issue by daynagithub** [qtumproject/qtum#904]
I go to use my pass phrase and it says it is invalid. But it is not. I have used it many times before with NO issue.

Pass phrase is invalid, but it is not I know this for a fact
 I am unable to use the pass phrase that has ALWAYS worked in the past, a few weeks ago it now will not accept it. How do I resolve this issue. I cannot create a new one as it does not recognize the old one.

 It happens everytime

 0.20.

**Comment by JB395** [comment]
Wallet.dat passphrase authentication has worked correctly for 11 years. Some things to try:

Try with all the backup wallet.dat files you have, especially if they are unencrypted.
If you are using qtumd with command line, make sure you don't have "smart quotes", only standard straight quotes around the passphrase.
Make sure you are remembering UPPER CASE and lower case correctly.
Make sure you don't have extra blank spaces between words, or a trailing blank space (unless you entered it that way).
If you think this is related to the version of Qtum Core (probably not) install an earlier version and try to unlock.
Try close variations of your passphrase. 
Long shot: try a different keyboard.
