### ISSUE TITLE
syncing headers stuck at 5.79 % since nov.29th 2017

### ISSUE THREAD

**Issue by kessrob** [qtumproject/qtum#917]
I cannot get my qtum tokens out of my wallet.  I tried to transfer but system will not update.  please advise

**Comment by JB395** [comment]
If your wallet gets stuck syncing the blockchain the best thing to do is exit the wallet, delete the local blockchain and resync the whole thing. 

Make sure your have a good backup of the wallet, then exit the wallet, and in the Qtum data directory, delete the folders **blocks**, **chainstate** and **stateQtum**. Then restart the wallet.

![Delete These Folders](https://user-images.githubusercontent.com/29760787/112857483-e65bff80-907e-11eb-8ea7-3b50251730c7.jpg)
