### ISSUE TITLE
wallet.dat file overwritten

### ISSUE THREAD

**Issue by nphias** [qtumproject/qtum#919]
I downloaded a new version of qtum for ubuntu linux..
I ran the qtum GUI and expected it to use my previous wallet ... however when looking at the file system i see that in the .qtum directory all files have been overwritten including the wallet.dat file..
I guess that means i have lost all the tokens i had?...  if so i would call that a bug.  yes i know you tell people to backup their wallet files.. but i assumed that the software would not be retarded as to just overwrite someones wallet when they upgrade the qtum client..

**Comment by qtum-neil** [comment]
The wallet will never overwrite the wallet.dat file, check that you are using the same user as before.
