### ISSUE TITLE
QTUM RPi wallet closes when synching

### ISSUE THREAD

**Issue by ChristopherRush** [qtumproject/qtum#938]
I'm using a RPi 3B+ with the latest Buster OS image for QTUM. The first issue I encountered was that it wouldn't synch at all, stuck at 0%. I had to manually add the nodes for it to start to synch. 

The issue i'm having at the moment is that the wallet starts to synch but after 30-60mins or so the wallet just closes completely. I checked the log files and there is nothing to suggest any errors.

Any help/suggestions to look at would be appreciated.

**Comment by JB395** [comment]
The RPi 3B may be running out of memory. Try to setup a swap file per https://linuxize.com/post/create-a-linux-swap-file/

**Comment by ChristopherRush** [comment]
Thanks, but there is already a 1GB SWAP file created on the QTUM image here - https://docs.qtum.site/en/Qtum-on-Raspberry-Pi/#Downloading-Qtum-Raspbian

**Comment by JB395** [comment]
Okay, for that version. Try to monitor the resource usage with `top `as the blockchain syncs, for memory and swap. Is it still running out?

**Comment by ChristopherRush** [comment]
I checked this yesterday and here is the results just before it closed:
Memory - Total 932068 Used 641356 Free 34168
Swap - Total 1034460 Used 455424 Free 579036

**Comment by ChristopherRush** [comment]
I will test this on a 4B to see if there is any noticeable difference and get back to you.

**Comment by JB395** [comment]
My results for Raspberry Pi 3B on testnet simular:
Mem 38 free, 783 used, 108 buff/cache
Swap 422 free, 601 used, 79 avail Mem

Staking 10k UTXOs on testnet:
Mem 32 free 771 used, 122 buff/cache
Swap 359 free, 664 used, 92 buff/cache

My 4Bs run great, either 2 MB or 4 MB versions.

**Comment by ChristopherRush** [comment]
Tested 4B 4GB and everything was ok. Just running on the 4B 1GB version now. I have noticed the way the SWAP is setup is that it replicates the existing memory size of the Pi in use. Maybe this is an issue for 1GB models 3B+/4B.

**Comment by brockle9** [comment]
Hi Christopher, any updates on your additional testing?

**Comment by ChristopherRush** [comment]
Yes, everything worked ok after adding a 2GB SWAP file to a 1GB Pi. It took more than a week to fully synch but the application didn't crash. So it seems the current SWAP setup in the provided OS image is insufficient as it replicated the current memory size. I would suggest to update it with a minimum of 2GB SWAP on all images.

**Comment by ChristopherRush** [comment]
I would have done this myself and created a new OS image but I didn't want to change the default password from what it is.

**Comment by brockle9** [comment]
Hi Christopher, 

Would you check the stakebox support email?

**Comment by ChristopherRush** [comment]
Do you have a ticket number?

**Comment by brockle9** [comment]
ticket ID #233019
