### ISSUE TITLE
The test tap is no longer accessible, address http://testnet-faucet.qtum.info/

### ISSUE THREAD

**Issue by BecksWang** [qtumproject/qtum#972]
Hello, I am developing qtum on the test chain now, but I can't get test coins. The official test faucet cannot be opened.

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)
