### ISSUE TITLE
Issue after upgrading to 22.0

### ISSUE THREAD

**Issue by muratso** [qtumproject/qtum#984]
I recently upgraded our node from 0.20.4 to 22.0 and after the node finish syncing, I get the following error

```
terminate called after throwing an instance of 'NonFatalCheckError'
  what():  core_write.cpp:264 (TxToUniv)
Internal bug detected: 'MoneyRange(fee)'
You may report this issue here: https://github.com/qtumproject/qtum/issues
```

**Expected behavior**

The node finish syncing and keep "waiting" for the next blocks to come.

**Actual behavior**

The node syncs and dies with this error.

**To reproduce**

I simply upgraded the node.

**System information**

We're using the version **22.0**, the aarch64 binaries downloaded directly from github.
It's running in a docker image based on **amazonlinux** (just like the previous version was).

Here are the full logs before the node dies https://pastebin.com/raw/0Rjrn4FC

**Comment by qtum-neil** [comment]
We are aware of this issue, we will make a bug fix release soon

**Comment by qtum-neil** [comment]
Released: https://github.com/qtumproject/qtum/releases/tag/v22.1

**Comment by herryben** [comment]
您好，我已收到您的邮件，我会尽快给您回复。
